"""Source-derived PTX semantics audit. No native compilation or performance test."""
from pathlib import Path
import ast, re, random, json, hashlib, itertools
from ptx_field_model import Program, extract_ptx, function, check_semantics
W=Path(__file__).resolve().parent
import argparse
parser=argparse.ArgumentParser()
parser.add_argument('--baseline',type=Path,default=W/'baseline/candidates/pinning')
parser.add_argument('--candidate',type=Path,default=W/'candidate/candidates/pinning')
args=parser.parse_args()
C=args.candidate; B=args.baseline
if not C.exists(): C=W
M32=(1<<32)-1; M64=(1<<64)-1; U=1<<256; K=(1<<32)+977; P=U-K
check_semantics()
def asm_blocks(s):
    # Comments may occur between asm( and its first string; directives in fused
    # reduction are retained as source text, but never executed by this model.
    s=re.sub(r'/\*.*?\*/','',s,flags=re.S)
    out=[]
    for m in re.finditer(r'asm\s*\(([^:]*?)\s*:\s*"=l"',s,re.S):
        p=''.join(ast.literal_eval(x) for x in re.findall(r'"(?:[^"\\]|\\.)*"',m[1]))
        if 'mul.wide.u32 e0, a0, b0;' in p or 'mul.wide.u32 e6, a2, a4;' in p: out.append(p)
    assert len(out)==5,len(out)
    return out
base=(B/'GPUMath.h').read_text(); new=(C/'GPUMath.h').read_text()
ba=asm_blocks(base); na=asm_blocks(new)
# Exact row-carry reweighting: odd limb starts at bits 288,352,416;
# adjacent even carry has precisely +32 bits of weight. Both carry sources
# are generated by addc.u32 ...,0,0, hence are bits, not full limbs.
def product_rewrite(p):
    assert p.count('cvt.u64.u32 odd_lc, odd_cy;')==3
    assert p.count('cvt.u64.u32 lc, cy;')==3
    assert p.count('addc.u32 cy, 0, 0;')==3
    assert p.count('addc.u32 odd_cy, 0, 0;')==3
    p=p.replace('cvt.u64.u32 odd_lc, odd_cy;\n','')
    p=p.replace('cvt.u64.u32 lc, cy;','mov.b64 odd_lc, {odd_cy, cy};')
    for i in [5,6,7]:
        assert p.count(f'addc.u64 e{i}, t, lc;')==1
        p=p.replace(f'addc.u64 e{i}, t, lc;',f'addc.u64 e{i}, t, 0;')
    return p
for i in [0,1]: assert product_rewrite(ba[i])==na[i]
assert M32*M32+1+1+(1<<32)<1<<64
# Prove exact square edits are only the five bounded fresh-word carry-outs.
def sqr_rewrite(p):
    edits=[('addc.cc.u64 o9, odd_t, 0;\naddc.u32 ocy, 0, 0;','addc.u64 o9, odd_t, 0;'),
    ('addc.cc.u64 e10, t, 0;\naddc.u32 ecy, 0, 0;\nmov.b64 o11, {ocy,0};\nmov.b64 e12, {ecy,0};','addc.u64 e10, t, 0;'),
    ('addc.cc.u64 o11, o11, odd_t;\naddc.u32 ocy, 0, 0;','addc.u64 o11, odd_t, 0;'),
    ('addc.cc.u64 e12, e12, t;\naddc.u32 e14, 0, 0;\nmov.b64 o13, {ocy,0};','addc.u64 e12, t, 0;'),
    ('addc.cc.u64 o13, o13, odd_t;\naddc.u32 o15, 0, 0;','addc.u64 o13, odd_t, 0;'),
    ('mov.u32 x14, e14;','mov.u32 x14, 0;'),('addc.u32 x15, x15, o15;','addc.u32 x15, x15, 0;')]
    for a,b in edits:
        assert p.count(a)==1,a
        p=p.replace(a,b)
    return p
norm=lambda s:re.sub(r'\s+','',s)
for i in [2,3,4]: assert norm(sqr_rewrite(ba[i]))==norm(na[i])
assert M32*M32+2 < 1<<64
# Fresh o9/e10 are product+carry <= maxproduct+1, so old ocy/ecy=0;
# then o11/e12 start at zero, again product+carry; o13 likewise. This
# proves the removed carries by induction, without random-input assumptions.
# Prefix ends before any modular reduction. Verify exact 512-bit products.
def prefix(p,square):
    marker='.reg .u64 fr0' if square else '.reg .u64 r0,r1,r2,r3,h0'
    head=p[:p.index(marker)]
    return Program(head+'\n'+''.join(f'mov.b64 %{i}, {{x{2*i},x{2*i+1}}};' for i in range(8))+'}')
def limbs(x):return [(x>>(64*i))&M64 for i in range(4)]
def integer(v):return sum(x<<(64*i) for i,x in enumerate(v))
programs=[(prefix(ba[i],i>=2),prefix(na[i],i>=2)) for i in range(5)]
full=[(Program(ba[i]),Program(na[i])) for i in range(4)]
bs=extract_ptx(function((B/'pinning.cu').read_text(),'void qsb_field_mul('))
ns=extract_ptx(function((C/'pinning.cu').read_text(),'void qsb_field_mul('))
assert product_rewrite(bs)==ns
assert bs.count('take')==ns.count('take')==1
raw=[Program(s.replace('.reg .pred take;','')) for s in [bs,ns]]
# Removing the tested asm and undoing the single independent-call reorder must
# reproduce the entire original GPUMath header byte-for-byte.
import difflib
changes=list(difflib.SequenceMatcher(None,base.splitlines(True),new.splitlines(True)).get_opcodes())
allowed=[]
for tag,a,b,c,d in changes:
    if tag=='equal':continue
    oldlines=base.splitlines(True)[a:b];newlines=new.splitlines(True)[c:d]
    assert all(('"' in x or '_ModMult(ZZ1, PP)' in x or '// on the paired-carry' in x) for x in oldlines+newlines),(a,b)
    allowed.append([a+1,b,c+1,d])
# Verify no intervening operation modifies PP, ZZ1 or ZZZ1; exact known body.
def pointbody(s):
    m=re.search(r'void _PointAddXYZZT\([^;]*?\)\s*\{',s)
    assert m
    return function(s[m.start():],'void _PointAddXYZZT(')
f0=pointbody(base);f1=pointbody(new)
move='  _ModMult(ZZ1, PP);                   // ZZ3; PP dies before the R^2/Y3 tail\n'
insert='  _ModMult(ZZ1, PP);                   // ZZ3 (after ZZZ3: lets ptxas keep every multiply\n                                       // on the paired-carry schedule without predicate spills)\n'
assert f0.replace(move,'')==f1.replace(insert,'')
mid=f0[f0.index(move)+len(move):f0.index('  _ModMult(ZZZ1, PPP);')]
assert 'ZZ1' not in mid and 'ZZZ1' not in mid and not re.search(r'\(PP[,)]',mid)
# Full candidate driver differs in exactly this function; all other source
# files (except research/manifest) must still be promoted baseline bytes.
assert (B/'pinning.cu').read_text().replace(function((B/'pinning.cu').read_text(),'void qsb_field_mul('),'FUNCTION')==(C/'pinning.cu').read_text().replace(function((C/'pinning.cu').read_text(),'void qsb_field_mul('),'FUNCTION')
for path in B.iterdir():
    if path.name not in ['GPUMath.h','pinning.cu','SOURCE-MANIFEST.json','RESEARCH.md']:assert path.read_bytes()==(C/path.name).read_bytes(),path.name
rng=random.Random(2026092002)
edges=[0,1,2,K-1,K,K+1,P-K,P-65537,P-2,P-1,P,P+1,U-2,U-1]
vectors=list(itertools.product(edges,repeat=2))
choices=[0,1,2,977,0x7fffffff,0x80000000,0xfffffffe,0xffffffff,0xfffffc2f]
for _ in range(2048):
 vectors.append(tuple(sum(rng.choice(choices)<<(32*i) for i in range(8)) for _ in range(2)))
for _ in range(2048): vectors.append((rng.getrandbits(256),rng.getrandbits(256)))
for a,b in vectors:
    for i,(old,newprog) in enumerate(programs):
        args=limbs(a)+(limbs(b) if i<2 else [])
        expected=a*b if i<2 else a*a
        assert integer(old.run(args,outputs=8))==expected
        assert integer(newprog.run(args,outputs=8))==expected
    for i,(old,newprog) in enumerate(full):
        args=limbs(a)+(limbs(b) if i<2 else [])
        assert old.run(args)==newprog.run(args)
    r0,r1=[integer(p.run(limbs(a)+limbs(b))) for p in raw]
    assert r0==r1 and r1%P==a*b%P
# Counter-tests: each unsafe omission must be detected by the same corpus.
mutants=[prefix(na[0].replace('mov.b64 odd_lc, {odd_cy, cy};','mov.b64 odd_lc, {odd_cy, 0};',1),False),
 prefix(na[0].replace('mov.b64 odd_lc, {odd_cy, cy};','mov.b64 odd_lc, {0, cy};',1),False),
 prefix(na[2].replace('addc.cc.u64 o7, o7, odd_t;','add.cc.u64 o7, o7, odd_t;',1),True)]
failed=[0,0,0]
for a,b in vectors:
 for i,p in enumerate(mutants):
  expected=a*a if i==2 else a*b
  failed[i]+=integer(p.run(limbs(a)+(limbs(b) if i<2 else []),outputs=8))!=expected
assert all(failed),failed
result={'status':'PASS','vectors':len(vectors),'exact_512bit_prefix_executions':len(vectors)*10,'full_primitive_pair_comparisons':len(vectors)*4,'carry_complete_raw_pairs':len(vectors),'mutant_mismatches':failed,'instruction_counts':{'base':[len(Program(x).ops) for x in ba[:4]],'new':[len(Program(x).ops) for x in na[:4]],'tree_base':len(raw[0].ops),'tree_new':len(raw[1].ops)},'bounds':{'square_margin':(1<<64)-(M32*M32+2),'paired_margin':(1<<64)-(M32*M32+2+(1<<32))},'header_changed_ranges':allowed,'sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [C/'GPUMath.h',C/'pinning.cu']},'limitations':'Python PTX semantics only. No CUDA compilation, JIT or throughput measurement. Header reduction retains promoted approximations; tree/recovery keeps complete reduction.'}
print(json.dumps(result,indent=2))
