/* cg_v29asm.h -- generated by gen/gen_v29.py; do not edit.
 * AVX2 4-lane secp256k1 field multiply / square, radix 2^29 (9 limbs), one element per 64-bit lane.
 * Constant table [k] (32 bytes per entry): 0x1fffffff, 0x7a20, 0xffffff, 0x3d1, 0x7a2000 broadcast to 4 lanes, then the VPSHUFB lane masks for << 8 and << 16. r must not alias b. */
#define QCG_V29_KTAB_QWORDS 28
#define QCG_V29_KTAB_INIT 0x1fffffffULL, 0x1fffffffULL, 0x1fffffffULL, 0x1fffffffULL, 0x7a20ULL, 0x7a20ULL, 0x7a20ULL, 0x7a20ULL, 0xffffffULL, 0xffffffULL, 0xffffffULL, 0xffffffULL, 0x3d1ULL, 0x3d1ULL, 0x3d1ULL, 0x3d1ULL, 0x7a2000ULL, 0x7a2000ULL, 0x7a2000ULL, 0x7a2000ULL, 0x605040302010080ULL, 0xe0d0c0b0a090880ULL, 0x605040302010080ULL, 0xe0d0c0b0a090880ULL, 0x504030201008080ULL, 0xd0c0b0a09088080ULL, 0x504030201008080ULL, 0xd0c0b0a09088080ULL
/* mul: 266 instructions (92 vpmuludq), sqr: 209 instructions (56 vpmuludq) */
#define QCG_V29_MUL_ASM \
    "vmovdqa 0(%[a]), %%ymm0\n\t" \
    "vmovdqa 32(%[a]), %%ymm1\n\t" \
    "vmovdqa 64(%[a]), %%ymm2\n\t" \
    "vmovdqa 96(%[a]), %%ymm3\n\t" \
    "vmovdqa 128(%[a]), %%ymm4\n\t" \
    "vmovdqa 160(%[a]), %%ymm5\n\t" \
    "vmovdqa 192(%[a]), %%ymm6\n\t" \
    "vmovdqa 224(%[a]), %%ymm7\n\t" \
    "vmovdqa 256(%[a]), %%ymm8\n\t" \
    "vpmuludq 256(%[b]), %%ymm0, %%ymm9\n\t" \
    "vpmuludq 224(%[b]), %%ymm1, %%ymm10\n\t" \
    "vpmuludq 192(%[b]), %%ymm2, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 160(%[b]), %%ymm3, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 128(%[b]), %%ymm4, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 96(%[b]), %%ymm5, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 64(%[b]), %%ymm6, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[b]), %%ymm7, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 0(%[b]), %%ymm8, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm9, %%ymm9\n\t" \
    "vpaddq %%ymm10, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm10\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 0(%[b]), %%ymm0, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm1, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm2, %%ymm13\n\t" \
    "vpmuludq 192(%[b]), %%ymm3, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 160(%[b]), %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 128(%[b]), %%ymm5, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 96(%[b]), %%ymm6, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 64(%[b]), %%ymm7, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 32(%[b]), %%ymm8, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 0(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[b]), %%ymm0, %%ymm12\n\t" \
    "vpmuludq 0(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm2, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm3, %%ymm13\n\t" \
    "vpmuludq 192(%[b]), %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 160(%[b]), %%ymm5, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 128(%[b]), %%ymm6, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 96(%[b]), %%ymm7, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 64(%[b]), %%ymm8, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 32(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 64(%[b]), %%ymm0, %%ymm12\n\t" \
    "vpmuludq 32(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpmuludq 0(%[b]), %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpmuludq 192(%[b]), %%ymm5, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 160(%[b]), %%ymm6, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 128(%[b]), %%ymm7, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 96(%[b]), %%ymm8, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 64(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 96(%[b]), %%ymm0, %%ymm12\n\t" \
    "vpmuludq 64(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpmuludq 32(%[b]), %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 0(%[b]), %%ymm3, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm4, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm5, %%ymm13\n\t" \
    "vpmuludq 192(%[b]), %%ymm6, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 160(%[b]), %%ymm7, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 128(%[b]), %%ymm8, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 96(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 128(%[b]), %%ymm0, %%ymm12\n\t" \
    "vpmuludq 96(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpmuludq 64(%[b]), %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 32(%[b]), %%ymm3, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 0(%[b]), %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpmuludq 192(%[b]), %%ymm7, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 160(%[b]), %%ymm8, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 128(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 160(%[b]), %%ymm0, %%ymm12\n\t" \
    "vpmuludq 128(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpmuludq 96(%[b]), %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 64(%[b]), %%ymm3, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 32(%[b]), %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 0(%[b]), %%ymm5, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm6, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm7, %%ymm13\n\t" \
    "vpmuludq 192(%[b]), %%ymm8, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 160(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 192(%[b]), %%ymm0, %%ymm12\n\t" \
    "vpmuludq 160(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpmuludq 128(%[b]), %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 96(%[b]), %%ymm3, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 64(%[b]), %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq 32(%[b]), %%ymm5, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpmuludq 0(%[b]), %%ymm6, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpmuludq 224(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 192(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm0, %%ymm0\n\t" \
    "vpmuludq 192(%[b]), %%ymm1, %%ymm1\n\t" \
    "vpmuludq 160(%[b]), %%ymm2, %%ymm2\n\t" \
    "vpaddq %%ymm2, %%ymm0, %%ymm0\n\t" \
    "vpmuludq 128(%[b]), %%ymm3, %%ymm3\n\t" \
    "vpaddq %%ymm3, %%ymm1, %%ymm1\n\t" \
    "vpmuludq 96(%[b]), %%ymm4, %%ymm4\n\t" \
    "vpaddq %%ymm4, %%ymm0, %%ymm0\n\t" \
    "vpmuludq 64(%[b]), %%ymm5, %%ymm5\n\t" \
    "vpaddq %%ymm5, %%ymm1, %%ymm1\n\t" \
    "vpmuludq 32(%[b]), %%ymm6, %%ymm6\n\t" \
    "vpaddq %%ymm6, %%ymm0, %%ymm0\n\t" \
    "vpmuludq 0(%[b]), %%ymm7, %%ymm7\n\t" \
    "vpaddq %%ymm7, %%ymm1, %%ymm1\n\t" \
    "vpaddq %%ymm1, %%ymm0, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm8, %%ymm8\n\t" \
    "vpaddq %%ymm8, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm0\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm0, %%ymm1\n\t" \
    "vpaddq %%ymm1, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm1\n\t" \
    "vmovdqa %%ymm1, 224(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm0, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm9, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm10, %%ymm11, %%ymm11\n\t" \
    "vpand 64(%[k]), %%ymm11, %%ymm0\n\t" \
    "vmovdqa %%ymm0, 256(%[r])\n\t" \
    "vpsrlq $24, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 96(%[k]), %%ymm11, %%ymm0\n\t" \
    "vpmuludq 128(%[k]), %%ymm9, %%ymm1\n\t" \
    "vpaddq %%ymm1, %%ymm0, %%ymm0\n\t" \
    "vpaddq 0(%[r]), %%ymm0, %%ymm0\n\t" \
    "vpand 0(%[k]), %%ymm0, %%ymm1\n\t" \
    "vmovdqa %%ymm1, 0(%[r])\n\t" \
    "vpsrlq $29, %%ymm0, %%ymm0\n\t" \
    "vpsllq $3, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm0, %%ymm0\n\t" \
    "vpshufb 192(%[k]), %%ymm9, %%ymm9\n\t" \
    "vpaddq %%ymm9, %%ymm0, %%ymm0\n\t" \
    "vpaddq 32(%[r]), %%ymm0, %%ymm0\n\t" \
    "vpand 0(%[k]), %%ymm0, %%ymm1\n\t" \
    "vmovdqa %%ymm1, 32(%[r])\n\t" \
    "vpsrlq $29, %%ymm0, %%ymm0\n\t" \
    "vpaddq 64(%[r]), %%ymm0, %%ymm0\n\t" \
    "vmovdqa %%ymm0, 64(%[r])\n\t" \

#define QCG_V29_SQR_ASM \
    "vmovdqa 0(%[a]), %%ymm0\n\t" \
    "vmovdqa 32(%[a]), %%ymm1\n\t" \
    "vmovdqa 64(%[a]), %%ymm2\n\t" \
    "vmovdqa 96(%[a]), %%ymm3\n\t" \
    "vmovdqa 128(%[a]), %%ymm4\n\t" \
    "vmovdqa 160(%[a]), %%ymm5\n\t" \
    "vmovdqa 192(%[a]), %%ymm6\n\t" \
    "vmovdqa 224(%[a]), %%ymm7\n\t" \
    "vmovdqa 256(%[a]), %%ymm8\n\t" \
    "vpmuludq %%ymm8, %%ymm0, %%ymm9\n\t" \
    "vpmuludq %%ymm7, %%ymm1, %%ymm10\n\t" \
    "vpmuludq %%ymm6, %%ymm2, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm9, %%ymm9\n\t" \
    "vpmuludq %%ymm5, %%ymm3, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm10, %%ymm10\n\t" \
    "vpaddq %%ymm10, %%ymm9, %%ymm9\n\t" \
    "vpaddq %%ymm9, %%ymm9, %%ymm9\n\t" \
    "vpmuludq %%ymm4, %%ymm4, %%ymm10\n\t" \
    "vpaddq %%ymm10, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm10\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq %%ymm0, %%ymm0, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm1, %%ymm12\n\t" \
    "vpmuludq %%ymm7, %%ymm2, %%ymm13\n\t" \
    "vpmuludq %%ymm6, %%ymm3, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm5, %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 0(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm1, %%ymm0, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm2, %%ymm12\n\t" \
    "vpmuludq %%ymm7, %%ymm3, %%ymm13\n\t" \
    "vpmuludq %%ymm6, %%ymm4, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm5, %%ymm5, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 32(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm2, %%ymm0, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm1, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm3, %%ymm12\n\t" \
    "vpmuludq %%ymm7, %%ymm4, %%ymm13\n\t" \
    "vpmuludq %%ymm6, %%ymm5, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 64(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm3, %%ymm0, %%ymm12\n\t" \
    "vpmuludq %%ymm2, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm4, %%ymm12\n\t" \
    "vpmuludq %%ymm7, %%ymm5, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm6, %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 96(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm4, %%ymm0, %%ymm12\n\t" \
    "vpmuludq %%ymm3, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm2, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm5, %%ymm12\n\t" \
    "vpmuludq %%ymm7, %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 128(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm5, %%ymm0, %%ymm12\n\t" \
    "vpmuludq %%ymm4, %%ymm1, %%ymm13\n\t" \
    "vpmuludq %%ymm3, %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm7, %%ymm7, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 160(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm6, %%ymm0, %%ymm12\n\t" \
    "vpmuludq %%ymm5, %%ymm1, %%ymm13\n\t" \
    "vpmuludq %%ymm4, %%ymm2, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpmuludq %%ymm3, %%ymm3, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm12\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm12, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vmovdqa %%ymm13, 192(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm7, %%ymm0, %%ymm0\n\t" \
    "vpmuludq %%ymm6, %%ymm1, %%ymm1\n\t" \
    "vpmuludq %%ymm5, %%ymm2, %%ymm2\n\t" \
    "vpaddq %%ymm2, %%ymm0, %%ymm0\n\t" \
    "vpmuludq %%ymm4, %%ymm3, %%ymm3\n\t" \
    "vpaddq %%ymm3, %%ymm1, %%ymm1\n\t" \
    "vpaddq %%ymm1, %%ymm0, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm0, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm8, %%ymm8, %%ymm8\n\t" \
    "vpaddq %%ymm8, %%ymm9, %%ymm9\n\t" \
    "vpand 0(%[k]), %%ymm9, %%ymm0\n\t" \
    "vpsrlq $29, %%ymm9, %%ymm9\n\t" \
    "vpmuludq 32(%[k]), %%ymm0, %%ymm1\n\t" \
    "vpaddq %%ymm1, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm1\n\t" \
    "vmovdqa %%ymm1, 224(%[r])\n\t" \
    "vpsrlq $29, %%ymm11, %%ymm11\n\t" \
    "vpshufb 160(%[k]), %%ymm0, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm9, %%ymm0\n\t" \
    "vpaddq %%ymm0, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm10, %%ymm11, %%ymm11\n\t" \
    "vpand 64(%[k]), %%ymm11, %%ymm0\n\t" \
    "vmovdqa %%ymm0, 256(%[r])\n\t" \
    "vpsrlq $24, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 96(%[k]), %%ymm11, %%ymm0\n\t" \
    "vpmuludq 128(%[k]), %%ymm9, %%ymm1\n\t" \
    "vpaddq %%ymm1, %%ymm0, %%ymm0\n\t" \
    "vpaddq 0(%[r]), %%ymm0, %%ymm0\n\t" \
    "vpand 0(%[k]), %%ymm0, %%ymm1\n\t" \
    "vmovdqa %%ymm1, 0(%[r])\n\t" \
    "vpsrlq $29, %%ymm0, %%ymm0\n\t" \
    "vpsllq $3, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm11, %%ymm0, %%ymm0\n\t" \
    "vpshufb 192(%[k]), %%ymm9, %%ymm9\n\t" \
    "vpaddq %%ymm9, %%ymm0, %%ymm0\n\t" \
    "vpaddq 32(%[r]), %%ymm0, %%ymm0\n\t" \
    "vpand 0(%[k]), %%ymm0, %%ymm1\n\t" \
    "vmovdqa %%ymm1, 32(%[r])\n\t" \
    "vpsrlq $29, %%ymm0, %%ymm0\n\t" \
    "vpaddq 64(%[r]), %%ymm0, %%ymm0\n\t" \
    "vmovdqa %%ymm0, 64(%[r])\n\t" \

#ifdef QCG_V29_WANT_C
/* C versions of the same programs (need V, vfe, VMUL, vs1, QV_INL in scope) */
static QV_INL void v29_mul_c(vfe *rr, const vfe *aa, const vfe *bb) {
    const V *a = aa->n; const V *b = bb->n;
    V r[9];
    const V v1 = a[0];
    const V v2 = a[1];
    const V v3 = a[2];
    const V v4 = a[3];
    const V v5 = a[4];
    const V v6 = a[5];
    const V v7 = a[6];
    const V v8 = a[7];
    const V v9 = a[8];
    const V v10 = VMUL(v1, b[8]);
    const V v11 = VMUL(v2, b[7]);
    const V v12 = VMUL(v3, b[6]);
    const V v13 = v10 + v12;
    const V v14 = VMUL(v4, b[5]);
    const V v15 = v11 + v14;
    const V v16 = VMUL(v5, b[4]);
    const V v17 = v13 + v16;
    const V v18 = VMUL(v6, b[3]);
    const V v19 = v15 + v18;
    const V v20 = VMUL(v7, b[2]);
    const V v21 = v17 + v20;
    const V v22 = VMUL(v8, b[1]);
    const V v23 = v19 + v22;
    const V v24 = VMUL(v9, b[0]);
    const V v25 = v21 + v24;
    const V v26 = v25 + v23;
    const V v27 = v26 & vs1(0x1fffffffULL);
    const V v28 = v26 >> 29;
    const V v29 = VMUL(v1, b[0]);
    const V v30 = VMUL(v2, b[8]);
    const V v31 = VMUL(v3, b[7]);
    const V v32 = VMUL(v4, b[6]);
    const V v33 = v30 + v32;
    const V v34 = VMUL(v5, b[5]);
    const V v35 = v31 + v34;
    const V v36 = VMUL(v6, b[4]);
    const V v37 = v33 + v36;
    const V v38 = VMUL(v7, b[3]);
    const V v39 = v35 + v38;
    const V v40 = VMUL(v8, b[2]);
    const V v41 = v37 + v40;
    const V v42 = VMUL(v9, b[1]);
    const V v43 = v39 + v42;
    const V v44 = v41 + v43;
    const V v45 = v28 + v44;
    const V v46 = v45 & vs1(0x1fffffffULL);
    const V v47 = v45 >> 29;
    const V v48 = VMUL(v46, vs1(0x7a20ULL));
    const V v49 = v29 + v48;
    const V v50 = v49 & vs1(0x1fffffffULL);
    r[0] = v50;
    const V v51 = v49 >> 29;
    const V v52 = v46 << 8;
    const V v53 = v51 + v52;
    const V v54 = VMUL(v1, b[1]);
    const V v55 = VMUL(v2, b[0]);
    const V v56 = v54 + v55;
    const V v57 = v53 + v56;
    const V v58 = VMUL(v3, b[8]);
    const V v59 = VMUL(v4, b[7]);
    const V v60 = VMUL(v5, b[6]);
    const V v61 = v58 + v60;
    const V v62 = VMUL(v6, b[5]);
    const V v63 = v59 + v62;
    const V v64 = VMUL(v7, b[4]);
    const V v65 = v61 + v64;
    const V v66 = VMUL(v8, b[3]);
    const V v67 = v63 + v66;
    const V v68 = VMUL(v9, b[2]);
    const V v69 = v65 + v68;
    const V v70 = v69 + v67;
    const V v71 = v47 + v70;
    const V v72 = v71 & vs1(0x1fffffffULL);
    const V v73 = v71 >> 29;
    const V v74 = VMUL(v72, vs1(0x7a20ULL));
    const V v75 = v57 + v74;
    const V v76 = v75 & vs1(0x1fffffffULL);
    r[1] = v76;
    const V v77 = v75 >> 29;
    const V v78 = v72 << 8;
    const V v79 = v77 + v78;
    const V v80 = VMUL(v1, b[2]);
    const V v81 = VMUL(v2, b[1]);
    const V v82 = VMUL(v3, b[0]);
    const V v83 = v80 + v82;
    const V v84 = v83 + v81;
    const V v85 = v79 + v84;
    const V v86 = VMUL(v4, b[8]);
    const V v87 = VMUL(v5, b[7]);
    const V v88 = VMUL(v6, b[6]);
    const V v89 = v86 + v88;
    const V v90 = VMUL(v7, b[5]);
    const V v91 = v87 + v90;
    const V v92 = VMUL(v8, b[4]);
    const V v93 = v89 + v92;
    const V v94 = VMUL(v9, b[3]);
    const V v95 = v91 + v94;
    const V v96 = v93 + v95;
    const V v97 = v73 + v96;
    const V v98 = v97 & vs1(0x1fffffffULL);
    const V v99 = v97 >> 29;
    const V v100 = VMUL(v98, vs1(0x7a20ULL));
    const V v101 = v85 + v100;
    const V v102 = v101 & vs1(0x1fffffffULL);
    r[2] = v102;
    const V v103 = v101 >> 29;
    const V v104 = v98 << 8;
    const V v105 = v103 + v104;
    const V v106 = VMUL(v1, b[3]);
    const V v107 = VMUL(v2, b[2]);
    const V v108 = VMUL(v3, b[1]);
    const V v109 = v106 + v108;
    const V v110 = VMUL(v4, b[0]);
    const V v111 = v107 + v110;
    const V v112 = v109 + v111;
    const V v113 = v105 + v112;
    const V v114 = VMUL(v5, b[8]);
    const V v115 = VMUL(v6, b[7]);
    const V v116 = VMUL(v7, b[6]);
    const V v117 = v114 + v116;
    const V v118 = VMUL(v8, b[5]);
    const V v119 = v115 + v118;
    const V v120 = VMUL(v9, b[4]);
    const V v121 = v117 + v120;
    const V v122 = v121 + v119;
    const V v123 = v99 + v122;
    const V v124 = v123 & vs1(0x1fffffffULL);
    const V v125 = v123 >> 29;
    const V v126 = VMUL(v124, vs1(0x7a20ULL));
    const V v127 = v113 + v126;
    const V v128 = v127 & vs1(0x1fffffffULL);
    r[3] = v128;
    const V v129 = v127 >> 29;
    const V v130 = v124 << 8;
    const V v131 = v129 + v130;
    const V v132 = VMUL(v1, b[4]);
    const V v133 = VMUL(v2, b[3]);
    const V v134 = VMUL(v3, b[2]);
    const V v135 = v132 + v134;
    const V v136 = VMUL(v4, b[1]);
    const V v137 = v133 + v136;
    const V v138 = VMUL(v5, b[0]);
    const V v139 = v135 + v138;
    const V v140 = v139 + v137;
    const V v141 = v131 + v140;
    const V v142 = VMUL(v6, b[8]);
    const V v143 = VMUL(v7, b[7]);
    const V v144 = VMUL(v8, b[6]);
    const V v145 = v142 + v144;
    const V v146 = VMUL(v9, b[5]);
    const V v147 = v143 + v146;
    const V v148 = v145 + v147;
    const V v149 = v125 + v148;
    const V v150 = v149 & vs1(0x1fffffffULL);
    const V v151 = v149 >> 29;
    const V v152 = VMUL(v150, vs1(0x7a20ULL));
    const V v153 = v141 + v152;
    const V v154 = v153 & vs1(0x1fffffffULL);
    r[4] = v154;
    const V v155 = v153 >> 29;
    const V v156 = v150 << 8;
    const V v157 = v155 + v156;
    const V v158 = VMUL(v1, b[5]);
    const V v159 = VMUL(v2, b[4]);
    const V v160 = VMUL(v3, b[3]);
    const V v161 = v158 + v160;
    const V v162 = VMUL(v4, b[2]);
    const V v163 = v159 + v162;
    const V v164 = VMUL(v5, b[1]);
    const V v165 = v161 + v164;
    const V v166 = VMUL(v6, b[0]);
    const V v167 = v163 + v166;
    const V v168 = v165 + v167;
    const V v169 = v157 + v168;
    const V v170 = VMUL(v7, b[8]);
    const V v171 = VMUL(v8, b[7]);
    const V v172 = VMUL(v9, b[6]);
    const V v173 = v170 + v172;
    const V v174 = v173 + v171;
    const V v175 = v151 + v174;
    const V v176 = v175 & vs1(0x1fffffffULL);
    const V v177 = v175 >> 29;
    const V v178 = VMUL(v176, vs1(0x7a20ULL));
    const V v179 = v169 + v178;
    const V v180 = v179 & vs1(0x1fffffffULL);
    r[5] = v180;
    const V v181 = v179 >> 29;
    const V v182 = v176 << 8;
    const V v183 = v181 + v182;
    const V v184 = VMUL(v1, b[6]);
    const V v185 = VMUL(v2, b[5]);
    const V v186 = VMUL(v3, b[4]);
    const V v187 = v184 + v186;
    const V v188 = VMUL(v4, b[3]);
    const V v189 = v185 + v188;
    const V v190 = VMUL(v5, b[2]);
    const V v191 = v187 + v190;
    const V v192 = VMUL(v6, b[1]);
    const V v193 = v189 + v192;
    const V v194 = VMUL(v7, b[0]);
    const V v195 = v191 + v194;
    const V v196 = v195 + v193;
    const V v197 = v183 + v196;
    const V v198 = VMUL(v8, b[8]);
    const V v199 = VMUL(v9, b[7]);
    const V v200 = v198 + v199;
    const V v201 = v177 + v200;
    const V v202 = v201 & vs1(0x1fffffffULL);
    const V v203 = v201 >> 29;
    const V v204 = VMUL(v202, vs1(0x7a20ULL));
    const V v205 = v197 + v204;
    const V v206 = v205 & vs1(0x1fffffffULL);
    r[6] = v206;
    const V v207 = v205 >> 29;
    const V v208 = v202 << 8;
    const V v209 = v207 + v208;
    const V v210 = VMUL(v1, b[7]);
    const V v211 = VMUL(v2, b[6]);
    const V v212 = VMUL(v3, b[5]);
    const V v213 = v210 + v212;
    const V v214 = VMUL(v4, b[4]);
    const V v215 = v211 + v214;
    const V v216 = VMUL(v5, b[3]);
    const V v217 = v213 + v216;
    const V v218 = VMUL(v6, b[2]);
    const V v219 = v215 + v218;
    const V v220 = VMUL(v7, b[1]);
    const V v221 = v217 + v220;
    const V v222 = VMUL(v8, b[0]);
    const V v223 = v219 + v222;
    const V v224 = v221 + v223;
    const V v225 = v209 + v224;
    const V v226 = VMUL(v9, b[8]);
    const V v227 = v203 + v226;
    const V v228 = v227 & vs1(0x1fffffffULL);
    const V v229 = v227 >> 29;
    const V v230 = VMUL(v228, vs1(0x7a20ULL));
    const V v231 = v225 + v230;
    const V v232 = v231 & vs1(0x1fffffffULL);
    r[7] = v232;
    const V v233 = v231 >> 29;
    const V v234 = v228 << 8;
    const V v235 = v233 + v234;
    const V v236 = VMUL(v229, vs1(0x7a20ULL));
    const V v237 = v235 + v236;
    const V v238 = v237 + v27;
    const V v239 = v238 & vs1(0xffffffULL);
    r[8] = v239;
    const V v240 = v238 >> 24;
    const V v241 = VMUL(v240, vs1(0x3d1ULL));
    const V v242 = VMUL(v229, vs1(0x7a2000ULL));
    const V v243 = v241 + v242;
    const V v244 = v243 + r[0];
    const V v245 = v244 & vs1(0x1fffffffULL);
    r[0] = v245;
    const V v246 = v244 >> 29;
    const V v247 = v240 << 3;
    const V v248 = v246 + v247;
    const V v249 = v229 << 16;
    const V v250 = v248 + v249;
    const V v251 = v250 + r[1];
    const V v252 = v251 & vs1(0x1fffffffULL);
    r[1] = v252;
    const V v253 = v251 >> 29;
    const V v254 = v253 + r[2];
    r[2] = v254;
    for (int k = 0; k < 9; k++) rr->n[k] = r[k];
}
static QV_INL void v29_sqr_c(vfe *rr, const vfe *aa) {
    const V *a = aa->n;
    V r[9];
    const V v1 = a[0];
    const V v2 = a[1];
    const V v3 = a[2];
    const V v4 = a[3];
    const V v5 = a[4];
    const V v6 = a[5];
    const V v7 = a[6];
    const V v8 = a[7];
    const V v9 = a[8];
    const V v10 = VMUL(v1, v9);
    const V v11 = VMUL(v2, v8);
    const V v12 = VMUL(v3, v7);
    const V v13 = v10 + v12;
    const V v14 = VMUL(v4, v6);
    const V v15 = v11 + v14;
    const V v16 = v13 + v15;
    const V v17 = v16 + v16;
    const V v18 = VMUL(v5, v5);
    const V v19 = v17 + v18;
    const V v20 = v19 & vs1(0x1fffffffULL);
    const V v21 = v19 >> 29;
    const V v22 = VMUL(v1, v1);
    const V v23 = VMUL(v2, v9);
    const V v24 = VMUL(v3, v8);
    const V v25 = VMUL(v4, v7);
    const V v26 = v23 + v25;
    const V v27 = VMUL(v5, v6);
    const V v28 = v24 + v27;
    const V v29 = v26 + v28;
    const V v30 = v29 + v29;
    const V v31 = v21 + v30;
    const V v32 = v31 & vs1(0x1fffffffULL);
    const V v33 = v31 >> 29;
    const V v34 = VMUL(v32, vs1(0x7a20ULL));
    const V v35 = v22 + v34;
    const V v36 = v35 & vs1(0x1fffffffULL);
    r[0] = v36;
    const V v37 = v35 >> 29;
    const V v38 = v32 << 8;
    const V v39 = v37 + v38;
    const V v40 = VMUL(v1, v2);
    const V v41 = v40 + v40;
    const V v42 = v39 + v41;
    const V v43 = VMUL(v3, v9);
    const V v44 = VMUL(v4, v8);
    const V v45 = VMUL(v5, v7);
    const V v46 = v43 + v45;
    const V v47 = v46 + v44;
    const V v48 = v47 + v47;
    const V v49 = VMUL(v6, v6);
    const V v50 = v48 + v49;
    const V v51 = v33 + v50;
    const V v52 = v51 & vs1(0x1fffffffULL);
    const V v53 = v51 >> 29;
    const V v54 = VMUL(v52, vs1(0x7a20ULL));
    const V v55 = v42 + v54;
    const V v56 = v55 & vs1(0x1fffffffULL);
    r[1] = v56;
    const V v57 = v55 >> 29;
    const V v58 = v52 << 8;
    const V v59 = v57 + v58;
    const V v60 = VMUL(v1, v3);
    const V v61 = v60 + v60;
    const V v62 = VMUL(v2, v2);
    const V v63 = v61 + v62;
    const V v64 = v59 + v63;
    const V v65 = VMUL(v4, v9);
    const V v66 = VMUL(v5, v8);
    const V v67 = VMUL(v6, v7);
    const V v68 = v65 + v67;
    const V v69 = v68 + v66;
    const V v70 = v69 + v69;
    const V v71 = v53 + v70;
    const V v72 = v71 & vs1(0x1fffffffULL);
    const V v73 = v71 >> 29;
    const V v74 = VMUL(v72, vs1(0x7a20ULL));
    const V v75 = v64 + v74;
    const V v76 = v75 & vs1(0x1fffffffULL);
    r[2] = v76;
    const V v77 = v75 >> 29;
    const V v78 = v72 << 8;
    const V v79 = v77 + v78;
    const V v80 = VMUL(v1, v4);
    const V v81 = VMUL(v2, v3);
    const V v82 = v80 + v81;
    const V v83 = v82 + v82;
    const V v84 = v79 + v83;
    const V v85 = VMUL(v5, v9);
    const V v86 = VMUL(v6, v8);
    const V v87 = v85 + v86;
    const V v88 = v87 + v87;
    const V v89 = VMUL(v7, v7);
    const V v90 = v88 + v89;
    const V v91 = v73 + v90;
    const V v92 = v91 & vs1(0x1fffffffULL);
    const V v93 = v91 >> 29;
    const V v94 = VMUL(v92, vs1(0x7a20ULL));
    const V v95 = v84 + v94;
    const V v96 = v95 & vs1(0x1fffffffULL);
    r[3] = v96;
    const V v97 = v95 >> 29;
    const V v98 = v92 << 8;
    const V v99 = v97 + v98;
    const V v100 = VMUL(v1, v5);
    const V v101 = VMUL(v2, v4);
    const V v102 = v100 + v101;
    const V v103 = v102 + v102;
    const V v104 = VMUL(v3, v3);
    const V v105 = v103 + v104;
    const V v106 = v99 + v105;
    const V v107 = VMUL(v6, v9);
    const V v108 = VMUL(v7, v8);
    const V v109 = v107 + v108;
    const V v110 = v109 + v109;
    const V v111 = v93 + v110;
    const V v112 = v111 & vs1(0x1fffffffULL);
    const V v113 = v111 >> 29;
    const V v114 = VMUL(v112, vs1(0x7a20ULL));
    const V v115 = v106 + v114;
    const V v116 = v115 & vs1(0x1fffffffULL);
    r[4] = v116;
    const V v117 = v115 >> 29;
    const V v118 = v112 << 8;
    const V v119 = v117 + v118;
    const V v120 = VMUL(v1, v6);
    const V v121 = VMUL(v2, v5);
    const V v122 = VMUL(v3, v4);
    const V v123 = v120 + v122;
    const V v124 = v123 + v121;
    const V v125 = v124 + v124;
    const V v126 = v119 + v125;
    const V v127 = VMUL(v7, v9);
    const V v128 = v127 + v127;
    const V v129 = VMUL(v8, v8);
    const V v130 = v128 + v129;
    const V v131 = v113 + v130;
    const V v132 = v131 & vs1(0x1fffffffULL);
    const V v133 = v131 >> 29;
    const V v134 = VMUL(v132, vs1(0x7a20ULL));
    const V v135 = v126 + v134;
    const V v136 = v135 & vs1(0x1fffffffULL);
    r[5] = v136;
    const V v137 = v135 >> 29;
    const V v138 = v132 << 8;
    const V v139 = v137 + v138;
    const V v140 = VMUL(v1, v7);
    const V v141 = VMUL(v2, v6);
    const V v142 = VMUL(v3, v5);
    const V v143 = v140 + v142;
    const V v144 = v143 + v141;
    const V v145 = v144 + v144;
    const V v146 = VMUL(v4, v4);
    const V v147 = v145 + v146;
    const V v148 = v139 + v147;
    const V v149 = VMUL(v8, v9);
    const V v150 = v149 + v149;
    const V v151 = v133 + v150;
    const V v152 = v151 & vs1(0x1fffffffULL);
    const V v153 = v151 >> 29;
    const V v154 = VMUL(v152, vs1(0x7a20ULL));
    const V v155 = v148 + v154;
    const V v156 = v155 & vs1(0x1fffffffULL);
    r[6] = v156;
    const V v157 = v155 >> 29;
    const V v158 = v152 << 8;
    const V v159 = v157 + v158;
    const V v160 = VMUL(v1, v8);
    const V v161 = VMUL(v2, v7);
    const V v162 = VMUL(v3, v6);
    const V v163 = v160 + v162;
    const V v164 = VMUL(v4, v5);
    const V v165 = v161 + v164;
    const V v166 = v163 + v165;
    const V v167 = v166 + v166;
    const V v168 = v159 + v167;
    const V v169 = VMUL(v9, v9);
    const V v170 = v153 + v169;
    const V v171 = v170 & vs1(0x1fffffffULL);
    const V v172 = v170 >> 29;
    const V v173 = VMUL(v171, vs1(0x7a20ULL));
    const V v174 = v168 + v173;
    const V v175 = v174 & vs1(0x1fffffffULL);
    r[7] = v175;
    const V v176 = v174 >> 29;
    const V v177 = v171 << 8;
    const V v178 = v176 + v177;
    const V v179 = VMUL(v172, vs1(0x7a20ULL));
    const V v180 = v178 + v179;
    const V v181 = v180 + v20;
    const V v182 = v181 & vs1(0xffffffULL);
    r[8] = v182;
    const V v183 = v181 >> 24;
    const V v184 = VMUL(v183, vs1(0x3d1ULL));
    const V v185 = VMUL(v172, vs1(0x7a2000ULL));
    const V v186 = v184 + v185;
    const V v187 = v186 + r[0];
    const V v188 = v187 & vs1(0x1fffffffULL);
    r[0] = v188;
    const V v189 = v187 >> 29;
    const V v190 = v183 << 3;
    const V v191 = v189 + v190;
    const V v192 = v172 << 16;
    const V v193 = v191 + v192;
    const V v194 = v193 + r[1];
    const V v195 = v194 & vs1(0x1fffffffULL);
    r[1] = v195;
    const V v196 = v194 >> 29;
    const V v197 = v196 + r[2];
    r[2] = v197;
    for (int k = 0; k < 9; k++) rr->n[k] = r[k];
}
#endif
