/* cg_v26asm.h -- generated by gen/gen_v26asm.py; do not edit.
 * AVX2 4-lane secp256k1 field multiply / square, libsecp256k1 10x26 algorithm
 * (field_10x26_impl.h, Copyright (c) 2013 Pieter Wuille, MIT license -- see COPYING-secp256k1). */
/* mul: 318 instructions, sqr: 245 instructions */
#define QCG_V26_MUL_ASM \
    "vmovdqa 0(%[a]), %%ymm0\n\t" \
    "vmovdqa 32(%[a]), %%ymm1\n\t" \
    "vmovdqa 64(%[a]), %%ymm2\n\t" \
    "vmovdqa 96(%[a]), %%ymm3\n\t" \
    "vmovdqa 128(%[a]), %%ymm4\n\t" \
    "vmovdqa 160(%[a]), %%ymm5\n\t" \
    "vmovdqa 192(%[a]), %%ymm6\n\t" \
    "vmovdqa 224(%[a]), %%ymm7\n\t" \
    "vmovdqa 256(%[a]), %%ymm8\n\t" \
    "vmovdqa 288(%[a]), %%ymm9\n\t" \
    "vpmuludq 256(%[b]), %%ymm1, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm0, %%ymm15\n\t" \
    "vpmuludq 0(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 192(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 128(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 160(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 64(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 96(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 0(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vmovdqa %%ymm14, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 288(%[r])\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 256(%[b]), %%ymm2, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm1, %%ymm15\n\t" \
    "vpmuludq 192(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 128(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 160(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 64(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 96(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 32(%[b]), %%ymm9, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 0(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm2, %%ymm15\n\t" \
    "vpmuludq 0(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 32(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 192(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 128(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 160(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 64(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 96(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 32(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm4, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm3, %%ymm15\n\t" \
    "vpmuludq 32(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 64(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 192(%[b]), %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm5, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 0(%[b]), %%ymm2, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 128(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 160(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 96(%[b]), %%ymm9, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 64(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm4, %%ymm15\n\t" \
    "vpmuludq 64(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 96(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 192(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 0(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 32(%[b]), %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 128(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 160(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 96(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm5, %%ymm15\n\t" \
    "vpmuludq 96(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 128(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 192(%[b]), %%ymm8, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm7, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 32(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 64(%[b]), %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 160(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 0(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 128(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm6, %%ymm15\n\t" \
    "vpmuludq 128(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 160(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 192(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 224(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 64(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 96(%[b]), %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 0(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 32(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 160(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm8, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm7, %%ymm15\n\t" \
    "vpmuludq 160(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 192(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 224(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq 96(%[b]), %%ymm3, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 128(%[b]), %%ymm2, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 32(%[b]), %%ymm5, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 64(%[b]), %%ymm4, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 0(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 192(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 288(%[b]), %%ymm8, %%ymm15\n\t" \
    "vpmuludq 192(%[b]), %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 224(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 128(%[b]), %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 160(%[b]), %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 64(%[b]), %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 96(%[b]), %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 0(%[b]), %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 32(%[b]), %%ymm6, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 224(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 288(%[b]), %%ymm9, %%ymm15\n\t" \
    "vpmuludq 224(%[b]), %%ymm1, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 256(%[b]), %%ymm0, %%ymm14\n\t" \
    "vpmuludq 160(%[b]), %%ymm3, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 192(%[b]), %%ymm2, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 96(%[b]), %%ymm5, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 128(%[b]), %%ymm4, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 32(%[b]), %%ymm7, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 64(%[b]), %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq 0(%[b]), %%ymm8, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 256(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 32(%[k]), %%ymm11, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpaddq 288(%[r]), %%ymm10, %%ymm10\n\t" \
    "vpand 64(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 288(%[r])\n\t" \
    "vpsrlq $22, %%ymm10, %%ymm10\n\t" \
    "vpsllq $14, %%ymm11, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 96(%[k]), %%ymm10, %%ymm11\n\t" \
    "vpsrlq $32, %%ymm10, %%ymm12\n\t" \
    "vpmuludq 96(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpsllq $32, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpaddq 0(%[r]), %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 0(%[r])\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpsllq $6, %%ymm10, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpaddq 32(%[r]), %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 32(%[r])\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpaddq 64(%[r]), %%ymm11, %%ymm11\n\t" \
    "vmovdqa %%ymm11, 64(%[r])\n\t" \

#define QCG_V26_SQR_ASM \
    "vmovdqa 0(%[a]), %%ymm0\n\t" \
    "vmovdqa 32(%[a]), %%ymm1\n\t" \
    "vmovdqa 64(%[a]), %%ymm2\n\t" \
    "vmovdqa 96(%[a]), %%ymm3\n\t" \
    "vmovdqa 128(%[a]), %%ymm4\n\t" \
    "vmovdqa 160(%[a]), %%ymm5\n\t" \
    "vmovdqa 192(%[a]), %%ymm6\n\t" \
    "vmovdqa 224(%[a]), %%ymm7\n\t" \
    "vmovdqa 256(%[a]), %%ymm8\n\t" \
    "vmovdqa 288(%[a]), %%ymm9\n\t" \
    "vpmuludq %%ymm9, %%ymm0, %%ymm15\n\t" \
    "vpmuludq %%ymm0, %%ymm0, %%ymm10\n\t" \
    "vpmuludq %%ymm8, %%ymm1, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm7, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm6, %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm5, %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vmovdqa %%ymm15, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 288(%[r])\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm5, %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm9, %%ymm1, %%ymm15\n\t" \
    "vpmuludq %%ymm8, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm7, %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm6, %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 0(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm9, %%ymm2, %%ymm15\n\t" \
    "vpmuludq %%ymm1, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm8, %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm7, %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm6, %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 32(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm6, %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm9, %%ymm3, %%ymm15\n\t" \
    "vpmuludq %%ymm1, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm2, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm8, %%ymm4, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm7, %%ymm5, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 64(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm9, %%ymm4, %%ymm15\n\t" \
    "vpmuludq %%ymm3, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm8, %%ymm5, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm2, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm7, %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 96(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm7, %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm9, %%ymm5, %%ymm15\n\t" \
    "vpmuludq %%ymm2, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm4, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm8, %%ymm6, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm3, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 128(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm9, %%ymm6, %%ymm15\n\t" \
    "vpmuludq %%ymm5, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm8, %%ymm7, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm15, %%ymm15\n\t" \
    "vpmuludq %%ymm4, %%ymm1, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm3, %%ymm2, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 160(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm8, %%ymm8, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm9, %%ymm7, %%ymm15\n\t" \
    "vpmuludq %%ymm3, %%ymm3, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm6, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm5, %%ymm1, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm4, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 192(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm9, %%ymm8, %%ymm15\n\t" \
    "vpmuludq %%ymm7, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm6, %%ymm1, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm5, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm4, %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm15, %%ymm15, %%ymm15\n\t" \
    "vpaddq %%ymm15, %%ymm11, %%ymm11\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 224(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm9, %%ymm9, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpmuludq %%ymm4, %%ymm4, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq %%ymm8, %%ymm0, %%ymm14\n\t" \
    "vpmuludq %%ymm7, %%ymm1, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm6, %%ymm2, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm14, %%ymm14\n\t" \
    "vpmuludq %%ymm5, %%ymm3, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm14, %%ymm14\n\t" \
    "vpaddq %%ymm14, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm13\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpmuludq 32(%[k]), %%ymm13, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpand 0(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 256(%[r])\n\t" \
    "vpsrlq $26, %%ymm10, %%ymm10\n\t" \
    "vpsllq $10, %%ymm13, %%ymm13\n\t" \
    "vpaddq %%ymm13, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 32(%[k]), %%ymm11, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpaddq 288(%[r]), %%ymm10, %%ymm10\n\t" \
    "vpand 64(%[k]), %%ymm10, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 288(%[r])\n\t" \
    "vpsrlq $22, %%ymm10, %%ymm10\n\t" \
    "vpsllq $14, %%ymm11, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm10, %%ymm10\n\t" \
    "vpmuludq 96(%[k]), %%ymm10, %%ymm11\n\t" \
    "vpsrlq $32, %%ymm10, %%ymm12\n\t" \
    "vpmuludq 96(%[k]), %%ymm12, %%ymm12\n\t" \
    "vpsllq $32, %%ymm12, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpaddq 0(%[r]), %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 0(%[r])\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpsllq $6, %%ymm10, %%ymm12\n\t" \
    "vpaddq %%ymm12, %%ymm11, %%ymm11\n\t" \
    "vpaddq 32(%[r]), %%ymm11, %%ymm11\n\t" \
    "vpand 0(%[k]), %%ymm11, %%ymm12\n\t" \
    "vmovdqa %%ymm12, 32(%[r])\n\t" \
    "vpsrlq $26, %%ymm11, %%ymm11\n\t" \
    "vpaddq 64(%[r]), %%ymm11, %%ymm11\n\t" \
    "vmovdqa %%ymm11, 64(%[r])\n\t" \

