// Generated by research/build_native_module.py; do not edit.
#pragma once
// This generated file is excluded from the source hash to avoid a cycle.
#define QSB_NATIVE_BUILD_BYTES {0x15,0xa4,0x15,0xee,0x4f,0x85,0xda,0xe7,0xee,0x10,0x16,0xa1,0x58,0x4b,0x8b,0xb2,0x36,0x27,0x44,0x84,0x25,0x4b,0xf5,0xad,0x37,0x53,0x41,0x30,0x9c,0x4f,0xa7,0xa7}
#define QSB_NATIVE_CUBIN_SHA256 "91a6048ad42f8492d1334ac8e93a9e6a7304d4f56827571e9f5e78e002c84883"
struct NativeManifestSource { const char *name; const char *sha256; };
static const NativeManifestSource native_manifest_sources[] = {
    {"GLVScalar.cuh","eda0e2a50f4f39846d664a1d36df52b94f8ce746bab652e3f5ba620ff671c1b1"},
    {"GPUHash.h","8cf9b303b6f5a09051e433a8bc21e2f3a66631e3bd22b2b1a10e71fe0b21b2bc"},
    {"GPUMath.h","a5fe65bcd5e75f3963378b5a66c8610527bdfe5be27b7f21ae5b68b0ead10eda"},
    {"LeafRecovery.cuh","92c86c563f21072b5f0b66ca2746b8e4927a9a6dcd27c9fccf7537a32aa05e7d"},
    {"NativeModule.h","fa675fd57572dc5f95e1b344f14fddb046e52dc6ed640566875337b54ca2c984"},
    {"PackedRecovery.cuh","47e16d8a2e3e6d193bd864c681ef8a9af8743332b01beb5ae29e9bb946c34afe"},
    {"ParityWindow.cuh","46d75063be4a1e9ae84c4b1c520fa688d870ad66d4be659be9071eb384be5ca4"},
    {"PriorityPipeline.h","35bcd42ff2bce56f044eab04147a6d80356b29074a484a4f9acdb4ea4499215f"},
    {"RecoveryConstant.h","6f6c0347ab0bb4abca13b2cdbb9294a997c9b3c6a076fd7ed7493e531ac0e369"},
    {"SlotReadback.h","1a3e4699d37aa5beeaa8be8a86da3e16aa5f21183e51781eff19fff279282b25"},
    {"cofactor_checkpoint.h","d41d3507e86c85b11bda88c466b1cda08efcf29ae2baf581e06933ba34279c55"},
    {"negative_y_mac.cuh","1342368c46fa2d8523f9b03c8ce9ae83c78438072866ca76d00696c6742175d3"},
    {"pinning.cu","3ce5ef7b5dc0fcfbe86db246226302379f2cd8ffa6e17097be5a22c1e9d2c838"},
    {"sha_pinsha.cuh","bd811f32f3560fe5fd694f4afd4990c3da451819dd486579d74695cb85ed5462"},
    {"sha_schedule_interleaved.cuh","629417bb86ff908078b8f1358a2b2773b44f02f1c88c3bce9f61a622e24b403f"},
};
static bool qsb_native_generated_config_match() {
#ifndef GT_CHUNKS
    return false;
#else
    if((GT_CHUNKS) != ((6))) return false;
#endif
#ifndef GT_GLV_TERMS
    return false;
#else
    if((GT_GLV_TERMS) != ((12))) return false;
#endif
#ifndef GT_HI
    return false;
#else
    if((GT_HI) != (((1u << 14)))) return false;
#endif
#ifndef GT_LO
    return false;
#else
    if((GT_LO) != (((1u << 14)))) return false;
#endif
#ifdef GT_ORDER_N
    return false;
#endif
#ifndef GT_TOTAL_ENTRIES
    return false;
#else
    if((GT_TOTAL_ENTRIES) != ((153175181u))) return false;
#endif
#ifndef QSB_BATCH
    return false;
#else
    if((QSB_BATCH) != ((8388608))) return false;
#endif
#ifndef QSB_BIGTBL
    return false;
#else
    if((QSB_BIGTBL) != ((1))) return false;
#endif
#ifdef QSB_BIGTBL_HOST_EXACT
    return false;
#endif
#ifndef QSB_C31
    return false;
#else
    if((QSB_C31) != ((1))) return false;
#endif
#ifndef QSB_CAND_STRIDE
    return false;
#else
    if((QSB_CAND_STRIDE) != (((128)))) return false;
#endif
#ifndef QSB_CARRY62
    return false;
#else
    if((QSB_CARRY62) != ((1))) return false;
#endif
#ifndef QSB_CHECKPOINT_NODES
    return false;
#else
    if((QSB_CHECKPOINT_NODES) != ((254))) return false;
#endif
#ifndef QSB_CHECKPOINT_STRIDE
    return false;
#else
    if((QSB_CHECKPOINT_STRIDE) != ((256))) return false;
#endif
#ifndef QSB_COMPACT_READBACK
    return false;
#else
    if((QSB_COMPACT_READBACK) != ((1))) return false;
#endif
#ifndef QSB_COMPLETION_MODE
    return false;
#else
    if((QSB_COMPLETION_MODE) != ((1))) return false;
#endif
#ifndef QSB_DIRECT_DIGITS
    return false;
#else
    if((QSB_DIRECT_DIGITS) != ((1))) return false;
#endif
#ifndef QSB_EARLY_LOAD
    return false;
#else
    if((QSB_EARLY_LOAD) != ((0))) return false;
#endif
#ifndef QSB_FIELD_SC
    return false;
#else
    if((QSB_FIELD_SC) != ((1))) return false;
#endif
#ifndef QSB_FINAL_TEMPLATE
    return false;
#else
    if((QSB_FINAL_TEMPLATE) != ((1))) return false;
#endif
#ifndef QSB_FIN_RAWS
    return false;
#else
    if((QSB_FIN_RAWS) != ((1))) return false;
#endif
#ifndef QSB_FOUR_HOT
    return false;
#else
    if((QSB_FOUR_HOT) != ((1))) return false;
#endif
#ifndef QSB_FUSE_SQRADDSUB2
    return false;
#else
    if((QSB_FUSE_SQRADDSUB2) != ((1))) return false;
#endif
#ifndef QSB_GLV_COEFF_BOUNDS
    return false;
#else
    if((QSB_GLV_COEFF_BOUNDS) != ((1))) return false;
#endif
#ifndef QSB_GLV_COLD_SEED
    return false;
#else
    if((QSB_GLV_COLD_SEED) != ((0))) return false;
#endif
#ifdef QSB_GLV_DENSE_FIRST
    return false;
#endif
#ifndef QSB_GLV_HIGH15
    return false;
#else
    if((QSB_GLV_HIGH15) != ((1))) return false;
#endif
#ifndef QSB_GLV_RESIDUAL129
    return false;
#else
    if((QSB_GLV_RESIDUAL129) != ((1))) return false;
#endif
#ifndef QSB_GLV_RESIDUAL3
    return false;
#else
    if((QSB_GLV_RESIDUAL3) != ((1))) return false;
#endif
#ifndef QSB_GLV_SEED_REG
    return false;
#else
    if((QSB_GLV_SEED_REG) != ((1))) return false;
#endif
#ifndef QSB_GT_RADIX_BITS
    return false;
#else
    if((QSB_GT_RADIX_BITS) != ((14))) return false;
#endif
#ifndef QSB_GT_SPARSE_CHECK
    return false;
#else
    if((QSB_GT_SPARSE_CHECK) != ((1))) return false;
#endif
#ifndef QSB_GT_TOP_CENTER
    return false;
#else
    if((QSB_GT_TOP_CENTER) != ((170559769u))) return false;
#endif
#ifndef QSB_GT_TOP_SHIFT
    return false;
#else
    if((QSB_GT_TOP_SHIFT) != ((100u))) return false;
#endif
#ifndef QSB_GT_TOTAL
    return false;
#else
    if((QSB_GT_TOTAL) != ((153175181u))) return false;
#endif
#ifndef QSB_HOST_GATE
    return false;
#else
    if((QSB_HOST_GATE) != ((1))) return false;
#endif
#ifndef QSB_HOST_READBACK
    return false;
#else
    if((QSB_HOST_READBACK) != ((0))) return false;
#endif
#ifndef QSB_ISO_XR
    return false;
#else
    if((QSB_ISO_XR) != ((1))) return false;
#endif
#ifndef QSB_IV0
    return false;
#else
    if((QSB_IV0) != ((0x6a09e667u))) return false;
#endif
#ifndef QSB_IV1
    return false;
#else
    if((QSB_IV1) != ((0xbb67ae85u))) return false;
#endif
#ifndef QSB_IV2
    return false;
#else
    if((QSB_IV2) != ((0x3c6ef372u))) return false;
#endif
#ifndef QSB_IV3
    return false;
#else
    if((QSB_IV3) != ((0xa54ff53au))) return false;
#endif
#ifndef QSB_IV4
    return false;
#else
    if((QSB_IV4) != ((0x510e527fu))) return false;
#endif
#ifndef QSB_IV5
    return false;
#else
    if((QSB_IV5) != ((0x9b05688cu))) return false;
#endif
#ifndef QSB_IV6
    return false;
#else
    if((QSB_IV6) != ((0x1f83d9abu))) return false;
#endif
#ifndef QSB_IV7
    return false;
#else
    if((QSB_IV7) != ((0x5be0cd19u))) return false;
#endif
#ifdef QSB_K32_
    return false;
#endif
#ifndef QSB_K32_ADD
    return false;
#else
    if((QSB_K32_ADD) != ((1))) return false;
#endif
#ifndef QSB_K32_OFF
    return false;
#else
    if((QSB_K32_OFF) != ((1))) return false;
#endif
#ifndef QSB_K32_SUB
    return false;
#else
    if((QSB_K32_SUB) != ((1))) return false;
#endif
#ifndef QSB_L2_SKIP
    return false;
#else
    if((QSB_L2_SKIP) != ((1))) return false;
#endif
#ifndef QSB_LAZY
    return false;
#else
    if((QSB_LAZY) != ((1))) return false;
#endif
#ifndef QSB_LAZY_REC
    return false;
#else
    if((QSB_LAZY_REC) != ((1))) return false;
#endif
#ifndef QSB_MAC_HALF_SEED
    return false;
#else
    if((QSB_MAC_HALF_SEED) != ((0))) return false;
#endif
#ifndef QSB_MUL_FOLD8_CUT
    return false;
#else
    if((QSB_MUL_FOLD8_CUT) != ((1))) return false;
#endif
#ifndef QSB_MUL_SFZ_PACK
    return false;
#else
    if((QSB_MUL_SFZ_PACK) != ((1))) return false;
#endif
#ifdef QSB_MW
    return false;
#endif
#ifndef QSB_NEG_Y_MAC
    return false;
#else
    if((QSB_NEG_Y_MAC) != ((1))) return false;
#endif
#ifndef QSB_OVERLAP_SEQUENCES
    return false;
#else
    if((QSB_OVERLAP_SEQUENCES) != ((1))) return false;
#endif
#ifndef QSB_PARITY_SUM
    return false;
#else
    if((QSB_PARITY_SUM) != ((1))) return false;
#endif
#ifndef QSB_PARITY_WINDOW
    return false;
#else
    if((QSB_PARITY_WINDOW) != ((1))) return false;
#endif
#ifndef QSB_PARITY_WINDOW_NARROW
    return false;
#else
    if((QSB_PARITY_WINDOW_NARROW) != ((1))) return false;
#endif
#ifndef QSB_PK_UNROLL
    return false;
#else
    if((QSB_PK_UNROLL) != ((1))) return false;
#endif
#ifndef QSB_PREFETCH
    return false;
#else
    if((QSB_PREFETCH) != ((0))) return false;
#endif
#ifndef QSB_PROBE_MASK
    return false;
#else
    if((QSB_PROBE_MASK) != ((0))) return false;
#endif
#ifndef QSB_RAW_DEN
    return false;
#else
    if((QSB_RAW_DEN) != ((1))) return false;
#endif
#ifndef QSB_RAW_X
    return false;
#else
    if((QSB_RAW_X) != ((0))) return false;
#endif
#ifndef QSB_RECOVERY_N
    return false;
#else
    if((QSB_RECOVERY_N) != ((128))) return false;
#endif
#ifndef QSB_REFILL_BEFORE_GATE
    return false;
#else
    if((QSB_REFILL_BEFORE_GATE) != ((1))) return false;
#endif
#ifndef QSB_RESTORE_SQR_F8
    return false;
#else
    if((QSB_RESTORE_SQR_F8) != ((1))) return false;
#endif
#ifndef QSB_RESUB_0920120629
    return false;
#else
    if((QSB_RESUB_0920120629) != ((1))) return false;
#endif
#ifndef QSB_ROOT_V2
    return false;
#else
    if((QSB_ROOT_V2) != ((1))) return false;
#endif
#ifdef QSB_RP_SQR
    return false;
#endif
#ifndef QSB_S0_BLOCKS
    return false;
#else
    if((QSB_S0_BLOCKS) != (((512/128)))) return false;
#endif
#ifndef QSB_S0_SHM
    return false;
#else
    if((QSB_S0_SHM) != ((0))) return false;
#endif
#ifndef QSB_S0_THREADS
    return false;
#else
    if((QSB_S0_THREADS) != ((128))) return false;
#endif
#ifndef QSB_S2_BLOCKS
    return false;
#else
    if((QSB_S2_BLOCKS) != ((7))) return false;
#endif
#ifndef QSB_S2_THREADS
    return false;
#else
    if((QSB_S2_THREADS) != ((128))) return false;
#endif
#ifndef QSB_SAS_FRMOV
    return false;
#else
    if((QSB_SAS_FRMOV) != ((1))) return false;
#endif
#ifndef QSB_SAS_SPLIT3P
    return false;
#else
    if((QSB_SAS_SPLIT3P) != ((1))) return false;
#endif
#ifndef QSB_SAS_Z9SUB_ALL
    return false;
#else
    if((QSB_SAS_Z9SUB_ALL) != ((1))) return false;
#endif
#ifndef QSB_SEED_MUL_CUT
    return false;
#else
    if((QSB_SEED_MUL_CUT) != ((1))) return false;
#endif
#ifndef QSB_SHA_ALU_ADD
    return false;
#else
    if((QSB_SHA_ALU_ADD) != ((0))) return false;
#endif
#ifndef QSB_SHA_FMA_ADD
    return false;
#else
    if((QSB_SHA_FMA_ADD) != ((1))) return false;
#endif
#ifndef QSB_SHA_FMA_ROT
    return false;
#else
    if((QSB_SHA_FMA_ROT) != ((0))) return false;
#endif
#ifndef QSB_SHA_OPT
    return false;
#else
    if((QSB_SHA_OPT) != ((1))) return false;
#endif
#ifndef QSB_SHA_SMEM_W1
    return false;
#else
    if((QSB_SHA_SMEM_W1) != ((0))) return false;
#endif
#ifndef QSB_SHA_UNIF
    return false;
#else
    if((QSB_SHA_UNIF) != ((1))) return false;
#endif
#ifndef QSB_SHORT_CARRY
    return false;
#else
    if((QSB_SHORT_CARRY) != ((1))) return false;
#endif
#ifndef QSB_SKIP_UNUSED_MIDSTATE
    return false;
#else
    if((QSB_SKIP_UNUSED_MIDSTATE) != ((1))) return false;
#endif
#ifndef QSB_SLOTPIPE
    return false;
#else
    if((QSB_SLOTPIPE) != ((1))) return false;
#endif
#ifndef QSB_SLOTS
    return false;
#else
    if((QSB_SLOTS) != ((2))) return false;
#endif
#ifndef QSB_SPARSE_D
    return false;
#else
    if((QSB_SPARSE_D) != ((1))) return false;
#endif
#ifndef QSB_SPARSE_TAIL
    return false;
#else
    if((QSB_SPARSE_TAIL) != ((1))) return false;
#endif
#ifndef QSB_SQR_FOLD8_CUT
    return false;
#else
    if((QSB_SQR_FOLD8_CUT) != ((1))) return false;
#endif
#ifndef QSB_SQR_ROW
    return false;
#else
    if((QSB_SQR_ROW) != ((1))) return false;
#endif
#ifndef QSB_STATE_PLANES
    return false;
#else
    if((QSB_STATE_PLANES) != ((4u))) return false;
#endif
#ifndef QSB_STREAM
    return false;
#else
    if((QSB_STREAM) != ((1))) return false;
#endif
#ifndef QSB_STREAM2
    return false;
#else
    if((QSB_STREAM2) != ((1))) return false;
#endif
#ifndef QSB_SYM_FINISH
    return false;
#else
    if((QSB_SYM_FINISH) != ((1))) return false;
#endif
#ifndef QSB_TAIL_PRE
    return false;
#else
    if((QSB_TAIL_PRE) != ((1))) return false;
#endif
#ifndef QSB_TAIL_TAB
    return false;
#else
    if((QSB_TAIL_TAB) != ((0))) return false;
#endif
#ifndef QSB_TOP16
    return false;
#else
    if((QSB_TOP16) != ((1))) return false;
#endif
#ifndef QSB_TOP16_SC
    return false;
#else
    if((QSB_TOP16_SC) != ((1))) return false;
#endif
#ifndef QSB_TREE_BLOCKS
    return false;
#else
    if((QSB_TREE_BLOCKS) != ((4))) return false;
#endif
#ifndef QSB_TREE_N
    return false;
#else
    if((QSB_TREE_N) != ((128))) return false;
#endif
#ifndef QSB_TREE_OFFLOAD
    return false;
#else
    if((QSB_TREE_OFFLOAD) != ((0))) return false;
#endif
#ifndef QSB_TREE_OFFLOAD2
    return false;
#else
    if((QSB_TREE_OFFLOAD2) != ((0))) return false;
#endif
#ifndef QSB_TREE_TOP2
    return false;
#else
    if((QSB_TREE_TOP2) != ((1))) return false;
#endif
#ifndef QSB_UNROLL
    return false;
#else
    if((QSB_UNROLL) != ((1))) return false;
#endif
#ifndef QSB_X3_TAIL
    return false;
#else
    if((QSB_X3_TAIL) != ((1))) return false;
#endif
#ifndef QSB_XY_DIRECT
    return false;
#else
    if((QSB_XY_DIRECT) != ((1))) return false;
#endif
#ifndef QSB_YOFF
    return false;
#else
    if((QSB_YOFF) != ((1))) return false;
#endif
#ifndef QSB_Z
    return false;
#else
    if((QSB_Z) != ((0u))) return false;
#endif
#ifndef QSB_ZEROS_N
    return false;
#else
    if((QSB_ZEROS_N) != ((24))) return false;
#endif
    return sizeof(void*)==8 && sizeof(int)==4;
}
#define QSB_NATIVE_CONFIG_MATCH qsb_native_generated_config_match()
