#!/usr/bin/env bash
# Regenerate qsb_carrier_sm89.h, the native image that QsbCarrier.h loads.
# Development tool; the ranked harness never runs it. Rerun after ANY edit to
# subset.cu or a header it includes, with the same CUDA toolkit as the runner
# (CUDA 12.8).   ./build_carrier.sh [QSB_ZEROS_N] [GENCODE...]
#
# Default target is sm_89 (the ranked RTX 4090). For local diagnostics on an
# sm_86 card pass the two-target form, which changes only the file's target
# list, never the source:
#   ./build_carrier.sh 24 "-gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89"
set -euo pipefail
cd "$(dirname "$0")"
Z=${1:-24}
ARCH=${2:--gencode arch=compute_89,code=sm_89}
NVCC=${NVCC:-nvcc}
W=$(mktemp -d)   # logs and the raw image stay out of the candidate directory
"$NVCC" -O3 -DQSB_ZEROS_N="$Z" -DQSB_CARRIER_BUILD=1 $ARCH \
        -fatbin -Xptxas -v -o "$W/c.fatbin" subset.cu 2> "$W/ptxas.log"
cuobjdump -symbols "$W/c.fatbin" > "$W/symbols.txt"
cuobjdump -sass "$W/c.fatbin" > "$W/sass.txt"
python3 - "$Z" "$W" "$ARCH" <<'PY'
import base64, hashlib, re, sys
zeros = int(sys.argv[1]); W = sys.argv[2]; arch = sys.argv[3]
syms = open(W + "/symbols.txt").read()
# order must match enum QsbCarrierKernel in QsbCarrier.h
want = [
    ("QK_DIGEST",  r"_Z13kernel_digest\w+"),
    ("QK_BUILD",   r"_Z19kernel_build_gtable\w+"),
    ("QK_EPGRP",   r"_Z19kernel_epoch_groups\w+"),
    ("QK_BEPOCH",  r"_Z23kernel_build_epochs_inc\w+"),
    ("QK_BELEAF",  r"_Z19kernel_build_epochs\w+"),
    ("QK_BFIRST",  r"_Z23kernel_build_first_flat\w+"),
    ("QK_VERIFY",  r"_Z23kernel_verify_pair_hits\w+"),
]
names = []
for kid, pat in want:
    hits = sorted(set(re.findall(pat, syms)))
    if len(hits) != 1:
        sys.exit(f"build_carrier: {kid} matched {hits}")
    names.append(hits[0])
# Every global the digest kernel reads, plus every global the host uploads so a
# kernel launched from either image sees identical state.
for g in ("qsb_carrier_zeros", "QSB_PUSH_WORDS", "QSB_CONST_SCHEDULE", "WIN3",
          "QSB_U2R", "QSB_U2R_C", "BINOM_C", "K",
          "QSB_FIRST_COUNT", "QSB_FIRST_CLASS", "QSB_FIRST_UNIQUE",
          "QSB_WINDOW_CLASS", "QSB_WINDOW_FIRST", "QSB_WINDOW_SECOND"):
    if not re.search(r"\b%s\b" % g, syms):
        sys.exit(f"build_carrier: global {g} missing from image")
sass = open(W + "/sass.txt").read()
blocks = re.split(r"\n\s*Function : ", sass)
d = [b for b in blocks if b.startswith(names[0])]
if not d:
    sys.exit("build_carrier: digest kernel not found in the disassembly")
if not all("LTC64B" in b for b in d):
    sys.exit("build_carrier: a digest-kernel target has no LDG.E.LTC64B load")
n_hint = min(b.count("LTC64B") for b in d)
img = open(W + "/c.fatbin", "rb").read()
b64 = base64.b64encode(img).decode()
lines = [b64[i:i + 120] for i in range(0, len(b64), 120)]
sha = hashlib.sha256(img).hexdigest()
with open("qsb_carrier_sm89.h", "w") as f:
    f.write("/* GENERATED by build_carrier.sh -- do not edit. Native image of subset.cu\n")
    f.write(f" * built with -DQSB_CARRIER_BUILD=1 -DQSB_ZEROS_N={zeros} {arch}.\n")
    f.write(f" * image sha256 {sha}; {len(img)} bytes; digest kernel LTC64B loads: {n_hint}. */\n")
    f.write("#pragma once\n#include <stddef.h>\n")
    f.write(f"static const size_t qsb_carrier_cubin_bytes = {len(img)};\n")
    f.write(f'static const char qsb_carrier_cubin_sha256[] = "{sha}";\n')
    f.write("static const char *const qsb_carrier_kernel_names[] = {\n")
    for kid, n in zip([k for k, _ in want], names):
        f.write(f'    "{n}", /* {kid} */\n')
    f.write("};\n")
    f.write(f"static const unsigned qsb_carrier_b64_lines = {len(lines)};\n")
    f.write("static const char *const qsb_carrier_b64[] = {\n")
    for l in lines:
        f.write(f'"{l}",\n')
    f.write("};\n")
print(f"qsb_carrier_sm89.h: {len(img)} B image, sha256 {sha[:16]}, {len(lines)} lines, LTC64B loads in digest: {n_hint}")
PY
echo "build logs: $W"
