#!/usr/bin/env python3
"""Host audit of actual source, not CUDA execution or a throughput test.

CPU threads emulate block/warp barriers and shuffles; OpenSSL replaces field
primitives. Epoch producer, scheduled SHA consumer and signed recoder execute
against independent Python references. SHA uses the header's C sigma fallback.
"""
import argparse
import ctypes as CT
import hashlib
import itertools
import json
import math
import os
from pathlib import Path
import random
import shlex
import struct
import subprocess
import sys
import tempfile

HERE=Path(__file__).resolve().parent
# Keep generated bytecode out of the directory Yukon packages for submission.
sys.dont_write_bytecode=True
from preflight import source_identity
sys.path.insert(0,str(HERE.parents[1]/"harness"))
import crypto as C
import gen_problem as GEN
import problem as PB


def function(text,signature):
    start=text.index(signature);end=text.index("{",start)+1;depth=1
    while depth:
        depth+=(text[end]=="{")-(text[end]=="}");end+=1
    return text[start:end]


BACKEND=r'''
#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <openssl/bn.h>
#define __device__
#define __constant__
#define __global__
#define __forceinline__ inline
#define __shared__ static
static void require(bool ok){if(!ok){fprintf(stderr,"audit failure\n");abort();}}
struct Dim{int x;};
static thread_local Dim threadIdx,blockIdx,blockDim;
static thread_local int block_syncs;
struct Barrier{
    std::mutex m;std::condition_variable cv;int remaining,total,generation=0;
    explicit Barrier(int n):remaining(n),total(n){}
    void wait(){
        std::unique_lock<std::mutex> lock(m);int g=generation;
        if(--remaining==0){remaining=total;generation++;cv.notify_all();}
        else cv.wait(lock,[&]{return generation!=g;});
    }
};
static Barrier *block_barrier,*warp_barriers[8];
static uint64_t shuffle_values[8][32];
static void __syncthreads(){block_syncs++;block_barrier->wait();}
static unsigned long long __shfl_sync(unsigned mask,unsigned long long v,int src){
    require(mask==0xffffffffu && src>=0 && src<32);
    int warp=threadIdx.x/32,lane=threadIdx.x%32;
    shuffle_values[warp][lane]=v;warp_barriers[warp]->wait();
    uint64_t out=shuffle_values[warp][src];warp_barriers[warp]->wait();return out;
}
template<class F> static void launch(int n,F fn){
    block_barrier=new Barrier(n);
    for(int i=0;i<n/32;i++)warp_barriers[i]=new Barrier(32);
    std::vector<std::thread> threads;
    for(int i=0;i<n;i++)threads.emplace_back([&,i]{
        threadIdx.x=i;blockIdx.x=0;blockDim.x=n;block_syncs=0;fn(i);
    });
    for(auto &t:threads)t.join();
    delete block_barrier;
    for(int i=0;i<n/32;i++)delete warp_barriers[i];
}
struct Field{
    BN_CTX *ctx=BN_CTX_new();BIGNUM *p=nullptr;
    Field(){BN_hex2bn(&p,"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F");}
    ~Field(){BN_free(p);BN_CTX_free(ctx);}
};
static thread_local Field field;
static std::atomic<int> multiply_count{0},inverse_count{0};
static void qsb_field_mul(uint64_t *r,uint64_t *a,uint64_t *b){
    multiply_count++;
    BIGNUM *aa=BN_lebin2bn((uint8_t*)a,32,nullptr),*bb=BN_lebin2bn((uint8_t*)b,32,nullptr),*rr=BN_new();
    require(BN_mod_mul(rr,aa,bb,field.p,field.ctx));
    require(BN_bn2lebinpad(rr,(uint8_t*)r,32)==32);r[4]=0;
    BN_free(aa);BN_free(bb);BN_free(rr);
}
static void _ModInv(uint64_t *r){
    inverse_count++;BIGNUM *a=BN_lebin2bn((uint8_t*)r,32,nullptr);
    BIGNUM *b=BN_mod_inverse(nullptr,a,field.p,field.ctx);require(b!=nullptr);
    require(BN_bn2lebinpad(b,(uint8_t*)r,32)==32);r[4]=0;BN_free(a);BN_free(b);
}
static uint32_t __byte_perm(uint32_t a,uint32_t b,unsigned select){
    uint64_t both=(uint64_t)a|((uint64_t)b<<32);uint32_t out=0;
    for(int i=0;i<4;i++){
        unsigned s=(select>>(4*i))&15,byte=(both>>(8*(s&7)))&255;
        if(s&8)byte=(byte&128)?255:0;
        out|=byte<<(8*i);
    }return out;
}
constexpr int cudaSuccess=0;
template<class T> int cudaMemcpyToSymbol(T &dst,const void *src,size_t n){
    require(n<=sizeof(dst));memcpy(&dst,src,n);return cudaSuccess;
}
template<class T> int cudaMemcpyFromSymbol(void *dst,const T &src,size_t n){
    require(n<=sizeof(src));memcpy(dst,&src,n);return cudaSuccess;
}
'''

WRAPPERS=r'''
extern "C" void check_inverse(const uint64_t *inputs,uint64_t *out,int n,int *counts){
    multiply_count=0;inverse_count=0;std::vector<int> barriers(n);
    launch(n,[&](int i){
        uint64_t value[5];memcpy(value,inputs+5*i,40);
        qsb_block_inverse_tree(value);memcpy(out+5*i,value,40);barriers[i]=block_syncs;
    });
    for(int i=1;i<n;i++)require(barriers[i]==barriers[0]);
    counts[0]=multiply_count;counts[1]=inverse_count;counts[2]=barriers[0];
}
extern "C" void init_hash(const uint8_t *rows,const uint8_t *windows,const uint32_t *constant){
    require(qsb_prepare_constant_schedule(constant,69)==0);
    require(qsb_prepare_window_schedule(rows,(const uint8_t (*)[3])windows,constant)==0);
    memset(BINOM_C,0,sizeof(BINOM_C));
    for(int n=0;n<=150;n++)for(int k=0;k<=9;k++){
        if(k==0||k==n)BINOM_C[n][k]=1;
        else if(k<n)BINOM_C[n][k]=BINOM_C[n-1][k]+BINOM_C[n-1][k-1];
    }
}
extern "C" void epoch_hash(uint64_t rank,uint64_t total,const uint32_t *mid,
        const uint8_t *pre,int prelen,const uint8_t *rows,uint32_t *out,uint8_t *skips){
    epoch_desc_t epoch;threadIdx.x=blockIdx.x=0;blockDim.x=1;
    kernel_build_epochs(rank,total,137,6,mid,pre,prelen,rows,&epoch);
    memcpy(skips,epoch.early,6);
    launch(256,[&](int lane){
        uint32_t state[8];qsb_scheduled_window_hash(state,&epoch,lane);
        uint32_t b2[16]={},s2[8];
        memcpy(b2,state,32);b2[8]=0x80000000u;b2[15]=256;
        _SHA256Initialize(s2);_SHA256Transform(s2,b2);memcpy(out+8*lane,s2,32);
    });
}
extern "C" void recode(const uint64_t *k,int32_t *digits){gt_recode_signed(k,digits);}
extern "C" void unrank(uint64_t rank,int n,int t,uint8_t *out){unrank_combo(rank,n,t,out);}
'''


def build_source():
    s=(HERE/"tests/gpu_epochs/tree.cu").read_text()
    sha=(HERE/"GPUHash.h").read_text().split("//Modified SHA256 function")[0]
    shape=s[s.index("#define QSB_SE_N_INC"):s.index("/* The first 256 lexicographic")]
    recode=s[s.index("__device__ __constant__ uint64_t GT_ORDER_N"):s.index("/* Load table point")]
    headers="\n".join(["#define MAX_T 16\n#define SIG_PUSH_SIZE 10",
        "uint64_t BINOM_C[151][10];\nuint32_t QSB_CONST_SCHEDULE[4][64];",shape,recode])
    return "\n".join([BACKEND,sha,headers,
        function(s,"static uint32_t qsb_host_rotr("),
        function(s,"static int qsb_prepare_constant_schedule("),
        function(s,"__device__ __forceinline__ void qsb_compress_constant_rolled("),
        (HERE/"tests/gpu_epochs/window_schedule_shared.cuh").read_text(),
        function(s,"__device__ __forceinline__ void unrank_combo("),
        function(s,"__global__ void kernel_build_epochs("),
        (HERE/"tests/gpu_epochs/tree_inverse.cuh").read_text(),WRAPPERS])


U8,U32,U64,I32=CT.c_uint8,CT.c_uint32,CT.c_uint64,CT.c_int32
P8,P32,P64,PI32=CT.POINTER(U8),CT.POINTER(U32),CT.POINTER(U64),CT.POINTER(I32)


def buf(data):return (U8*len(data)).from_buffer_copy(data)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report",type=Path,help="write the final machine-readable JSON report")
    args=parser.parse_args()
    identity=source_identity();flags=[]
    prefix=os.environ.get("OPENSSL_PREFIX")
    if not prefix and Path("/opt/homebrew/opt/openssl@3").exists():prefix="/opt/homebrew/opt/openssl@3"
    if prefix:flags=[f"-I{prefix}/include",f"-L{prefix}/lib"]
    rng=random.Random(20260916)
    counts={"inverse_values":0,"sha256d":0,"signed_recodings":0,"unranking":0}
    with tempfile.TemporaryDirectory(prefix="qsb-subset-host-audit-") as tmp:
        cpp,shared=Path(tmp)/"check.cpp",Path(tmp)/"check.so";cpp.write_text(build_source())
        subprocess.run(shlex.split(os.environ.get("CXX","c++"))+
            ["-std=c++17","-O2","-shared","-fPIC","-pthread","-Wno-deprecated-declarations",
             *flags,str(cpp),"-lcrypto","-o",str(shared)],check=True)
        lib=CT.CDLL(str(shared))
        lib.check_inverse.argtypes=[P64,P64,CT.c_int,PI32]
        lib.init_hash.argtypes=[P8,P8,P32]
        lib.epoch_hash.argtypes=[U64,U64,P32,P8,CT.c_int,P8,P32,P8]
        lib.recode.argtypes=[P64,PI32];lib.unrank.argtypes=[U64,CT.c_int,CT.c_int,P8]
        p=(1<<256)-(1<<32)-977
        for n in (32,64,128,256):
            for case in range(8):
                active=[n,1,n-1,n//2+1][case%4]
                values=[rng.randrange(1,p) for _ in range(active)]+[1]*(n-active)
                if case==0:values=[1,2,p-1,p-2,(1<<255),p//2,3,17]*(n//8)
                if case==4:values=[1]*n
                raw=[]
                for v in values:raw.extend([(v>>(64*k))&((1<<64)-1) for k in range(4)]+[123])
                inputs,out,ops=(U64*(5*n))(*raw),(U64*(5*n))(),(I32*3)()
                lib.check_inverse(inputs,out,n,ops)
                # Four-lane reduction plus fused shared up/down levels.
                assert tuple(ops)==(3*n-3,1,2*int(math.log2(n))-4),tuple(ops)
                for i,v in enumerate(values):
                    got=sum(out[5*i+k]<<(64*k) for k in range(4))
                    assert got==pow(v,-1,p) and out[5*i+4]==0,(n,case,i)
                    counts["inverse_values"]+=1
            print(f"Inverse source: {n} lanes, 8 blocks, {ops[0]} multiplies / {ops[2]} barriers: PASS",flush=True)
        windows=list(itertools.islice(itertools.combinations(range(137,150),3),256))
        for seed in (20260916,679162400):
            prob,_=GEN.gen_subset(random.Random(seed));prefix_bytes=bytes.fromhex(prob["fixed_prefix"])
            aligned=len(prefix_bytes)//64*64
            mid=(U32*8)(*C.sha256_midstate(prefix_bytes[:aligned]));pre=buf(prefix_bytes[aligned:])
            rows=buf(b"".join(bytes.fromhex(x) for x in prob["dummy_sigs"]))
            suffix=bytes.fromhex(prob["tail_section"]+prob["tx_suffix"])
            constant=suffix+b"\x80"+b"\x00"*5+(prob["total_preimage_len"]*8).to_bytes(8,"big")
            assert len(constant)==276
            lib.init_hash(rows,buf(bytes(itertools.chain.from_iterable(windows))),
                          (U32*69)(*struct.unpack(">69I",constant)))
            total=math.comb(137,6)
            ordinals=[0,1,32767,32768,total-1,total-2]+[rng.randrange(total) for _ in range(6)]
            for ordinal in ordinals:
                output,early=(U32*(256*8))(),(U8*6)()
                lib.epoch_hash(ordinal,total,mid,pre,len(pre),rows,output,early)
                for lane,win in enumerate(windows):
                    skip=list(early)+list(win)
                    assert len(set(skip))==9 and skip==sorted(skip)
                    want=hashlib.sha256(hashlib.sha256(PB.sub_preimage(prob,skip)).digest()).digest()
                    got=struct.pack(">8I",*output[8*lane:8*lane+8])
                    assert got==want,(seed,ordinal,lane)
                    counts["sha256d"]+=1
            print(f"Epoch + window SHA source, seed {seed}: {len(ordinals)*256} digests PASS",flush=True)
        scalars=[0,1,C.N-1,C.N,C.N+1,(1<<256)-1]
        scalars += [1<<i for i in range(256)]+[rng.getrandbits(256) for _ in range(10000)]
        for k in scalars:
            digits=(I32*16)()
            lib.recode((U64*4)(*[(k>>(64*i))&((1<<64)-1) for i in range(4)]),digits)
            assert all((abs(d)&1)==1 and abs(d)<65536 for d in digits)
            assert (sum(int(d)<<(16*i) for i,d in enumerate(digits))*pow(2,-1,C.N)-k)%C.N==0
            counts["signed_recodings"]+=1
        for n in range(1,13):
            for t in range(1,min(n,9)+1):
                for rank,want in enumerate(itertools.combinations(range(n),t)):
                    out=(U8*16)();lib.unrank(rank,n,t,out)
                    assert tuple(out[:t])==want;counts["unranking"]+=1
        assert source_identity()==identity,"Source changed during the audit; rerun on a stable candidate"
        report={"status":"PASS","validation_level":"cpu_reference",**counts,
            "include_closure_files":len(identity["source_sha256"]),**identity,
            "audit_sha256":hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
            "gpu_executed":False,
            "limitations":"CPU synchronization emulation and OpenSSL field primitives; no CUDA compilation, GPU race validation or throughput measurement."}
        encoded=json.dumps(report,indent=2)
        if args.report:args.report.write_text(encoded+"\n")
        print(encoded)


if __name__=="__main__":main()
