#!/usr/bin/env python3
"""mk_b_header.py <in: qsb_carrier_sm89.h from any build_carrier.sh> <out: qsb_carrier_b_sm89.h> [--flags STR]

Development tool (never run by the harness). Turns a native-image header written by build_carrier.sh
into the variant-B header of the in-run A/B (QsbCarrier.h includes it inside namespace qsb_ab_b):
  - drops the system include (nothing system-level may land inside the namespace);
  - appends the image's exact qsb_carrier_knobs string (read from the cubin's ELF symbol table),
    the build flags, and every data global of the image (name, bytes, uploaded-or-not is decided
    at run time), so the loader can verify the image and compare its globals with image A.
The cubin itself is carried unchanged (same base64 lines, same sha256)."""
import base64, hashlib, re, struct, sys


def cstr(s):
    out = []
    for ch in s:
        if ch in '\\"':
            out.append('\\' + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append('\\%03o' % ord(ch))
    return '"' + ''.join(out) + '"'


def elf_objects(img):
    """(name, size, section name, bytes-or-None) for every STT_OBJECT symbol of a 64-bit LE ELF."""
    if img[:4] != b'\x7fELF' or img[4] != 2 or img[5] != 1:
        sys.exit('mk_b_header: image is not a 64-bit little-endian ELF')
    e_shoff, = struct.unpack_from('<Q', img, 0x28)
    e_shentsize, e_shnum, e_shstrndx = struct.unpack_from('<HHH', img, 0x3A)
    secs = []
    for i in range(e_shnum):
        o = e_shoff + i * e_shentsize
        name, typ, flags, addr, off, size, link, info, align, entsize = struct.unpack_from('<IIQQQQIIQQ', img, o)
        secs.append(dict(name=name, type=typ, off=off, size=size, link=link, entsize=entsize))
    shstr = secs[e_shstrndx]

    def sname(idx):
        b = img[shstr['off'] + idx:]
        return b[:b.index(b'\0')].decode()
    for s in secs:
        s['sname'] = sname(s['name'])
    symtab = [s for s in secs if s['type'] == 2]          # SHT_SYMTAB
    if len(symtab) != 1:
        sys.exit('mk_b_header: expected one .symtab')
    st = symtab[0]
    strtab = secs[st['link']]
    objs = []
    for i in range(st['size'] // st['entsize']):
        o = st['off'] + i * st['entsize']
        st_name, st_info, st_other, st_shndx, st_value, st_size = struct.unpack_from('<IBBHQQ', img, o)
        if st_info & 0xF != 1:                               # STT_OBJECT
            continue
        b = img[strtab['off'] + st_name:]
        name = b[:b.index(b'\0')].decode()
        sec = secs[st_shndx] if st_shndx < len(secs) else None
        data = None
        if sec is not None and sec['type'] == 1:              # SHT_PROGBITS: initialized
            data = img[sec['off'] + st_value: sec['off'] + st_value + st_size]
        objs.append((name, st_size, sec['sname'] if sec else '?', data))
    return objs


def main():
    a = sys.argv[1:]
    flags = ''
    if '--flags' in a:
        i = a.index('--flags'); flags = a[i + 1]; del a[i:i + 2]
    if len(a) != 2:
        sys.exit(__doc__)
    src, dst = a
    text = open(src).read()
    m = re.search(r'qsb_carrier_b64\[\] = \{(.*?)\};', text, re.S)
    img = base64.b64decode(''.join(re.findall(r'"([A-Za-z0-9+/=]+)"', m.group(1))), validate=True)
    want_len = int(re.search(r'qsb_carrier_cubin_bytes = (\d+);', text).group(1))
    want_sha = re.search(r'qsb_carrier_cubin_sha256\[\] = "([0-9a-f]{64})"', text).group(1)
    sha = hashlib.sha256(img).hexdigest()
    if len(img) != want_len or sha != want_sha:
        sys.exit('mk_b_header: header does not match its own cubin (%d/%s vs %d/%s)' % (len(img), sha, want_len, want_sha))
    objs = elf_objects(img)
    kn = [o for o in objs if o[0] == 'qsb_carrier_knobs']
    if len(kn) != 1 or kn[0][3] is None or not kn[0][3].endswith(b'\0'):
        sys.exit('mk_b_header: qsb_carrier_knobs missing from the image')
    knobs = kn[0][3][:-1].decode()
    names = sorted({o[0] for o in objs})
    if len(names) != len(objs):
        sys.exit('mk_b_header: duplicate global names in the image')
    body = text.replace('#include <stddef.h>\n', '')
    if '#include' in body:
        sys.exit('mk_b_header: unexpected #include in the input header')
    with open(dst, 'w') as f:
        f.write('/* GENERATED by mk_b_header.py from a build_carrier.sh header -- do not edit.\n')
        f.write(' * Variant-B native image of the in-run A/B (QSB_AB); QsbCarrier.h includes this file\n')
        f.write(' * inside namespace qsb_ab_b. Build flags: %s */\n' % (flags or '(none)'))
        f.write(body)
        f.write('/* ---- A/B metadata (mk_b_header.py) ---- */\n')
        f.write('static const char qsb_carrier_b_flags[] = %s;\n' % cstr(flags))
        f.write('static const char qsb_carrier_b_knobs[] = %s;\n' % cstr(knobs))
        f.write('struct QsbAbGlobal { const char *name; size_t bytes; };\n')
        f.write('static const QsbAbGlobal qsb_carrier_b_globals[] = {\n')
        for name, size, sec, data in sorted(objs):
            f.write('    {%s, %d},  /* %s */\n' % (cstr(name), size, sec))
        f.write('};\n')
        f.write('static const unsigned qsb_carrier_b_n_globals = %d;\n' % len(objs))
    print('mk_b_header: %s -> %s: cubin %d B sha256 %s, %d globals, flags %r' % (src, dst, len(img), sha[:16], len(objs), flags))


if __name__ == '__main__':
    main()
