#!/usr/bin/env bash
# mk_carrier.sh -- local regeneration of qsb_carrier_sm89.h without cuobjdump
# (this dev box has only the nvcc shim; binutils nm reads the cubin's ELF symtab).
# Same output format as build_carrier.sh; the SASS LTC64B check is replaced by a
# PTX ld.global...L2::64B check (nvcc -ptx preserves the hint from the same source).
set -euo pipefail
cd "$(dirname "$0")"
Z=${1:-24}
W=$(mktemp -d)
nvcc --version | tail -n 2 | head -n 1 > "$W/nvcc.txt"
nvcc -O3 -DQSB_ZEROS_N="$Z" -DQSB_CARRIER_BUILD=1 -arch=sm_89 -cubin \
     -Xptxas -v -o "$W/c.cubin" subset.cu 2> "$W/ptxas.log"
nm "$W/c.cubin" | awk '{print $NF, $2}' > "$W/symbols.txt"
nvcc -O3 -DQSB_ZEROS_N="$Z" -DQSB_CARRIER_BUILD=1 -arch=sm_89 -ptx \
     -o "$W/c.ptx" subset.cu 2>/dev/null
python3 - "$Z" "$W" <<'PY'
import base64, glob, hashlib, re, sys
zeros = int(sys.argv[1]); W = sys.argv[2]
syms = open(W + "/symbols.txt").read()
want = [  # order must match enum QsbCarrierKernel in QsbCarrier.h
    ("QK_EG",  r"_Z19kernel_epoch_groups\w+"),
    ("QK_BEI", r"_Z23kernel_build_epochs_inc\w+"),
    ("QK_BFF", r"_Z23kernel_build_first_flat\w+"),
    ("QK_DIG", r"_Z13kernel_digest\w+"),
    ("QK_GT",  r"_Z19kernel_build_gtable\w+"),
    ("QK_HEAL", r"_Z19kernel_gt_heal_scan\w+"),
]
names = []
for kid, pat in want:
    # nm output lines are "ADDR t MANGLED" (local syms) or contain the mangled
    # name inside $_...$ sections; search anywhere in the line, strip decorations.
    hits = set()
    for line in syms.splitlines():
        for m in re.finditer(r"(_Z1[39]kernel_\w+)", line):
            hits.add(m.group(1))
    hits = sorted(h for h in hits if re.fullmatch(pat[:-2] + r"\w*", h))
    if len(hits) != 1:
        # fall back: unique full match on the pattern
        hits = sorted(set(re.findall(pat, syms)))
    if len(hits) != 1:
        sys.exit(f"mk_carrier: {kid} matched {hits}")
    names.append(hits[0])
for g in ("qsb_carrier_knobs", "QSB_CONST_SCHEDULE", "QSB_U2R", "QSB_U2R_ISO", "QSB_ISO_INVU",
          "QSB_ISO_XNEG", "QSB_U2R_C", "QSB_PUSH_WORDS", "BINOM_C", "WIN3", "QSB_WINDOW_FIRST",
          "QSB_WINDOW_SECOND", "QSB_WINDOW_CLASS", "QSB_FIRST_CLASS", "QSB_LANE_CLASS",
          "QSB_FIRST_UNIQUE", "QSB_FIRST_COUNT"):
    if not re.search(r"\b%s\b" % g, syms):
        sys.exit(f"mk_carrier: global {g} missing from image")
ptx = open(W + "/c.ptx").read()
n_hint = len(re.findall(r"ld\.global[^;\n]*L2::64B", ptx))
if n_hint == 0:
    sys.exit("mk_carrier: no L2::64B load in PTX")
img = open(W + "/c.cubin", "rb").read()
b64 = base64.b64encode(img).decode()
lines = [b64[i:i + 120] for i in range(0, len(b64), 120)]
sha = hashlib.sha256(img).hexdigest()
src = hashlib.sha256()
for p in sorted(glob.glob("*.cu") + glob.glob("*.cuh") + glob.glob("*.h") +
                glob.glob("tests/gpu_epochs/*.cuh") + glob.glob("tests/gpu_epochs/*.h") +
                ["tests/gpu_epochs/tree.cu"]):
    if p == "qsb_carrier_sm89.h":
        continue
    src.update(p.encode() + b"\0" + open(p, "rb").read())
tool = open(W + "/nvcc.txt").read().strip()
with open("qsb_carrier_sm89.h", "w") as f:
    f.write("/* GENERATED by build_carrier.sh -- do not edit. Native sm_89 image of subset.cu\n")
    f.write(f" * built with -DQSB_CARRIER_BUILD=1 -DQSB_ZEROS_N={zeros} -arch=sm_89 ({tool}).\n")
    f.write(f" * cubin sha256 {sha}; {len(img)} bytes; digest kernel LTC64B loads: {n_hint}.\n")
    f.write(f" * source sha256 {src.hexdigest()} (every .cu/.cuh/.h of the build but this file). */\n")
    f.write("#pragma once\n#include <stddef.h>\n")
    f.write(f"static const size_t qsb_carrier_cubin_bytes = {len(img)};\n")
    f.write(f'static const char qsb_carrier_cubin_sha256[] = "{sha}";\n')
    f.write("static const char *const qsb_carrier_kernel_names[] = {\n")
    for kid, n in zip([k for k, _ in want], names):
        f.write(f'    "{n}", /* {kid} */\n')
    f.write("};\n")
    f.write(f"static const unsigned qsb_carrier_b64_lines = {len(lines)};\n")
    f.write("static const char *const qsb_carrier_b64[] = {\n")
    for l in lines:
        f.write(f'"{l}",\n')
    f.write("};\n")
print(f"qsb_carrier_sm89.h: {len(img)} B cubin, sha256 {sha[:16]}, {len(lines)} lines, "
      f"L2::64B loads in digest PTX: {n_hint}, {tool}")
PY
grep -A2 "Compiling entry function '_Z13kernel_digest" "$W/ptxas.log" | tail -n 2 || true
echo "build logs: $W"
