// stack arm generated 2026-10-01T13:55:17Z: QSB_TAIL_STAGGER=4 QSB_ROOT_LUT_SMEM=1 QSB_ROOT_WARP=2 QSB_DIVSTEP_LOOKAHEAD=1 QSB_SHA_FMA_ROT=4 QSB_TREE_UNROLL=1
#define QSB_LOCAL_SM86 1
#define QSB_TAIL_STAGGER 4
#define QSB_ROOT_LUT_SMEM 1
#define QSB_ROOT_WARP 2
#define QSB_DIVSTEP_LOOKAHEAD 1
#define QSB_SHA_FMA_ROT 4
#define QSB_TREE_UNROLL 1
#include "subset.cu"
