// Generated by regenerate_native.py; do not edit.
#define QSB_NATIVE_FILE "native_sm89.cubin"
#define QSB_NATIVE_BYTES 451744
static const unsigned char payload_sha256[32] = {0x98,0x79,0xc5,0xc1,0x90,0x34,0xfb,0xd6,0xbc,0x58,0xa2,0x70,0xf1,0x22,0x2e,0x70,0xda,0xdd,0x35,0xf8,0xb9,0x76,0x6b,0x6d,0x25,0x9b,0x8b,0x70,0x16,0x5c,0x33,0x33};
static Kernel kernels[] = {
{"kernel_build_first_flat", "_Z23kernel_build_first_flatPK12epoch_desc_tPjjj", 4, {8,8,4,4}, NULL, false},
{"kernel_epoch_groups", "_Z19kernel_epoch_groupsmjiiPKjPKhiS2_P11qsb_group_tPjmm", 12, {8,4,4,4,8,8,4,8,8,8,8,8}, NULL, false},
{"kernel_build_epochs_inc", "_Z23kernel_build_epochs_incmmiiPKhPK11qsb_group_tmP12epoch_desc_tPjPKj", 10, {8,8,4,4,8,8,8,8,8,8}, NULL, false},
{"kernel_digest", "_Z13kernel_digestPKhiiPKjS0_iS0_S0_iS0_iiPKmS4_S4_S4_S4_PhPjS6_S5_S5_S5_S5_S5_S5_iiiiimiiS0_iS2_PK12epoch_desc_tS2_i", 40, {8,4,4,8,8,4,8,8,4,8,4,4,8,8,8,8,8,8,8,8,8,8,8,8,8,8,4,4,4,4,4,8,4,4,8,4,8,8,8,4}, NULL, false},
{"kernel_build_gtable", "_Z19kernel_build_gtablePKmS0_S0_Ph", 4, {8,8,8,8}, NULL, false},
{"kernel_gt_heal_scan", "_Z19kernel_gt_heal_scanPKhPKmPjj", 4, {8,8,8,4}, NULL, false},
};
static Global globals[] = {
{"K", 256, NULL},
{"QSB_CONST_SCHEDULE", 1024, NULL},
{"QSB_U2R", 64, NULL},
{"QSB_U2R_ISO", 64, NULL},
{"QSB_ISO_INVU", 32, NULL},
{"QSB_ISO_XNEG", 4, NULL},
{"QSB_U2R_C", 32, NULL},
{"QSB_PUSH_WORDS", 2416, NULL},
{"BINOM_C", 12080, NULL},
{"WIN3", 384, NULL},
{"QSB_WINDOW_FIRST", 7168, NULL},
{"QSB_WINDOW_SECOND", 32768, NULL},
{"QSB_WINDOW_CLASS", 512, NULL},
{"QSB_FIRST_CLASS", 512, NULL},
{"QSB_FIRST_UNIQUE", 896, NULL},
{"QSB_FIRST_COUNT", 4, NULL},
};
