// Generated by regenerate_native.py; do not edit.
#define QSB_NATIVE_FILE "native_sm89.cubin"
#define QSB_NATIVE_BYTES 1209952
static const unsigned char payload_sha256[32] = {0x08,0x73,0x9e,0x1c,0x55,0x95,0x6c,0x1c,0x5a,0x86,0x01,0xc5,0x3e,0x01,0xf4,0x8e,0x80,0xc3,0x95,0xb5,0xa2,0xf0,0x9f,0xa8,0x05,0x34,0x56,0x56,0xbb,0xa0,0x0a,0x66};
static Kernel kernels[] = {
{"kernel_build_first_flat", "_Z23kernel_build_first_flatPK12epoch_desc_tPjjj", 4, {8,8,4,4}, NULL, false},
{"kernel_build_epochs", "_Z19kernel_build_epochsmmiiPKjPKhiS2_P12epoch_desc_tPj", 10, {8,8,4,4,8,8,4,8,8,8}, NULL, false},
{"kernel_epoch_groups", "_Z19kernel_epoch_groupsmjiiPKjPKhiS2_P11qsb_group_tPjmm", 12, {8,4,4,4,8,8,4,8,8,8,8,8}, NULL, false},
{"kernel_build_epochs_inc", "_Z23kernel_build_epochs_incmmiiPKhPK11qsb_group_tmP12epoch_desc_tPjPKj", 10, {8,8,4,4,8,8,8,8,8,8}, NULL, false},
{"kernel_verify_pair_hits", "_Z23kernel_verify_pair_hitsPKhPhPK12epoch_desc_tPKjS0_i", 6, {8,8,8,8,8,4}, NULL, false},
{"kernel_digest", "_Z13kernel_digestPKhiiPKjS0_iS0_S0_iS0_iiPKmS4_S4_S4_S4_PhPjS6_S5_S5_S5_S5_S5_S5_iiiiimiiS0_iS2_PK12epoch_desc_tS2_i", 40, {8,4,4,8,8,4,8,8,4,8,4,4,8,8,8,8,8,8,8,8,8,8,8,8,8,8,4,4,4,4,4,8,4,4,8,4,8,8,8,4}, NULL, false},
{"kernel_build_gtable", "_Z19kernel_build_gtablePKmS0_Ph", 3, {8,8,8}, NULL, false},
{"kernel_build_glv10", "_Z18kernel_build_glv10PKmS0_PhmmPKj", 6, {8,8,8,8,8,8}, NULL, false},
{"kernel_build_glv10_batch", "_Z24kernel_build_glv10_batchPKmS0_PhmmPKjPj", 7, {8,8,8,8,8,8,8}, NULL, false},
{"kernel_gather_glv10", "_Z19kernel_gather_glv10PKhPKjPmj", 4, {8,8,8,4}, NULL, false},
{"kernel_audit_glv10", "_Z18kernel_audit_glv10PKhPKmPmPjj", 5, {8,8,8,8,4}, NULL, false},
};
static Global globals[] = {
{"K", 256, NULL},
{"QSB_CONST_SCHEDULE", 1024, NULL},
{"QSB_U2R", 64, NULL},
{"QSB_U2R_C", 32, NULL},
{"QSB_PUSH_WORDS", 2416, NULL},
{"BINOM_C", 12080, NULL},
{"WIN3", 384, NULL},
{"QSB_WINDOW_FIRST", 7168, NULL},
{"QSB_WINDOW_SECOND", 32768, NULL},
{"QSB_WINDOW_CLASS", 512, NULL},
{"QSB_FIRST_CLASS", 512, NULL},
{"QSB_FIRST_UNIQUE", 3584, NULL},
{"QSB_FIRST_COUNT", 4, NULL},
};
