#!/usr/bin/env python3
"""Rebuild the generic N=24/sm89 payload with CUDA 12.8.93 (no GPU needed).

Run from anywhere: python3 /path/to/candidates/subset/regenerate_native.py
Outputs only native_sm89.cubin, native_manifest.cuh and native_manifest.json.
The fixed benchmark command does not need to run this generator.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile
import shutil

ROOT = Path(__file__).resolve().parent

def sha(data):
    return hashlib.sha256(data).hexdigest()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--docker', help='Existing CUDA container with repository mounted at /work')
    parser.add_argument('--artifact-dir', type=Path, help='Preserve PTX, cubin and toolchain for a read-only census')
    parser.add_argument('--docker-workdir', default='/work/candidates/subset', help='Container path of this source copy when using --docker')
    args = parser.parse_args()
    prefix = ['docker', 'exec', '-w', args.docker_workdir, args.docker] if args.docker else []
    nvcc_version = subprocess.check_output(prefix + ['nvcc', '--version'], text=True)
    ptxas_version = subprocess.check_output(prefix + ['ptxas', '--version'], text=True)
    for version in (nvcc_version, ptxas_version):
        if 'V12.8.93' not in version:
            raise SystemExit('Reproducible payload requires CUDA V12.8.93')
    with tempfile.TemporaryDirectory(prefix='.qsb-native-', dir=ROOT) as temp:
        ptx = Path(temp) / 'native.ptx'
        cubin = Path(temp) / 'native.cubin'
        subprocess.run(prefix + ['nvcc', '-O3', '-DQSB_ZEROS_N=24', '-DQSB_NATIVE_MODULE=0',
                        '--ptx', 'subset.cu', '-o', str(ptx.relative_to(ROOT))], cwd=ROOT, check=True)
        subprocess.run(prefix + ['ptxas', '-arch=sm_89', '-O3', str(ptx.relative_to(ROOT)),
                                 '-o', str(cubin.relative_to(ROOT)), '-v'], cwd=ROOT, check=True)
        text = ptx.read_text()
        payload = cubin.read_bytes()
        entries = []
        for symbol, params in re.findall(r'\.visible\s+\.entry\s+(\w+)\s*\(([^)]*)\)', text, re.S):
            types = re.findall(r'\.param\s+\.(u\d+)\s+\w+', params)
            if len(types) != params.count('.param'):
                raise SystemExit('Unsupported PTX parameter type')
            m = re.match(r'_Z(\d+)', symbol)
            name = symbol[m.end():m.end() + int(m[1])]
            entries.append(dict(name=name, symbol=symbol, bytes=[int(t[1:])//8 for t in types]))
        globals_ = []
        for space, align, bits, name, array in re.findall(
            r'^\.(const|global)\s+\.align\s+(\d+)\s+\.([bu]\d+)\s+(\w+)(?:\[(\d+)\])?', text, re.M):
            globals_.append(dict(symbol=name, space=space, alignment=int(align),
                                 bytes=int(bits[1:])//8 * int(array or 1)))
        expected_kernels = {'kernel_build_first_flat', 'kernel_build_epochs', 'kernel_epoch_groups',
                            'kernel_build_epochs_inc', 'kernel_verify_pair_hits', 'kernel_digest',
                            'kernel_build_gtable', 'kernel_build_glv10', 'kernel_build_glv10_batch',
                            'kernel_gather_glv10', 'kernel_audit_glv10'}
        if {e['name'] for e in entries} != expected_kernels or len(globals_) != 20:
            raise SystemExit(f'Unexpected module shape: {len(entries)} kernels, {len(globals_)} globals')
        digest = sha(payload)
        lines = ['// Generated by regenerate_native.py; do not edit.',
                 '#define QSB_NATIVE_FILE "native_sm89.cubin"',
                 f'#define QSB_NATIVE_BYTES {len(payload)}',
                 'static const unsigned char payload_sha256[32] = {' +
                 ','.join('0x'+digest[i:i+2] for i in range(0,64,2)) + '};',
                 'static Kernel kernels[] = {']
        for e in entries:
            lines.append('{"'+e['name']+'", "'+e['symbol']+'", '+str(len(e['bytes']))+
                         ', {'+','.join(map(str,e['bytes']))+'}, NULL, false},')
        host_text = '\n'.join((ROOT / f).read_text() for f in
            ('tests/gpu_epochs/tree.cu', 'tests/gpu_epochs/window_schedule_shared.cuh'))
        used = set(re.findall(r'QSB_TO_SYMBOL\(\s*(\w+)', host_text))
        used.update(re.findall(r'QSB_FROM_SYMBOL\([^,]+,\s*(\w+)', host_text))
        if len(used) != 13 or not used <= {g['symbol'] for g in globals_}:
            raise SystemExit('Unexpected host symbol routing')
        lines += ['};', 'static Global globals[] = {']
        lines += [f'{{"{g["symbol"]}", {g["bytes"]}, NULL}},' for g in globals_ if g['symbol'] in used]
        lines += ['};']
        # Hash the recursive source inputs, excluding generated metadata. The
        # latter is excluded from the device build by QSB_NATIVE_MODULE=0.
        sources = {}
        def visit(path):
            rel = str(path.relative_to(ROOT))
            if rel in sources or path.name == 'native_manifest.cuh':
                return
            data = path.read_bytes()
            sources[rel] = sha(data)
            for inc in re.findall(r'^\s*#include\s+"([^"]+)"', data.decode(), re.M):
                visit((path.parent / inc).resolve())
        visit(ROOT / 'subset.cu')
        manifest = dict(toolchain='CUDA 12.8.93', arch='sm_89', zeros_n=24,
                        frontend=['nvcc', '-O3', '-DQSB_ZEROS_N=24', '-DQSB_NATIVE_MODULE=0', '--ptx', 'subset.cu'],
                        assembler=['ptxas', '-arch=sm_89', '-O3'],
                        cubin_bytes=len(payload), cubin_sha256=digest,
                        ptx_sha256=sha(ptx.read_bytes()), entries=entries,
                        globals=globals_, host_globals=sorted(used), sources=sources)
        (ROOT / 'native_sm89.cubin').write_bytes(payload)
        (ROOT / 'native_manifest.cuh').write_text('\n'.join(lines)+'\n')
        (ROOT / 'native_manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')
        if args.artifact_dir:
            args.artifact_dir.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ptx, args.artifact_dir / 'native.ptx')
            shutil.copyfile(cubin, args.artifact_dir / 'native.cubin')
            (args.artifact_dir / 'toolchain.txt').write_text(nvcc_version + ptxas_version)
        print(json.dumps({k:manifest[k] for k in ('cubin_bytes','cubin_sha256','ptx_sha256')}))

if __name__ == '__main__':
    main()
