#!/usr/bin/env python3
"""Rebuild the generic N=24/sm89 payload with CUDA 12.8.93 (no GPU needed).

Run from anywhere: python3 /path/to/candidates/subset/regenerate_native.py
Outputs only native_sm89.cubin, native_manifest.cuh and native_manifest.json.
The fixed benchmark command does not need to run this generator.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent

def sha(data):
    return hashlib.sha256(data).hexdigest()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--docker', help='Existing CUDA container with repository mounted at /work')
    parser.add_argument('--docker-workdir', default='/work/candidates/subset',
                        help='Candidate root inside the existing container')
    parser.add_argument('--artifacts', type=Path, default=ROOT.parent / 'native-regeneration',
                        help='Persistent build/log directory outside the candidate')
    args = parser.parse_args()
    artifacts = args.artifacts.resolve()
    if artifacts == ROOT or ROOT in artifacts.parents:
        raise SystemExit('Build artifacts must be outside the candidate')
    artifacts.mkdir(parents=True, exist_ok=True)
    prefix = ['docker', 'exec', '-w', args.docker_workdir, args.docker] if args.docker else []
    commands = []
    def run(command, log):
        commands.append(command)
        with (artifacts / log).open('w') as out:
            subprocess.run(prefix + command, cwd=ROOT, stdout=out,
                           stderr=subprocess.STDOUT, check=True)
    def relative(path):
        return os.path.relpath(path, ROOT)
    nvcc_version = subprocess.check_output(prefix + ['nvcc', '--version'], text=True)
    ptxas_version = subprocess.check_output(prefix + ['ptxas', '--version'], text=True)
    for version in (nvcc_version, ptxas_version):
        if 'V12.8.93' not in version:
            raise SystemExit('Reproducible payload requires CUDA V12.8.93')
    (artifacts / 'toolchain.txt').write_text(nvcc_version + ptxas_version)
    ptx = artifacts / 'native.ptx'
    cubin = artifacts / 'native.cubin'
    run(['nvcc', '-O3', '-DQSB_ZEROS_N=24', '-DQSB_NATIVE_MODULE=0',
         '--ptx', 'subset.cu', '-o', relative(ptx)], 'frontend.log')
    run(['ptxas', '-arch=sm_89', '-O3', relative(ptx), '-o', relative(cubin)], 'ptxas.log')
    text = ptx.read_text()
    payload = cubin.read_bytes()
    expected = '994014fb153b73eb4338b013d373734dc8350041378b2c39ed0199987cc38ae8'
    identity = dict(expected_bytes=933536, expected_sha256=expected,
                    actual_bytes=len(payload), actual_sha256=sha(payload),
                    pass_identity=len(payload) == 933536 and sha(payload) == expected)
    (artifacts / 'identity.json').write_text(json.dumps(identity, indent=2)+'\n')
    if not identity['pass_identity']:
        raise SystemExit('STOP: immutable native-v1 cubin identity mismatch; no outputs installed')
    entries = []
    for symbol, params in re.findall(r'\.visible\s+\.entry\s+(\w+)\s*\(([^)]*)\)', text, re.S):
        types = re.findall(r'\.param\s+\.(u\d+)\s+\w+', params)
        if len(types) != params.count('.param'):
            raise SystemExit('Unsupported PTX parameter type')
        m = re.match(r'_Z(\d+)', symbol)
        name = symbol[m.end():m.end() + int(m[1])]
        entries.append(dict(name=name, symbol=symbol, bytes=[int(t[1:])//8 for t in types]))
    globals_ = []
    for space, align, bits, name, array in re.findall(
        r'^\.(const|global)\s+\.align\s+(\d+)\s+\.([bu]\d+)\s+(\w+)(?:\[(\d+)\])?', text, re.M):
        globals_.append(dict(symbol=name, space=space, alignment=int(align),
                             bytes=int(bits[1:])//8 * int(array or 1)))
    if len(entries) != 7 or len(globals_) != 20:
        raise SystemExit(f'Unexpected module shape: {len(entries)} kernels, {len(globals_)} globals')
    digest = sha(payload)
    lines = ['// Generated by regenerate_native.py; do not edit.',
             '#define QSB_NATIVE_FILE "native_sm89.cubin"',
             f'#define QSB_NATIVE_BYTES {len(payload)}',
             'static const unsigned char payload_sha256[32] = {' +
             ','.join('0x'+digest[i:i+2] for i in range(0,64,2)) + '};',
             'static Kernel kernels[] = {']
    for e in entries:
        lines.append('{"'+e['name']+'", "'+e['symbol']+'", '+str(len(e['bytes']))+
                     ', {'+','.join(map(str,e['bytes']))+'}, NULL, false},')
    host_text = '\n'.join((ROOT / f).read_text() for f in
        ('tests/gpu_epochs/tree.cu', 'tests/gpu_epochs/window_schedule_shared.cuh'))
    used = set(re.findall(r'QSB_TO_SYMBOL\(\s*(\w+)', host_text))
    used.update(re.findall(r'QSB_FROM_SYMBOL\([^,]+,\s*(\w+)', host_text))
    if len(used) != 13 or not used <= {g['symbol'] for g in globals_}:
        raise SystemExit('Unexpected host symbol routing')
    lines += ['};', 'static Global globals[] = {']
    lines += [f'{{"{g["symbol"]}", {g["bytes"]}, NULL}},' for g in globals_ if g['symbol'] in used]
    lines += ['};']
    # Hash the recursive source inputs, excluding generated metadata. The
    # latter is excluded from the device build by QSB_NATIVE_MODULE=0.
    sources = {}
    def visit(path):
        rel = str(path.relative_to(ROOT))
        if rel in sources or path.name == 'native_manifest.cuh':
            return
        data = path.read_bytes()
        sources[rel] = sha(data)
        for inc in re.findall(r'^\s*#include\s+"([^"]+)"', data.decode(), re.M):
            visit((path.parent / inc).resolve())
    visit(ROOT / 'subset.cu')
    # Preprocessor dependency evidence for each explicit role, including the
    # generated carrier lookup header. This is separate from the conservative
    # recursive union, which deliberately includes inactive local branches.
    roles = {}
    for name, define in [('carrier', '1'), ('full_source', '0')]:
        dep = artifacts / (name + '.d')
        command = ['nvcc', '-O3', '-DQSB_ZEROS_N=24', '-DQSB_NATIVE_MODULE='+define,
                   '-M', 'subset.cu', '-o', relative(dep)]
        run(command, name + '-dependencies.log')
        local = {}
        for token in dep.read_text().replace('\\\n', ' ').split():
            path = (ROOT / token).resolve()
            if path.is_file() and (path == ROOT or ROOT in path.parents):
                local[str(path.relative_to(ROOT))] = sha(path.read_bytes())
        roles[name] = dict(defines={'QSB_NATIVE_MODULE': int(define),
                                   'QSB_HOST_CARRIER': int(define)},
                           local_dependencies=local)
    sources['regenerate_native.py'] = sha(Path(__file__).read_bytes())
    (artifacts / 'commands.json').write_text(json.dumps(commands, indent=2)+'\n')
    manifest = dict(source_roles=roles, toolchain='CUDA 12.8.93', arch='sm_89', zeros_n=24,
                    frontend=['nvcc', '-O3', '-DQSB_ZEROS_N=24', '-DQSB_NATIVE_MODULE=0', '--ptx', 'subset.cu'],
                    assembler=['ptxas', '-arch=sm_89', '-O3'],
                    cubin_bytes=len(payload), cubin_sha256=digest,
                    ptx_sha256=sha(ptx.read_bytes()), entries=entries,
                    globals=globals_, host_globals=sorted(used), sources=sources)
    (ROOT / 'native_sm89.cubin').write_bytes(payload)
    (ROOT / 'native_manifest.cuh').write_text('\n'.join(lines)+'\n')
    (ROOT / 'native_manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(json.dumps({k:manifest[k] for k in ('cubin_bytes','cubin_sha256','ptx_sha256')}))

if __name__ == '__main__':
    main()
