// Iter47: exact raw integer product narrowing, speculative reducer unchanged.
// Generated by lab/iter47_generate.py; GPL-3 as the containing field helpers.
#pragma once
#ifndef QSB_TREE_KARATSUBA
#define QSB_TREE_KARATSUBA 0
#endif
#if QSB_TREE_KARATSUBA != 0 && QSB_TREE_KARATSUBA != 1
#error QSB_TREE_KARATSUBA must be 0 or 1
#endif
#if QSB_TREE_KARATSUBA
#define QSB_KARAT_PRODUCT_PTX \
"{\n" \
".reg .u32 a<8>,b<8>,da<4>,db<4>,u<8>,v<8>,d<8>,c<9>,x<16>;\n" \
".reg .u64 aL0,aL1,aH0,aH1,bL0,bL1,bH0,bH1,ad0,ad1,bd0,bd1,ba,bb,t;\n" \
".reg .pred neg;\n" \
"mov.b64 {a0,a1}, %5;\n" \
"mov.b64 {a2,a3}, %6;\n" \
"mov.b64 {a4,a5}, %7;\n" \
"mov.b64 {a6,a7}, %8;\n" \
"mov.b64 aL0, {a0,a1};\n" \
"mov.b64 aL1, {a2,a3};\n" \
"mov.b64 aH0, {a4,a5};\n" \
"mov.b64 aH1, {a6,a7};\n" \
"mov.b64 {b0,b1}, %9;\n" \
"mov.b64 {b2,b3}, %10;\n" \
"mov.b64 {b4,b5}, %11;\n" \
"mov.b64 {b6,b7}, %12;\n" \
"mov.b64 bL0, {b0,b1};\n" \
"mov.b64 bL1, {b2,b3};\n" \
"mov.b64 bH0, {b4,b5};\n" \
"mov.b64 bH1, {b6,b7};\n" \
"sub.cc.u64 ad0,aH0,aL0; subc.cc.u64 ad1,aH1,aL1; subc.u64 ba,0,0;\n" \
"xor.b64 ad0,ad0,ba; xor.b64 ad1,ad1,ba;\n" \
"sub.cc.u64 ad0,ad0,ba; subc.u64 ad1,ad1,ba;\n" \
"mov.b64 {da0,da1}, ad0;\n" \
"mov.b64 {da2,da3}, ad1;\n" \
"sub.cc.u64 bd0,bH0,bL0; subc.cc.u64 bd1,bH1,bL1; subc.u64 bb,0,0;\n" \
"xor.b64 bd0,bd0,bb; xor.b64 bd1,bd1,bb;\n" \
"sub.cc.u64 bd0,bd0,bb; subc.u64 bd1,bd1,bb;\n" \
"mov.b64 {db0,db1}, bd0;\n" \
"mov.b64 {db2,db3}, bd1;\n" \
"setp.eq.u64 neg,ba,bb;\n" \
"{ .reg .u64 e<4>,o<3>,t,lc; .reg .u32 ec,cy,o7,y<6>;\n" \
"mul.wide.u32 e0,a0,b0; mul.wide.u32 e1,a0,b2;\n" \
"mul.wide.u32 t,a1,b1; add.cc.u64 e1,e1,t;\n" \
"mul.wide.u32 t,a1,b3; addc.u64 e2,t,0;\n" \
"mul.wide.u32 t,a2,b0; add.cc.u64 e1,e1,t;\n" \
"mul.wide.u32 t,a2,b2; addc.cc.u64 e2,e2,t; addc.u32 ec,0,0;\n" \
"mul.wide.u32 t,a3,b1; add.cc.u64 e2,e2,t;\n" \
"mul.wide.u32 t,a3,b3; addc.u64 e3,t,0;\n" \
"mul.wide.u32 o0,a0,b1; mul.wide.u32 o1,a0,b3;\n" \
"mul.wide.u32 t,a1,b0; add.cc.u64 o0,o0,t;\n" \
"mul.wide.u32 t,a1,b2; addc.cc.u64 o1,o1,t; addc.u32 cy,0,0; mov.b64 lc,{cy,ec};\n" \
"mul.wide.u32 t,a2,b1; add.cc.u64 o1,o1,t;\n" \
"mul.wide.u32 t,a2,b3; addc.u64 o2,t,lc;\n" \
"mul.wide.u32 t,a3,b0; add.cc.u64 o1,o1,t;\n" \
"mul.wide.u32 t,a3,b2; addc.cc.u64 o2,o2,t; addc.u32 o7,0,0;\n" \
"mov.b64 {u0,u1},e0;\n" \
"mov.b64 {u2,u3},e1;\n" \
"mov.b64 {u4,u5},e2;\n" \
"mov.b64 {u6,u7},e3;\n" \
"mov.b64 {y0,y1},o0;\n" \
"mov.b64 {y2,y3},o1;\n" \
"mov.b64 {y4,y5},o2;\n" \
"add.cc.u32 u1,u1,y0;\n" \
"addc.cc.u32 u2,u2,y1;\n" \
"addc.cc.u32 u3,u3,y2;\n" \
"addc.cc.u32 u4,u4,y3;\n" \
"addc.cc.u32 u5,u5,y4;\n" \
"addc.cc.u32 u6,u6,y5;\n" \
"addc.u32 u7,u7,o7; }\n" \
"{ .reg .u64 e<4>,o<3>,t,lc; .reg .u32 ec,cy,o7,y<6>;\n" \
"mul.wide.u32 e0,a4,b4; mul.wide.u32 e1,a4,b6;\n" \
"mul.wide.u32 t,a5,b5; add.cc.u64 e1,e1,t;\n" \
"mul.wide.u32 t,a5,b7; addc.u64 e2,t,0;\n" \
"mul.wide.u32 t,a6,b4; add.cc.u64 e1,e1,t;\n" \
"mul.wide.u32 t,a6,b6; addc.cc.u64 e2,e2,t; addc.u32 ec,0,0;\n" \
"mul.wide.u32 t,a7,b5; add.cc.u64 e2,e2,t;\n" \
"mul.wide.u32 t,a7,b7; addc.u64 e3,t,0;\n" \
"mul.wide.u32 o0,a4,b5; mul.wide.u32 o1,a4,b7;\n" \
"mul.wide.u32 t,a5,b4; add.cc.u64 o0,o0,t;\n" \
"mul.wide.u32 t,a5,b6; addc.cc.u64 o1,o1,t; addc.u32 cy,0,0; mov.b64 lc,{cy,ec};\n" \
"mul.wide.u32 t,a6,b5; add.cc.u64 o1,o1,t;\n" \
"mul.wide.u32 t,a6,b7; addc.u64 o2,t,lc;\n" \
"mul.wide.u32 t,a7,b4; add.cc.u64 o1,o1,t;\n" \
"mul.wide.u32 t,a7,b6; addc.cc.u64 o2,o2,t; addc.u32 o7,0,0;\n" \
"mov.b64 {v0,v1},e0;\n" \
"mov.b64 {v2,v3},e1;\n" \
"mov.b64 {v4,v5},e2;\n" \
"mov.b64 {v6,v7},e3;\n" \
"mov.b64 {y0,y1},o0;\n" \
"mov.b64 {y2,y3},o1;\n" \
"mov.b64 {y4,y5},o2;\n" \
"add.cc.u32 v1,v1,y0;\n" \
"addc.cc.u32 v2,v2,y1;\n" \
"addc.cc.u32 v3,v3,y2;\n" \
"addc.cc.u32 v4,v4,y3;\n" \
"addc.cc.u32 v5,v5,y4;\n" \
"addc.cc.u32 v6,v6,y5;\n" \
"addc.u32 v7,v7,o7; }\n" \
"{ .reg .u64 e<4>,o<3>,t,lc; .reg .u32 ec,cy,o7,y<6>;\n" \
"mul.wide.u32 e0,da0,db0; mul.wide.u32 e1,da0,db2;\n" \
"mul.wide.u32 t,da1,db1; add.cc.u64 e1,e1,t;\n" \
"mul.wide.u32 t,da1,db3; addc.u64 e2,t,0;\n" \
"mul.wide.u32 t,da2,db0; add.cc.u64 e1,e1,t;\n" \
"mul.wide.u32 t,da2,db2; addc.cc.u64 e2,e2,t; addc.u32 ec,0,0;\n" \
"mul.wide.u32 t,da3,db1; add.cc.u64 e2,e2,t;\n" \
"mul.wide.u32 t,da3,db3; addc.u64 e3,t,0;\n" \
"mul.wide.u32 o0,da0,db1; mul.wide.u32 o1,da0,db3;\n" \
"mul.wide.u32 t,da1,db0; add.cc.u64 o0,o0,t;\n" \
"mul.wide.u32 t,da1,db2; addc.cc.u64 o1,o1,t; addc.u32 cy,0,0; mov.b64 lc,{cy,ec};\n" \
"mul.wide.u32 t,da2,db1; add.cc.u64 o1,o1,t;\n" \
"mul.wide.u32 t,da2,db3; addc.u64 o2,t,lc;\n" \
"mul.wide.u32 t,da3,db0; add.cc.u64 o1,o1,t;\n" \
"mul.wide.u32 t,da3,db2; addc.cc.u64 o2,o2,t; addc.u32 o7,0,0;\n" \
"mov.b64 {d0,d1},e0;\n" \
"mov.b64 {d2,d3},e1;\n" \
"mov.b64 {d4,d5},e2;\n" \
"mov.b64 {d6,d7},e3;\n" \
"mov.b64 {y0,y1},o0;\n" \
"mov.b64 {y2,y3},o1;\n" \
"mov.b64 {y4,y5},o2;\n" \
"add.cc.u32 d1,d1,y0;\n" \
"addc.cc.u32 d2,d2,y1;\n" \
"addc.cc.u32 d3,d3,y2;\n" \
"addc.cc.u32 d4,d4,y3;\n" \
"addc.cc.u32 d5,d5,y4;\n" \
"addc.cc.u32 d6,d6,y5;\n" \
"addc.u32 d7,d7,o7; }\n" \
"add.cc.u32 c0,u0,v0;\n" \
"addc.cc.u32 c1,u1,v1;\n" \
"addc.cc.u32 c2,u2,v2;\n" \
"addc.cc.u32 c3,u3,v3;\n" \
"addc.cc.u32 c4,u4,v4;\n" \
"addc.cc.u32 c5,u5,v5;\n" \
"addc.cc.u32 c6,u6,v6;\n" \
"addc.cc.u32 c7,u7,v7;\n" \
"addc.u32 c8,0,0;\n" \
"@neg sub.cc.u32 c0,c0,d0;\n" \
"@neg subc.cc.u32 c1,c1,d1;\n" \
"@neg subc.cc.u32 c2,c2,d2;\n" \
"@neg subc.cc.u32 c3,c3,d3;\n" \
"@neg subc.cc.u32 c4,c4,d4;\n" \
"@neg subc.cc.u32 c5,c5,d5;\n" \
"@neg subc.cc.u32 c6,c6,d6;\n" \
"@neg subc.cc.u32 c7,c7,d7;\n" \
"@neg subc.u32 c8,c8,0;\n" \
"@!neg add.cc.u32 c0,c0,d0;\n" \
"@!neg addc.cc.u32 c1,c1,d1;\n" \
"@!neg addc.cc.u32 c2,c2,d2;\n" \
"@!neg addc.cc.u32 c3,c3,d3;\n" \
"@!neg addc.cc.u32 c4,c4,d4;\n" \
"@!neg addc.cc.u32 c5,c5,d5;\n" \
"@!neg addc.cc.u32 c6,c6,d6;\n" \
"@!neg addc.cc.u32 c7,c7,d7;\n" \
"@!neg addc.u32 c8,c8,0;\n" \
"mov.u32 x0,u0; mov.u32 x8,v0;\n" \
"mov.u32 x1,u1; mov.u32 x9,v1;\n" \
"mov.u32 x2,u2; mov.u32 x10,v2;\n" \
"mov.u32 x3,u3; mov.u32 x11,v3;\n" \
"mov.u32 x4,u4; mov.u32 x12,v4;\n" \
"mov.u32 x5,u5; mov.u32 x13,v5;\n" \
"mov.u32 x6,u6; mov.u32 x14,v6;\n" \
"mov.u32 x7,u7; mov.u32 x15,v7;\n" \
"add.cc.u32 x4,x4,c0;\n" \
"addc.cc.u32 x5,x5,c1;\n" \
"addc.cc.u32 x6,x6,c2;\n" \
"addc.cc.u32 x7,x7,c3;\n" \
"addc.cc.u32 x8,x8,c4;\n" \
"addc.cc.u32 x9,x9,c5;\n" \
"addc.cc.u32 x10,x10,c6;\n" \
"addc.cc.u32 x11,x11,c7;\n" \
"addc.cc.u32 x12,x12,c8;\n" \
"addc.cc.u32 x13,x13,0;\n" \
"addc.cc.u32 x14,x14,0;\n" \
"addc.u32 x15,x15,0;\n"

__device__ __forceinline__ void qsb_filter_mul_karatsuba(uint64_t *r, const uint64_t *a, const uint64_t *b, uint32_t &bad)
{
#ifdef __CUDA_ARCH__

uint64_t r0,r1,r2,r3; uint32_t carry;
asm( QSB_KARAT_PRODUCT_PTX
".reg .u64 r0,r1,r2,r3,h0,h1,h2,h3,f0,f1,f2,f3,g0,g1,g2,g3;\n\t.reg .u32 f8,g8,z0,z1,z2,z3,z4,z5,z6,z7,z8,z9,w0,w1,w2,w3,w4,w5,w6,w7,m0,m1,m2;\n\tmov.b64 r0, {x0,x1}; mov.b64 r1, {x2,x3}; mov.b64 r2, {x4,x5}; mov.b64 r3, {x6,x7};\n\tmov.b64 h0, {x8,x9}; mov.b64 h1, {x10,x11}; mov.b64 h2, {x12,x13}; mov.b64 h3, {x14,x15};\n\tmul.wide.u32 t, x8, 977;  add.cc.u64  f0, r0, t;\n\tmul.wide.u32 t, x10, 977; addc.cc.u64 f1, r1, t;\n\tmul.wide.u32 t, x12, 977; addc.cc.u64 f2, r2, t;\n\tmul.wide.u32 t, x14, 977; addc.cc.u64 f3, r3, t;\n\t\n\tmul.wide.u32 t, x9, 977;  add.cc.u64  g0, h0, t;\n\tmul.wide.u32 t, x11, 977; addc.cc.u64 g1, h1, t;\n\tmul.wide.u32 t, x13, 977; addc.cc.u64 g2, h2, t;\n\tmul.wide.u32 t, x15, 977; addc.u64 g3, h3, t;\n\tmov.b64 {z0,z1}, f0;\n\tmov.b64 {z2,z3}, f1;\n\tmov.b64 {z4,z5}, f2;\n\tmov.b64 {z6,z7}, f3;\n\tmov.b64 {w0,w1}, g0;\n\tmov.b64 {w2,w3}, g1;\n\tmov.b64 {w4,w5}, g2;\n\tmov.b64 {w6,w7}, g3;\n\tadd.cc.u32  z1, z1, w0;\n\taddc.cc.u32 z2, z2, w1;\n\taddc.cc.u32 z3, z3, w2;\n\taddc.cc.u32 z4, z4, w3;\n\taddc.cc.u32 z5, z5, w4;\n\taddc.cc.u32 z6, z6, w5;\n\taddc.cc.u32 z7, z7, w6;\n\taddc.u32 z8, 0, w7;\n\t{ .reg .u64 sfz,sft; .reg .u32 sfl;\n\tmov.b64 sfz, {z0, z8};\n\tmul.wide.u32 sft, z8, 977; add.cc.u64 sft, sft, sfz;\n\taddc.u32 m2, 0, 0;\n\tmov.b64 {z0, sfl}, sft;\n\tadd.cc.u32 z1, z1, sfl; }\n\t "
#if QSB_SHORT_CARRY2
"addc.u32 z2, z2, m2;"
#if QSB_SHORT_CARRY2_SENTINEL
"xor.b32 z0,z0,0xC0DE0001;\n\t"
#endif
#else
"addc.cc.u32 z2, z2, m2;\n\taddc.cc.u32 z3, z3, 0;\n\taddc.u32 z4, z4, 0;"
#endif
"\n\tmov.u32 %4, 0;\n\tmov.b64 %0, {z0,z1}; mov.b64 %1, {z2,z3}; mov.b64 %2, {z4,z5}; mov.b64 %3, {z6,z7};\n\t}"
: "=l"(r0),"=l"(r1),"=l"(r2),"=l"(r3),"=r"(carry)
: "l"(a[0]),"l"(a[1]),"l"(a[2]),"l"(a[3]),"l"(b[0]),"l"(b[1]),"l"(b[2]),"l"(b[3]) );

r[0]=r0; r[1]=r1; r[2]=r2; r[3]=r3;

#else
_ModMultCore(r,a,b);

#endif
}


#endif
