// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by a generator script (PAIR form, schedule pm9, YP_FOLD_DROP=switch). Do not edit by hand.
// QSB_Y_PAIR pair form: the deferred Y is carried as the pair (Q' = X3 - V in Y, R in RP); the next trip forms
// R = red(S*ZZZ + Q'*R_prev) with ONE reduction (two lean products, the second absorbing the first's low
// words as free 64-bit addends); f15 is not computed; the last add resolves Y = -red(y*ZZZ3 + Q'*R).
// Same reduction and drop class as P16. The P16 plumbing is reused: qsb_filter_mul16 copies (Y3 = Q', RP = R)
// and qsb_filter_fused16 is the four-operand fusion.
#pragma once
#if !QSB_SHORT_CARRY2 || !QSB_Z2_SPEC_CUT || !QSB_K32 || !QSB_SHORT_CARRY6 || !QSB_K32_BGLUE
#error "QSB_Y_PAIR was generated for the default short-carry chain"
#endif
#define QSB_Y_PAIR_PAIR 1
/* QSB_YP_FOLD_DROP (a rare-carry cut under, exactness behind the host gate): the fused R
 * reduction leaves out the two fold carries it alone captured (carry(f) out of f3 = r3 + 977*x14 + c and
 * carry(g) out of g3 = h3 + 977*x15 + c, each 1 only when that 64-bit word is within 977*2^32 of 2^64, about
 * 2^-23 each per reduction); the base f2 / f15 reductions drop the same two carries. When one is 1 the result
 * misses 2^256 (resp. 2^288) mod p, the candidate's point is wrong and its hit is lost; no false hit can pass
 * the exact host gate. About 8.25 fused reductions per candidate: about 2^-19 of candidates. Bit mask:
 * 1 = the chain loop's fused R (QSB_YP_FUSED_R), 2 = the last add (qsb_filter_fused16). Default 0: ptxas
 * already folds both captures into its IMAD.WIDE.X carry chains, so dropping them saves no slot, and every
 * loop form moves kernel_digest to 128 registers with 12 to 16 spill bytes (bit 2 alone: +3 slots).
 * 0 = the previous reduction byte for byte (both carries kept). */
#ifndef QSB_YP_FOLD_DROP
#define QSB_YP_FOLD_DROP 0
#endif
#if QSB_YP_FOLD_DROP < 0 || QSB_YP_FOLD_DROP > 3
#error "QSB_YP_FOLD_DROP is a mask of bits 1 and 2"
#endif
/* In-block, after S = AY + OFF: R = red(S*ZZZ + YY*RP), YY = Q'_prev, RP = R_prev. */
#if QSB_YP_FOLD_DROP & 1
#define QSB_YP_FUSED_R \
        "\t.reg .u32 yp_ca0,yp_ca1,yp_ca2,yp_ca3,yp_ca4,yp_ca5,yp_ca6,yp_ca7,yp_cb0,yp_cb1,yp_cb2,yp_cb3,yp_cb4,yp_cb5,yp_cb6,yp_cb7;\n" \
        "\t.reg .u64 yp_ce0,yp_ce1,yp_ce2,yp_ce3,yp_ce4,yp_ce5,yp_ce6,yp_ce7,yp_co0,yp_co1,yp_co2,yp_co3,yp_co4,yp_co5,yp_co6,yp_ct,yp_clc;\n" \
        "\t.reg .u32 yp_ccy,yp_cec10,yp_cec12,yp_cec14,yp_co15;\n" \
        "\t.reg .u32 yp_ma0,yp_ma1,yp_ma2,yp_ma3,yp_ma4,yp_ma5,yp_ma6,yp_ma7,yp_mb0,yp_mb1,yp_mb2,yp_mb3,yp_mb4,yp_mb5,yp_mb6,yp_mb7;\n" \
        "\t.reg .u64 yp_me0,yp_me1,yp_me2,yp_me3,yp_me4,yp_me5,yp_me6,yp_me7,yp_mo0,yp_mo1,yp_mo2,yp_mo3,yp_mo4,yp_mo5,yp_mo6,yp_mt,yp_mlc;\n" \
        "\t.reg .u32 yp_mcy,yp_mec10,yp_mec12,yp_mec14,yp_mx0,yp_mx1,yp_mx2,yp_mx3,yp_mx4,yp_mx5,yp_mx6,yp_mx7,yp_mx8,yp_mx9,yp_mx10,yp_mx11,yp_mx12,yp_mx13,yp_mx14,yp_mx15,yp_mx16,yp_my1,yp_my2,yp_my3,yp_my4,yp_my5,yp_my6,yp_my7,yp_my8,yp_my9,yp_my10,yp_my11,yp_my12,yp_my13,yp_my14,yp_mobc,yp_u8,yp_u9,yp_u10,yp_u11,yp_u12,yp_u13,yp_u14,yp_u15,yp_u16,yp_v9,yp_v10,yp_v11,yp_v12,yp_v13,yp_v14;\n" \
        "\tmov.b64 {yp_ca0,yp_ca1}, YY0;\n" \
        "\tmov.b64 {yp_ca2,yp_ca3}, YY1;\n" \
        "\tmov.b64 {yp_ca4,yp_ca5}, YY2;\n" \
        "\tmov.b64 {yp_ca6,yp_ca7}, YY3;\n" \
        "\tmov.b64 {yp_cb0,yp_cb1}, RP0;\n" \
        "\tmov.b64 {yp_cb2,yp_cb3}, RP1;\n" \
        "\tmov.b64 {yp_cb4,yp_cb5}, RP2;\n" \
        "\tmov.b64 {yp_cb6,yp_cb7}, RP3;\n" \
        "\tmul.wide.u32 yp_ce0, yp_ca0, yp_cb0; mul.wide.u32 yp_ce1, yp_ca0, yp_cb2; mul.wide.u32 yp_ce2, yp_ca0, yp_cb4; mul.wide.u32 yp_ce3, yp_ca0, yp_cb6;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb1; add.cc.u64 yp_ce1, yp_ce1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb3; addc.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb5; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb7; addc.u64 yp_ce4, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb0; add.cc.u64 yp_ce1, yp_ce1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb2; addc.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb4; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb6; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\taddc.u32 yp_cec10, 0, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb1; add.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb3; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb5; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb7; addc.u64 yp_ce5, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb0; add.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb2; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb4; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb6; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\taddc.u32 yp_cec12, 0, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb1; add.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb3; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb5; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb7; addc.u64 yp_ce6, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb0; add.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb2; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb4; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb6; addc.cc.u64 yp_ce6, yp_ce6, yp_ct;\n" \
        "\taddc.u32 yp_cec14, 0, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb1; add.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb3; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb5; addc.cc.u64 yp_ce6, yp_ce6, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb7; addc.u64 yp_ce7, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_co0, yp_ca0, yp_cb1; mul.wide.u32 yp_co1, yp_ca0, yp_cb3; mul.wide.u32 yp_co2, yp_ca0, yp_cb5; mul.wide.u32 yp_co3, yp_ca0, yp_cb7;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb0; add.cc.u64 yp_co0, yp_co0, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb2; addc.cc.u64 yp_co1, yp_co1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb4; addc.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb6; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\taddc.u32 yp_ccy, 0, 0;\n" \
        "\tmov.b64 yp_clc, {yp_ccy, yp_cec10};\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb1; add.cc.u64 yp_co1, yp_co1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb3; addc.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb5; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb7; addc.u64 yp_co4, yp_ct, yp_clc;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb0; add.cc.u64 yp_co1, yp_co1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb2; addc.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb4; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb6; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\taddc.u32 yp_ccy, 0, 0;\n" \
        "\tmov.b64 yp_clc, {yp_ccy, yp_cec12};\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb1; add.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb3; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb5; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb7; addc.u64 yp_co5, yp_ct, yp_clc;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb0; add.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb2; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb4; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb6; addc.cc.u64 yp_co5, yp_co5, yp_ct;\n" \
        "\taddc.u32 yp_ccy, 0, 0;\n" \
        "\tmov.b64 yp_clc, {yp_ccy, yp_cec14};\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb1; add.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb3; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb5; addc.cc.u64 yp_co5, yp_co5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb7; addc.u64 yp_co6, yp_ct, yp_clc;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb0; add.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb2; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb4; addc.cc.u64 yp_co5, yp_co5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb6; addc.cc.u64 yp_co6, yp_co6, yp_ct;\n" \
        "\taddc.u32 yp_co15, 0, 0;\n" \
        "\tmov.b64 {yp_u8,yp_u9}, yp_ce4;\n" \
        "\tmov.b64 {yp_u10,yp_u11}, yp_ce5;\n" \
        "\tmov.b64 {yp_u12,yp_u13}, yp_ce6;\n" \
        "\tmov.b64 {yp_u14,yp_u15}, yp_ce7;\n" \
        "\tmov.b64 {yp_v9,yp_v10}, yp_co4;\n" \
        "\tmov.b64 {yp_v11,yp_v12}, yp_co5;\n" \
        "\tmov.b64 {yp_v13,yp_v14}, yp_co6;\n" \
        "\tmov.b64 {yp_ma0,yp_ma1}, S0;\n" \
        "\tmov.b64 {yp_ma2,yp_ma3}, S1;\n" \
        "\tmov.b64 {yp_ma4,yp_ma5}, S2;\n" \
        "\tmov.b64 {yp_ma6,yp_ma7}, S3;\n" \
        "\tmov.b64 {yp_mb0,yp_mb1}, ZZZ0;\n" \
        "\tmov.b64 {yp_mb2,yp_mb3}, ZZZ1;\n" \
        "\tmov.b64 {yp_mb4,yp_mb5}, ZZZ2;\n" \
        "\tmov.b64 {yp_mb6,yp_mb7}, ZZZ3;\n" \
        "\tmul.wide.u32 yp_me0, yp_ma0, yp_mb0; mul.wide.u32 yp_me1, yp_ma0, yp_mb2; mul.wide.u32 yp_me2, yp_ma0, yp_mb4; mul.wide.u32 yp_me3, yp_ma0, yp_mb6;\n" \
        "\tadd.cc.u64 yp_me0, yp_me0, yp_ce0;\n" \
        "\taddc.cc.u64 yp_me1, yp_me1, yp_ce1;\n" \
        "\taddc.cc.u64 yp_me2, yp_me2, yp_ce2;\n" \
        "\taddc.cc.u64 yp_me3, yp_me3, yp_ce3;\n" \
        "\taddc.cc.u32 yp_u8, yp_u8, 0;\n" \
        "\taddc.cc.u32 yp_u9, yp_u9, yp_v9;\n" \
        "\taddc.cc.u32 yp_u10, yp_u10, yp_v10;\n" \
        "\taddc.cc.u32 yp_u11, yp_u11, yp_v11;\n" \
        "\taddc.cc.u32 yp_u12, yp_u12, yp_v12;\n" \
        "\taddc.cc.u32 yp_u13, yp_u13, yp_v13;\n" \
        "\taddc.cc.u32 yp_u14, yp_u14, yp_v14;\n" \
        "\taddc.cc.u32 yp_u15, yp_u15, yp_co15;\n" \
        "\taddc.u32 yp_u16, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb1; add.cc.u64 yp_me1, yp_me1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb3; addc.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb5; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb7; addc.u64 yp_me4, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb0; add.cc.u64 yp_me1, yp_me1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb2; addc.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb4; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb6; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\taddc.u32 yp_mec10, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb1; add.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb3; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb5; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb7; addc.u64 yp_me5, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb0; add.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb2; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb4; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb6; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\taddc.u32 yp_mec12, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb1; add.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb3; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb5; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb7; addc.u64 yp_me6, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb0; add.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb2; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb4; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb6; addc.cc.u64 yp_me6, yp_me6, yp_mt;\n" \
        "\taddc.u32 yp_mec14, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb1; add.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb3; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb5; addc.cc.u64 yp_me6, yp_me6, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb7; addc.u64 yp_me7, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mo0, yp_ma0, yp_mb1; mul.wide.u32 yp_mo1, yp_ma0, yp_mb3; mul.wide.u32 yp_mo2, yp_ma0, yp_mb5; mul.wide.u32 yp_mo3, yp_ma0, yp_mb7;\n" \
        "\tadd.cc.u64 yp_mo0, yp_mo0, yp_co0;\n" \
        "\taddc.cc.u64 yp_mo1, yp_mo1, yp_co1;\n" \
        "\taddc.cc.u64 yp_mo2, yp_mo2, yp_co2;\n" \
        "\taddc.cc.u64 yp_mo3, yp_mo3, yp_co3;\n" \
        "\taddc.u32 yp_mobc, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb0; add.cc.u64 yp_mo0, yp_mo0, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb2; addc.cc.u64 yp_mo1, yp_mo1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb4; addc.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb6; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\taddc.u32 yp_mcy, 0, 0;\n" \
        "\tadd.u32 yp_mcy, yp_mcy, yp_mobc;\n" \
        "\tmov.b64 yp_mlc, {yp_mcy, yp_mec10};\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb1; add.cc.u64 yp_mo1, yp_mo1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb3; addc.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb5; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb7; addc.u64 yp_mo4, yp_mt, yp_mlc;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb0; add.cc.u64 yp_mo1, yp_mo1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb2; addc.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb4; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb6; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\taddc.u32 yp_mcy, 0, 0;\n" \
        "\tmov.b64 yp_mlc, {yp_mcy, yp_mec12};\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb1; add.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb3; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb5; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb7; addc.u64 yp_mo5, yp_mt, yp_mlc;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb0; add.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb2; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb4; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb6; addc.cc.u64 yp_mo5, yp_mo5, yp_mt;\n" \
        "\taddc.u32 yp_mcy, 0, 0;\n" \
        "\tmov.b64 yp_mlc, {yp_mcy, yp_mec14};\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb1; add.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb3; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb5; addc.cc.u64 yp_mo5, yp_mo5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb7; addc.u64 yp_mo6, yp_mt, yp_mlc;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb0; add.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb2; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb4; addc.cc.u64 yp_mo5, yp_mo5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb6; addc.cc.u64 yp_mo6, yp_mo6, yp_mt;\n" \
        "\tmov.b64 {yp_mx14,yp_mx15}, yp_me7;\n" \
        "\taddc.cc.u32 yp_mx15, yp_mx15, 0;\n" \
        "\taddc.u32 yp_mx16, yp_u16, 0;\n" \
        "\tmov.b64 {yp_mx0,yp_mx1}, yp_me0;\n" \
        "\tmov.b64 {yp_mx2,yp_mx3}, yp_me1;\n" \
        "\tmov.b64 {yp_mx4,yp_mx5}, yp_me2;\n" \
        "\tmov.b64 {yp_mx6,yp_mx7}, yp_me3;\n" \
        "\tmov.b64 {yp_mx8,yp_mx9}, yp_me4;\n" \
        "\tmov.b64 {yp_mx10,yp_mx11}, yp_me5;\n" \
        "\tmov.b64 {yp_mx12,yp_mx13}, yp_me6;\n" \
        "\tmov.b64 {yp_my1,yp_my2}, yp_mo0;\n" \
        "\tmov.b64 {yp_my3,yp_my4}, yp_mo1;\n" \
        "\tmov.b64 {yp_my5,yp_my6}, yp_mo2;\n" \
        "\tmov.b64 {yp_my7,yp_my8}, yp_mo3;\n" \
        "\tmov.b64 {yp_my9,yp_my10}, yp_mo4;\n" \
        "\tmov.b64 {yp_my11,yp_my12}, yp_mo5;\n" \
        "\tmov.b64 {yp_my13,yp_my14}, yp_mo6;\n" \
        "\tadd.cc.u32 yp_mx1, yp_mx1, yp_my1;\n" \
        "\taddc.cc.u32 yp_mx2, yp_mx2, yp_my2;\n" \
        "\taddc.cc.u32 yp_mx3, yp_mx3, yp_my3;\n" \
        "\taddc.cc.u32 yp_mx4, yp_mx4, yp_my4;\n" \
        "\taddc.cc.u32 yp_mx5, yp_mx5, yp_my5;\n" \
        "\taddc.cc.u32 yp_mx6, yp_mx6, yp_my6;\n" \
        "\taddc.cc.u32 yp_mx7, yp_mx7, yp_my7;\n" \
        "\taddc.cc.u32 yp_mx8, yp_mx8, yp_my8;\n" \
        "\taddc.cc.u32 yp_mx9, yp_mx9, yp_my9;\n" \
        "\taddc.cc.u32 yp_mx10, yp_mx10, yp_my10;\n" \
        "\taddc.cc.u32 yp_mx11, yp_mx11, yp_my11;\n" \
        "\taddc.cc.u32 yp_mx12, yp_mx12, yp_my12;\n" \
        "\taddc.cc.u32 yp_mx13, yp_mx13, yp_my13;\n" \
        "\taddc.cc.u32 yp_mx14, yp_mx14, yp_my14;\n" \
        "\taddc.cc.u32 yp_mx15, yp_mx15, 0;\n" \
        "\taddc.u32 yp_mx16, yp_mx16, 0;\n" \
        "\tadd.cc.u32 yp_mx8, yp_mx8, yp_u8;\n" \
        "\taddc.cc.u32 yp_mx9, yp_mx9, yp_u9;\n" \
        "\taddc.cc.u32 yp_mx10, yp_mx10, yp_u10;\n" \
        "\taddc.cc.u32 yp_mx11, yp_mx11, yp_u11;\n" \
        "\taddc.cc.u32 yp_mx12, yp_mx12, yp_u12;\n" \
        "\taddc.cc.u32 yp_mx13, yp_mx13, yp_u13;\n" \
        "\taddc.cc.u32 yp_mx14, yp_mx14, yp_u14;\n" \
        "\taddc.cc.u32 yp_mx15, yp_mx15, yp_u15;\n" \
        "\taddc.u32 yp_mx16, yp_mx16, 0;\n" \
        "\t.reg .u64 yp_mr0,yp_mr1,yp_mr2,yp_mr3,yp_mh0,yp_mh1,yp_mh2,yp_mh3,yp_mf0,yp_mf1,yp_mf2,yp_mf3,yp_mg0,yp_mg1,yp_mg2,yp_mg3,yp_msfz,yp_msft;\n" \
        "\t.reg .u32 yp_mz0,yp_mz1,yp_mz2,yp_mz3,yp_mz4,yp_mz5,yp_mz6,yp_mz7,yp_mz8,yp_mz9,yp_mw0,yp_mw1,yp_mw2,yp_mw3,yp_mw4,yp_mw5,yp_mw6,yp_mw7,yp_mk16,yp_mk9,yp_msfq,yp_msfh,yp_msfc,yp_msfhi;\n" \
        "\tmul.lo.u32 yp_mk16, yp_mx16, 977;\n" \
        "\tmov.b64 yp_mr0, {yp_mx0,yp_mx1};\n" \
        "\tmov.b64 yp_mr1, {yp_mx2,yp_mx3};\n" \
        "\tmov.b64 yp_mr2, {yp_mx4,yp_mx5};\n" \
        "\tmov.b64 yp_mr3, {yp_mx6,yp_mx7};\n" \
        "\tmov.b64 yp_mh0, {yp_mx8,yp_mx9};\n" \
        "\tmov.b64 yp_mh1, {yp_mx10,yp_mx11};\n" \
        "\tmov.b64 yp_mh2, {yp_mx12,yp_mx13};\n" \
        "\tmov.b64 yp_mh3, {yp_mx14,yp_mx15};\n" \
        "\tmul.wide.u32 yp_mt, yp_mx9, 977; add.cc.u64 yp_mg0, yp_mh0, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx11, 977; addc.cc.u64 yp_mg1, yp_mh1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx13, 977; addc.cc.u64 yp_mg2, yp_mh2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx15, 977; addc.u64 yp_mg3, yp_mh3, yp_mt;\n" \
        "\tmov.b64 {yp_mw0,yp_mw1}, yp_mg0;\n" \
        "\tmov.b64 {yp_mw2,yp_mw3}, yp_mg1;\n" \
        "\tmov.b64 {yp_mw4,yp_mw5}, yp_mg2;\n" \
        "\tmov.b64 {yp_mw6,yp_mw7}, yp_mg3;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx8, 977; add.cc.u64 yp_mf0, yp_mr0, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx10, 977; addc.cc.u64 yp_mf1, yp_mr1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx12, 977; addc.cc.u64 yp_mf2, yp_mr2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx14, 977; addc.u64 yp_mf3, yp_mr3, yp_mt;\n" \
        "\tmov.b64 {yp_mz0,yp_mz1}, yp_mf0;\n" \
        "\tmov.b64 {yp_mz2,yp_mz3}, yp_mf1;\n" \
        "\tmov.b64 {yp_mz4,yp_mz5}, yp_mf2;\n" \
        "\tmov.b64 {yp_mz6,yp_mz7}, yp_mf3;\n" \
        "\tadd.cc.u32 yp_mz1, yp_mz1, yp_mw0;\n" \
        "\taddc.cc.u32 yp_mz2, yp_mz2, yp_mw1;\n" \
        "\taddc.cc.u32 yp_mz3, yp_mz3, yp_mw2;\n" \
        "\taddc.cc.u32 yp_mz4, yp_mz4, yp_mw3;\n" \
        "\taddc.cc.u32 yp_mz5, yp_mz5, yp_mw4;\n" \
        "\taddc.cc.u32 yp_mz6, yp_mz6, yp_mw5;\n" \
        "\taddc.cc.u32 yp_mz7, yp_mz7, yp_mw6;\n" \
        "\taddc.cc.u32 yp_mz8, yp_mk16, yp_mw7;\n" \
        "\taddc.u32 yp_mz9, yp_mx16, 0;\n" \
        "\tmul.lo.u32 yp_mk9, yp_mz9, 977;\n" \
        "\tadd.cc.u32 yp_msfq, yp_mz8, yp_mk9;\n" \
        "\taddc.u32 yp_msfh, yp_mz9, 0;\n" \
        "\tmov.b64 yp_msfz, {yp_mz0, yp_msfq};\n" \
        "\tmul.wide.u32 yp_msft, yp_mz8, 977; add.cc.u64 yp_msft, yp_msft, yp_msfz;\n" \
        "\taddc.u32 yp_msfc, yp_msfh, 0;\n" \
        "\tmov.b64 {yp_mz0, yp_msfhi}, yp_msft;\n" \
        "\tadd.cc.u32 yp_mz1, yp_mz1, yp_msfhi;\n" \
        "\taddc.u32 yp_mz2, yp_mz2, yp_msfc;\n" \
        "\tmov.b64 R0, {yp_mz0,yp_mz1};\n" \
        "\tmov.b64 R1, {yp_mz2,yp_mz3};\n" \
        "\tmov.b64 R2, {yp_mz4,yp_mz5};\n" \
        "\tmov.b64 R3, {yp_mz6,yp_mz7};\n"
#else
#define QSB_YP_FUSED_R \
        "\t.reg .u32 yp_ca0,yp_ca1,yp_ca2,yp_ca3,yp_ca4,yp_ca5,yp_ca6,yp_ca7,yp_cb0,yp_cb1,yp_cb2,yp_cb3,yp_cb4,yp_cb5,yp_cb6,yp_cb7;\n" \
        "\t.reg .u64 yp_ce0,yp_ce1,yp_ce2,yp_ce3,yp_ce4,yp_ce5,yp_ce6,yp_ce7,yp_co0,yp_co1,yp_co2,yp_co3,yp_co4,yp_co5,yp_co6,yp_ct,yp_clc;\n" \
        "\t.reg .u32 yp_ccy,yp_cec10,yp_cec12,yp_cec14,yp_co15;\n" \
        "\t.reg .u32 yp_ma0,yp_ma1,yp_ma2,yp_ma3,yp_ma4,yp_ma5,yp_ma6,yp_ma7,yp_mb0,yp_mb1,yp_mb2,yp_mb3,yp_mb4,yp_mb5,yp_mb6,yp_mb7;\n" \
        "\t.reg .u64 yp_me0,yp_me1,yp_me2,yp_me3,yp_me4,yp_me5,yp_me6,yp_me7,yp_mo0,yp_mo1,yp_mo2,yp_mo3,yp_mo4,yp_mo5,yp_mo6,yp_mt,yp_mlc;\n" \
        "\t.reg .u32 yp_mcy,yp_mec10,yp_mec12,yp_mec14,yp_mx0,yp_mx1,yp_mx2,yp_mx3,yp_mx4,yp_mx5,yp_mx6,yp_mx7,yp_mx8,yp_mx9,yp_mx10,yp_mx11,yp_mx12,yp_mx13,yp_mx14,yp_mx15,yp_mx16,yp_my1,yp_my2,yp_my3,yp_my4,yp_my5,yp_my6,yp_my7,yp_my8,yp_my9,yp_my10,yp_my11,yp_my12,yp_my13,yp_my14,yp_mobc,yp_u8,yp_u9,yp_u10,yp_u11,yp_u12,yp_u13,yp_u14,yp_u15,yp_u16,yp_v9,yp_v10,yp_v11,yp_v12,yp_v13,yp_v14;\n" \
        "\tmov.b64 {yp_ca0,yp_ca1}, YY0;\n" \
        "\tmov.b64 {yp_ca2,yp_ca3}, YY1;\n" \
        "\tmov.b64 {yp_ca4,yp_ca5}, YY2;\n" \
        "\tmov.b64 {yp_ca6,yp_ca7}, YY3;\n" \
        "\tmov.b64 {yp_cb0,yp_cb1}, RP0;\n" \
        "\tmov.b64 {yp_cb2,yp_cb3}, RP1;\n" \
        "\tmov.b64 {yp_cb4,yp_cb5}, RP2;\n" \
        "\tmov.b64 {yp_cb6,yp_cb7}, RP3;\n" \
        "\tmul.wide.u32 yp_ce0, yp_ca0, yp_cb0; mul.wide.u32 yp_ce1, yp_ca0, yp_cb2; mul.wide.u32 yp_ce2, yp_ca0, yp_cb4; mul.wide.u32 yp_ce3, yp_ca0, yp_cb6;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb1; add.cc.u64 yp_ce1, yp_ce1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb3; addc.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb5; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb7; addc.u64 yp_ce4, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb0; add.cc.u64 yp_ce1, yp_ce1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb2; addc.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb4; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb6; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\taddc.u32 yp_cec10, 0, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb1; add.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb3; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb5; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb7; addc.u64 yp_ce5, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb0; add.cc.u64 yp_ce2, yp_ce2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb2; addc.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb4; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb6; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\taddc.u32 yp_cec12, 0, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb1; add.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb3; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb5; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb7; addc.u64 yp_ce6, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb0; add.cc.u64 yp_ce3, yp_ce3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb2; addc.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb4; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb6; addc.cc.u64 yp_ce6, yp_ce6, yp_ct;\n" \
        "\taddc.u32 yp_cec14, 0, 0;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb1; add.cc.u64 yp_ce4, yp_ce4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb3; addc.cc.u64 yp_ce5, yp_ce5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb5; addc.cc.u64 yp_ce6, yp_ce6, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb7; addc.u64 yp_ce7, yp_ct, 0;\n" \
        "\tmul.wide.u32 yp_co0, yp_ca0, yp_cb1; mul.wide.u32 yp_co1, yp_ca0, yp_cb3; mul.wide.u32 yp_co2, yp_ca0, yp_cb5; mul.wide.u32 yp_co3, yp_ca0, yp_cb7;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb0; add.cc.u64 yp_co0, yp_co0, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb2; addc.cc.u64 yp_co1, yp_co1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb4; addc.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca1, yp_cb6; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\taddc.u32 yp_ccy, 0, 0;\n" \
        "\tmov.b64 yp_clc, {yp_ccy, yp_cec10};\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb1; add.cc.u64 yp_co1, yp_co1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb3; addc.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb5; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca2, yp_cb7; addc.u64 yp_co4, yp_ct, yp_clc;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb0; add.cc.u64 yp_co1, yp_co1, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb2; addc.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb4; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca3, yp_cb6; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\taddc.u32 yp_ccy, 0, 0;\n" \
        "\tmov.b64 yp_clc, {yp_ccy, yp_cec12};\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb1; add.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb3; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb5; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca4, yp_cb7; addc.u64 yp_co5, yp_ct, yp_clc;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb0; add.cc.u64 yp_co2, yp_co2, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb2; addc.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb4; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca5, yp_cb6; addc.cc.u64 yp_co5, yp_co5, yp_ct;\n" \
        "\taddc.u32 yp_ccy, 0, 0;\n" \
        "\tmov.b64 yp_clc, {yp_ccy, yp_cec14};\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb1; add.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb3; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb5; addc.cc.u64 yp_co5, yp_co5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca6, yp_cb7; addc.u64 yp_co6, yp_ct, yp_clc;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb0; add.cc.u64 yp_co3, yp_co3, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb2; addc.cc.u64 yp_co4, yp_co4, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb4; addc.cc.u64 yp_co5, yp_co5, yp_ct;\n" \
        "\tmul.wide.u32 yp_ct, yp_ca7, yp_cb6; addc.cc.u64 yp_co6, yp_co6, yp_ct;\n" \
        "\taddc.u32 yp_co15, 0, 0;\n" \
        "\tmov.b64 {yp_u8,yp_u9}, yp_ce4;\n" \
        "\tmov.b64 {yp_u10,yp_u11}, yp_ce5;\n" \
        "\tmov.b64 {yp_u12,yp_u13}, yp_ce6;\n" \
        "\tmov.b64 {yp_u14,yp_u15}, yp_ce7;\n" \
        "\tmov.b64 {yp_v9,yp_v10}, yp_co4;\n" \
        "\tmov.b64 {yp_v11,yp_v12}, yp_co5;\n" \
        "\tmov.b64 {yp_v13,yp_v14}, yp_co6;\n" \
        "\tmov.b64 {yp_ma0,yp_ma1}, S0;\n" \
        "\tmov.b64 {yp_ma2,yp_ma3}, S1;\n" \
        "\tmov.b64 {yp_ma4,yp_ma5}, S2;\n" \
        "\tmov.b64 {yp_ma6,yp_ma7}, S3;\n" \
        "\tmov.b64 {yp_mb0,yp_mb1}, ZZZ0;\n" \
        "\tmov.b64 {yp_mb2,yp_mb3}, ZZZ1;\n" \
        "\tmov.b64 {yp_mb4,yp_mb5}, ZZZ2;\n" \
        "\tmov.b64 {yp_mb6,yp_mb7}, ZZZ3;\n" \
        "\tmul.wide.u32 yp_me0, yp_ma0, yp_mb0; mul.wide.u32 yp_me1, yp_ma0, yp_mb2; mul.wide.u32 yp_me2, yp_ma0, yp_mb4; mul.wide.u32 yp_me3, yp_ma0, yp_mb6;\n" \
        "\tadd.cc.u64 yp_me0, yp_me0, yp_ce0;\n" \
        "\taddc.cc.u64 yp_me1, yp_me1, yp_ce1;\n" \
        "\taddc.cc.u64 yp_me2, yp_me2, yp_ce2;\n" \
        "\taddc.cc.u64 yp_me3, yp_me3, yp_ce3;\n" \
        "\taddc.cc.u32 yp_u8, yp_u8, 0;\n" \
        "\taddc.cc.u32 yp_u9, yp_u9, yp_v9;\n" \
        "\taddc.cc.u32 yp_u10, yp_u10, yp_v10;\n" \
        "\taddc.cc.u32 yp_u11, yp_u11, yp_v11;\n" \
        "\taddc.cc.u32 yp_u12, yp_u12, yp_v12;\n" \
        "\taddc.cc.u32 yp_u13, yp_u13, yp_v13;\n" \
        "\taddc.cc.u32 yp_u14, yp_u14, yp_v14;\n" \
        "\taddc.cc.u32 yp_u15, yp_u15, yp_co15;\n" \
        "\taddc.u32 yp_u16, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb1; add.cc.u64 yp_me1, yp_me1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb3; addc.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb5; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb7; addc.u64 yp_me4, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb0; add.cc.u64 yp_me1, yp_me1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb2; addc.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb4; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb6; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\taddc.u32 yp_mec10, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb1; add.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb3; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb5; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb7; addc.u64 yp_me5, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb0; add.cc.u64 yp_me2, yp_me2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb2; addc.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb4; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb6; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\taddc.u32 yp_mec12, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb1; add.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb3; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb5; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb7; addc.u64 yp_me6, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb0; add.cc.u64 yp_me3, yp_me3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb2; addc.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb4; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb6; addc.cc.u64 yp_me6, yp_me6, yp_mt;\n" \
        "\taddc.u32 yp_mec14, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb1; add.cc.u64 yp_me4, yp_me4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb3; addc.cc.u64 yp_me5, yp_me5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb5; addc.cc.u64 yp_me6, yp_me6, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb7; addc.u64 yp_me7, yp_mt, 0;\n" \
        "\tmul.wide.u32 yp_mo0, yp_ma0, yp_mb1; mul.wide.u32 yp_mo1, yp_ma0, yp_mb3; mul.wide.u32 yp_mo2, yp_ma0, yp_mb5; mul.wide.u32 yp_mo3, yp_ma0, yp_mb7;\n" \
        "\tadd.cc.u64 yp_mo0, yp_mo0, yp_co0;\n" \
        "\taddc.cc.u64 yp_mo1, yp_mo1, yp_co1;\n" \
        "\taddc.cc.u64 yp_mo2, yp_mo2, yp_co2;\n" \
        "\taddc.cc.u64 yp_mo3, yp_mo3, yp_co3;\n" \
        "\taddc.u32 yp_mobc, 0, 0;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb0; add.cc.u64 yp_mo0, yp_mo0, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb2; addc.cc.u64 yp_mo1, yp_mo1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb4; addc.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma1, yp_mb6; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\taddc.u32 yp_mcy, 0, 0;\n" \
        "\tadd.u32 yp_mcy, yp_mcy, yp_mobc;\n" \
        "\tmov.b64 yp_mlc, {yp_mcy, yp_mec10};\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb1; add.cc.u64 yp_mo1, yp_mo1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb3; addc.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb5; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma2, yp_mb7; addc.u64 yp_mo4, yp_mt, yp_mlc;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb0; add.cc.u64 yp_mo1, yp_mo1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb2; addc.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb4; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma3, yp_mb6; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\taddc.u32 yp_mcy, 0, 0;\n" \
        "\tmov.b64 yp_mlc, {yp_mcy, yp_mec12};\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb1; add.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb3; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb5; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma4, yp_mb7; addc.u64 yp_mo5, yp_mt, yp_mlc;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb0; add.cc.u64 yp_mo2, yp_mo2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb2; addc.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb4; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma5, yp_mb6; addc.cc.u64 yp_mo5, yp_mo5, yp_mt;\n" \
        "\taddc.u32 yp_mcy, 0, 0;\n" \
        "\tmov.b64 yp_mlc, {yp_mcy, yp_mec14};\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb1; add.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb3; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb5; addc.cc.u64 yp_mo5, yp_mo5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma6, yp_mb7; addc.u64 yp_mo6, yp_mt, yp_mlc;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb0; add.cc.u64 yp_mo3, yp_mo3, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb2; addc.cc.u64 yp_mo4, yp_mo4, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb4; addc.cc.u64 yp_mo5, yp_mo5, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_ma7, yp_mb6; addc.cc.u64 yp_mo6, yp_mo6, yp_mt;\n" \
        "\tmov.b64 {yp_mx14,yp_mx15}, yp_me7;\n" \
        "\taddc.cc.u32 yp_mx15, yp_mx15, 0;\n" \
        "\taddc.u32 yp_mx16, yp_u16, 0;\n" \
        "\tmov.b64 {yp_mx0,yp_mx1}, yp_me0;\n" \
        "\tmov.b64 {yp_mx2,yp_mx3}, yp_me1;\n" \
        "\tmov.b64 {yp_mx4,yp_mx5}, yp_me2;\n" \
        "\tmov.b64 {yp_mx6,yp_mx7}, yp_me3;\n" \
        "\tmov.b64 {yp_mx8,yp_mx9}, yp_me4;\n" \
        "\tmov.b64 {yp_mx10,yp_mx11}, yp_me5;\n" \
        "\tmov.b64 {yp_mx12,yp_mx13}, yp_me6;\n" \
        "\tmov.b64 {yp_my1,yp_my2}, yp_mo0;\n" \
        "\tmov.b64 {yp_my3,yp_my4}, yp_mo1;\n" \
        "\tmov.b64 {yp_my5,yp_my6}, yp_mo2;\n" \
        "\tmov.b64 {yp_my7,yp_my8}, yp_mo3;\n" \
        "\tmov.b64 {yp_my9,yp_my10}, yp_mo4;\n" \
        "\tmov.b64 {yp_my11,yp_my12}, yp_mo5;\n" \
        "\tmov.b64 {yp_my13,yp_my14}, yp_mo6;\n" \
        "\tadd.cc.u32 yp_mx1, yp_mx1, yp_my1;\n" \
        "\taddc.cc.u32 yp_mx2, yp_mx2, yp_my2;\n" \
        "\taddc.cc.u32 yp_mx3, yp_mx3, yp_my3;\n" \
        "\taddc.cc.u32 yp_mx4, yp_mx4, yp_my4;\n" \
        "\taddc.cc.u32 yp_mx5, yp_mx5, yp_my5;\n" \
        "\taddc.cc.u32 yp_mx6, yp_mx6, yp_my6;\n" \
        "\taddc.cc.u32 yp_mx7, yp_mx7, yp_my7;\n" \
        "\taddc.cc.u32 yp_mx8, yp_mx8, yp_my8;\n" \
        "\taddc.cc.u32 yp_mx9, yp_mx9, yp_my9;\n" \
        "\taddc.cc.u32 yp_mx10, yp_mx10, yp_my10;\n" \
        "\taddc.cc.u32 yp_mx11, yp_mx11, yp_my11;\n" \
        "\taddc.cc.u32 yp_mx12, yp_mx12, yp_my12;\n" \
        "\taddc.cc.u32 yp_mx13, yp_mx13, yp_my13;\n" \
        "\taddc.cc.u32 yp_mx14, yp_mx14, yp_my14;\n" \
        "\taddc.cc.u32 yp_mx15, yp_mx15, 0;\n" \
        "\taddc.u32 yp_mx16, yp_mx16, 0;\n" \
        "\tadd.cc.u32 yp_mx8, yp_mx8, yp_u8;\n" \
        "\taddc.cc.u32 yp_mx9, yp_mx9, yp_u9;\n" \
        "\taddc.cc.u32 yp_mx10, yp_mx10, yp_u10;\n" \
        "\taddc.cc.u32 yp_mx11, yp_mx11, yp_u11;\n" \
        "\taddc.cc.u32 yp_mx12, yp_mx12, yp_u12;\n" \
        "\taddc.cc.u32 yp_mx13, yp_mx13, yp_u13;\n" \
        "\taddc.cc.u32 yp_mx14, yp_mx14, yp_u14;\n" \
        "\taddc.cc.u32 yp_mx15, yp_mx15, yp_u15;\n" \
        "\taddc.u32 yp_mx16, yp_mx16, 0;\n" \
        "\t.reg .u64 yp_mr0,yp_mr1,yp_mr2,yp_mr3,yp_mh0,yp_mh1,yp_mh2,yp_mh3,yp_mf0,yp_mf1,yp_mf2,yp_mf3,yp_mg0,yp_mg1,yp_mg2,yp_mg3,yp_msfz,yp_msft;\n" \
        "\t.reg .u32 yp_mf8,yp_mg8,yp_mz0,yp_mz1,yp_mz2,yp_mz3,yp_mz4,yp_mz5,yp_mz6,yp_mz7,yp_mz8,yp_mz9,yp_mw0,yp_mw1,yp_mw2,yp_mw3,yp_mw4,yp_mw5,yp_mw6,yp_mw7,yp_mk16,yp_mk9,yp_msfq,yp_msfh,yp_msfc,yp_msfhi;\n" \
        "\tmul.lo.u32 yp_mk16, yp_mx16, 977;\n" \
        "\tmov.b64 yp_mr0, {yp_mx0,yp_mx1};\n" \
        "\tmov.b64 yp_mr1, {yp_mx2,yp_mx3};\n" \
        "\tmov.b64 yp_mr2, {yp_mx4,yp_mx5};\n" \
        "\tmov.b64 yp_mr3, {yp_mx6,yp_mx7};\n" \
        "\tmov.b64 yp_mh0, {yp_mx8,yp_mx9};\n" \
        "\tmov.b64 yp_mh1, {yp_mx10,yp_mx11};\n" \
        "\tmov.b64 yp_mh2, {yp_mx12,yp_mx13};\n" \
        "\tmov.b64 yp_mh3, {yp_mx14,yp_mx15};\n" \
        "\tmul.wide.u32 yp_mt, yp_mx9, 977; add.cc.u64 yp_mg0, yp_mh0, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx11, 977; addc.cc.u64 yp_mg1, yp_mh1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx13, 977; addc.cc.u64 yp_mg2, yp_mh2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx15, 977; addc.cc.u64 yp_mg3, yp_mh3, yp_mt;\n" \
        "\taddc.u32 yp_mg8, yp_mx16, 0;\n" \
        "\tmov.b64 {yp_mw0,yp_mw1}, yp_mg0;\n" \
        "\tmov.b64 {yp_mw2,yp_mw3}, yp_mg1;\n" \
        "\tmov.b64 {yp_mw4,yp_mw5}, yp_mg2;\n" \
        "\tmov.b64 {yp_mw6,yp_mw7}, yp_mg3;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx8, 977; add.cc.u64 yp_mf0, yp_mr0, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx10, 977; addc.cc.u64 yp_mf1, yp_mr1, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx12, 977; addc.cc.u64 yp_mf2, yp_mr2, yp_mt;\n" \
        "\tmul.wide.u32 yp_mt, yp_mx14, 977; addc.cc.u64 yp_mf3, yp_mr3, yp_mt;\n" \
        "\taddc.u32 yp_mf8, yp_mk16, 0;\n" \
        "\tmov.b64 {yp_mz0,yp_mz1}, yp_mf0;\n" \
        "\tmov.b64 {yp_mz2,yp_mz3}, yp_mf1;\n" \
        "\tmov.b64 {yp_mz4,yp_mz5}, yp_mf2;\n" \
        "\tmov.b64 {yp_mz6,yp_mz7}, yp_mf3;\n" \
        "\tadd.cc.u32 yp_mz1, yp_mz1, yp_mw0;\n" \
        "\taddc.cc.u32 yp_mz2, yp_mz2, yp_mw1;\n" \
        "\taddc.cc.u32 yp_mz3, yp_mz3, yp_mw2;\n" \
        "\taddc.cc.u32 yp_mz4, yp_mz4, yp_mw3;\n" \
        "\taddc.cc.u32 yp_mz5, yp_mz5, yp_mw4;\n" \
        "\taddc.cc.u32 yp_mz6, yp_mz6, yp_mw5;\n" \
        "\taddc.cc.u32 yp_mz7, yp_mz7, yp_mw6;\n" \
        "\taddc.cc.u32 yp_mz8, yp_mf8, yp_mw7;\n" \
        "\taddc.u32 yp_mz9, yp_mg8, 0;\n" \
        "\tmul.lo.u32 yp_mk9, yp_mz9, 977;\n" \
        "\tadd.cc.u32 yp_msfq, yp_mz8, yp_mk9;\n" \
        "\taddc.u32 yp_msfh, yp_mz9, 0;\n" \
        "\tmov.b64 yp_msfz, {yp_mz0, yp_msfq};\n" \
        "\tmul.wide.u32 yp_msft, yp_mz8, 977; add.cc.u64 yp_msft, yp_msft, yp_msfz;\n" \
        "\taddc.u32 yp_msfc, yp_msfh, 0;\n" \
        "\tmov.b64 {yp_mz0, yp_msfhi}, yp_msft;\n" \
        "\tadd.cc.u32 yp_mz1, yp_mz1, yp_msfhi;\n" \
        "\taddc.u32 yp_mz2, yp_mz2, yp_msfc;\n" \
        "\tmov.b64 R0, {yp_mz0,yp_mz1};\n" \
        "\tmov.b64 R1, {yp_mz2,yp_mz3};\n" \
        "\tmov.b64 R2, {yp_mz4,yp_mz5};\n" \
        "\tmov.b64 R3, {yp_mz6,yp_mz7};\n"
#endif

/* In-block, at the f15 site, after Q = X3 - V: no product; the pair (Q, R) goes out (RP <- R). */
#define QSB_YP_F15U \
        "\tmov.u64 RP0, R0;\n" \
        "\tmov.u64 RP1, R1;\n" \
        "\tmov.u64 RP2, R2;\n" \
        "\tmov.u64 RP3, R3;\n"

/* Last add: r = red(a*b + c*d). */
__device__ __forceinline__ void qsb_filter_fused16(uint64_t *r, const uint64_t *a, const uint64_t *b, const uint64_t *c, const uint64_t *d) {
#ifdef __CUDA_ARCH__
    uint64_t r0, r1, r2, r3;
    asm("{\n"
#if QSB_YP_FOLD_DROP & 2
        "\t.reg .u32 yf_ca0,yf_ca1,yf_ca2,yf_ca3,yf_ca4,yf_ca5,yf_ca6,yf_ca7,yf_cb0,yf_cb1,yf_cb2,yf_cb3,yf_cb4,yf_cb5,yf_cb6,yf_cb7;\n"
        "\t.reg .u64 yf_ce0,yf_ce1,yf_ce2,yf_ce3,yf_ce4,yf_ce5,yf_ce6,yf_ce7,yf_co0,yf_co1,yf_co2,yf_co3,yf_co4,yf_co5,yf_co6,yf_ct,yf_clc;\n"
        "\t.reg .u32 yf_ccy,yf_cec10,yf_cec12,yf_cec14,yf_co15;\n"
        "\t.reg .u32 yf_ma0,yf_ma1,yf_ma2,yf_ma3,yf_ma4,yf_ma5,yf_ma6,yf_ma7,yf_mb0,yf_mb1,yf_mb2,yf_mb3,yf_mb4,yf_mb5,yf_mb6,yf_mb7;\n"
        "\t.reg .u64 yf_me0,yf_me1,yf_me2,yf_me3,yf_me4,yf_me5,yf_me6,yf_me7,yf_mo0,yf_mo1,yf_mo2,yf_mo3,yf_mo4,yf_mo5,yf_mo6,yf_mt,yf_mlc;\n"
        "\t.reg .u32 yf_mcy,yf_mec10,yf_mec12,yf_mec14,yf_mx0,yf_mx1,yf_mx2,yf_mx3,yf_mx4,yf_mx5,yf_mx6,yf_mx7,yf_mx8,yf_mx9,yf_mx10,yf_mx11,yf_mx12,yf_mx13,yf_mx14,yf_mx15,yf_mx16,yf_my1,yf_my2,yf_my3,yf_my4,yf_my5,yf_my6,yf_my7,yf_my8,yf_my9,yf_my10,yf_my11,yf_my12,yf_my13,yf_my14,yf_mobc,yf_u8,yf_u9,yf_u10,yf_u11,yf_u12,yf_u13,yf_u14,yf_u15,yf_u16,yf_v9,yf_v10,yf_v11,yf_v12,yf_v13,yf_v14;\n"
        "\tmov.b64 {yf_ca0,yf_ca1}, %12;\n"
        "\tmov.b64 {yf_ca2,yf_ca3}, %13;\n"
        "\tmov.b64 {yf_ca4,yf_ca5}, %14;\n"
        "\tmov.b64 {yf_ca6,yf_ca7}, %15;\n"
        "\tmov.b64 {yf_cb0,yf_cb1}, %16;\n"
        "\tmov.b64 {yf_cb2,yf_cb3}, %17;\n"
        "\tmov.b64 {yf_cb4,yf_cb5}, %18;\n"
        "\tmov.b64 {yf_cb6,yf_cb7}, %19;\n"
        "\tmul.wide.u32 yf_ce0, yf_ca0, yf_cb0; mul.wide.u32 yf_ce1, yf_ca0, yf_cb2; mul.wide.u32 yf_ce2, yf_ca0, yf_cb4; mul.wide.u32 yf_ce3, yf_ca0, yf_cb6;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb1; add.cc.u64 yf_ce1, yf_ce1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb3; addc.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb5; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb7; addc.u64 yf_ce4, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb0; add.cc.u64 yf_ce1, yf_ce1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb2; addc.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb4; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb6; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\taddc.u32 yf_cec10, 0, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb1; add.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb3; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb5; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb7; addc.u64 yf_ce5, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb0; add.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb2; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb4; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb6; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\taddc.u32 yf_cec12, 0, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb1; add.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb3; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb5; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb7; addc.u64 yf_ce6, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb0; add.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb2; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb4; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb6; addc.cc.u64 yf_ce6, yf_ce6, yf_ct;\n"
        "\taddc.u32 yf_cec14, 0, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb1; add.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb3; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb5; addc.cc.u64 yf_ce6, yf_ce6, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb7; addc.u64 yf_ce7, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_co0, yf_ca0, yf_cb1; mul.wide.u32 yf_co1, yf_ca0, yf_cb3; mul.wide.u32 yf_co2, yf_ca0, yf_cb5; mul.wide.u32 yf_co3, yf_ca0, yf_cb7;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb0; add.cc.u64 yf_co0, yf_co0, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb2; addc.cc.u64 yf_co1, yf_co1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb4; addc.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb6; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\taddc.u32 yf_ccy, 0, 0;\n"
        "\tmov.b64 yf_clc, {yf_ccy, yf_cec10};\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb1; add.cc.u64 yf_co1, yf_co1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb3; addc.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb5; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb7; addc.u64 yf_co4, yf_ct, yf_clc;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb0; add.cc.u64 yf_co1, yf_co1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb2; addc.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb4; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb6; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\taddc.u32 yf_ccy, 0, 0;\n"
        "\tmov.b64 yf_clc, {yf_ccy, yf_cec12};\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb1; add.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb3; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb5; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb7; addc.u64 yf_co5, yf_ct, yf_clc;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb0; add.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb2; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb4; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb6; addc.cc.u64 yf_co5, yf_co5, yf_ct;\n"
        "\taddc.u32 yf_ccy, 0, 0;\n"
        "\tmov.b64 yf_clc, {yf_ccy, yf_cec14};\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb1; add.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb3; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb5; addc.cc.u64 yf_co5, yf_co5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb7; addc.u64 yf_co6, yf_ct, yf_clc;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb0; add.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb2; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb4; addc.cc.u64 yf_co5, yf_co5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb6; addc.cc.u64 yf_co6, yf_co6, yf_ct;\n"
        "\taddc.u32 yf_co15, 0, 0;\n"
        "\tmov.b64 {yf_u8,yf_u9}, yf_ce4;\n"
        "\tmov.b64 {yf_u10,yf_u11}, yf_ce5;\n"
        "\tmov.b64 {yf_u12,yf_u13}, yf_ce6;\n"
        "\tmov.b64 {yf_u14,yf_u15}, yf_ce7;\n"
        "\tmov.b64 {yf_v9,yf_v10}, yf_co4;\n"
        "\tmov.b64 {yf_v11,yf_v12}, yf_co5;\n"
        "\tmov.b64 {yf_v13,yf_v14}, yf_co6;\n"
        "\tmov.b64 {yf_ma0,yf_ma1}, %4;\n"
        "\tmov.b64 {yf_ma2,yf_ma3}, %5;\n"
        "\tmov.b64 {yf_ma4,yf_ma5}, %6;\n"
        "\tmov.b64 {yf_ma6,yf_ma7}, %7;\n"
        "\tmov.b64 {yf_mb0,yf_mb1}, %8;\n"
        "\tmov.b64 {yf_mb2,yf_mb3}, %9;\n"
        "\tmov.b64 {yf_mb4,yf_mb5}, %10;\n"
        "\tmov.b64 {yf_mb6,yf_mb7}, %11;\n"
        "\tmul.wide.u32 yf_me0, yf_ma0, yf_mb0; mul.wide.u32 yf_me1, yf_ma0, yf_mb2; mul.wide.u32 yf_me2, yf_ma0, yf_mb4; mul.wide.u32 yf_me3, yf_ma0, yf_mb6;\n"
        "\tadd.cc.u64 yf_me0, yf_me0, yf_ce0;\n"
        "\taddc.cc.u64 yf_me1, yf_me1, yf_ce1;\n"
        "\taddc.cc.u64 yf_me2, yf_me2, yf_ce2;\n"
        "\taddc.cc.u64 yf_me3, yf_me3, yf_ce3;\n"
        "\taddc.cc.u32 yf_u8, yf_u8, 0;\n"
        "\taddc.cc.u32 yf_u9, yf_u9, yf_v9;\n"
        "\taddc.cc.u32 yf_u10, yf_u10, yf_v10;\n"
        "\taddc.cc.u32 yf_u11, yf_u11, yf_v11;\n"
        "\taddc.cc.u32 yf_u12, yf_u12, yf_v12;\n"
        "\taddc.cc.u32 yf_u13, yf_u13, yf_v13;\n"
        "\taddc.cc.u32 yf_u14, yf_u14, yf_v14;\n"
        "\taddc.cc.u32 yf_u15, yf_u15, yf_co15;\n"
        "\taddc.u32 yf_u16, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb1; add.cc.u64 yf_me1, yf_me1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb3; addc.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb5; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb7; addc.u64 yf_me4, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb0; add.cc.u64 yf_me1, yf_me1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb2; addc.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb4; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb6; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\taddc.u32 yf_mec10, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb1; add.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb3; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb5; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb7; addc.u64 yf_me5, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb0; add.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb2; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb4; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb6; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\taddc.u32 yf_mec12, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb1; add.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb3; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb5; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb7; addc.u64 yf_me6, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb0; add.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb2; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb4; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb6; addc.cc.u64 yf_me6, yf_me6, yf_mt;\n"
        "\taddc.u32 yf_mec14, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb1; add.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb3; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb5; addc.cc.u64 yf_me6, yf_me6, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb7; addc.u64 yf_me7, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mo0, yf_ma0, yf_mb1; mul.wide.u32 yf_mo1, yf_ma0, yf_mb3; mul.wide.u32 yf_mo2, yf_ma0, yf_mb5; mul.wide.u32 yf_mo3, yf_ma0, yf_mb7;\n"
        "\tadd.cc.u64 yf_mo0, yf_mo0, yf_co0;\n"
        "\taddc.cc.u64 yf_mo1, yf_mo1, yf_co1;\n"
        "\taddc.cc.u64 yf_mo2, yf_mo2, yf_co2;\n"
        "\taddc.cc.u64 yf_mo3, yf_mo3, yf_co3;\n"
        "\taddc.u32 yf_mobc, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb0; add.cc.u64 yf_mo0, yf_mo0, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb2; addc.cc.u64 yf_mo1, yf_mo1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb4; addc.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb6; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\taddc.u32 yf_mcy, 0, 0;\n"
        "\tadd.u32 yf_mcy, yf_mcy, yf_mobc;\n"
        "\tmov.b64 yf_mlc, {yf_mcy, yf_mec10};\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb1; add.cc.u64 yf_mo1, yf_mo1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb3; addc.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb5; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb7; addc.u64 yf_mo4, yf_mt, yf_mlc;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb0; add.cc.u64 yf_mo1, yf_mo1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb2; addc.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb4; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb6; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\taddc.u32 yf_mcy, 0, 0;\n"
        "\tmov.b64 yf_mlc, {yf_mcy, yf_mec12};\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb1; add.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb3; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb5; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb7; addc.u64 yf_mo5, yf_mt, yf_mlc;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb0; add.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb2; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb4; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb6; addc.cc.u64 yf_mo5, yf_mo5, yf_mt;\n"
        "\taddc.u32 yf_mcy, 0, 0;\n"
        "\tmov.b64 yf_mlc, {yf_mcy, yf_mec14};\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb1; add.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb3; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb5; addc.cc.u64 yf_mo5, yf_mo5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb7; addc.u64 yf_mo6, yf_mt, yf_mlc;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb0; add.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb2; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb4; addc.cc.u64 yf_mo5, yf_mo5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb6; addc.cc.u64 yf_mo6, yf_mo6, yf_mt;\n"
        "\tmov.b64 {yf_mx14,yf_mx15}, yf_me7;\n"
        "\taddc.cc.u32 yf_mx15, yf_mx15, 0;\n"
        "\taddc.u32 yf_mx16, yf_u16, 0;\n"
        "\tmov.b64 {yf_mx0,yf_mx1}, yf_me0;\n"
        "\tmov.b64 {yf_mx2,yf_mx3}, yf_me1;\n"
        "\tmov.b64 {yf_mx4,yf_mx5}, yf_me2;\n"
        "\tmov.b64 {yf_mx6,yf_mx7}, yf_me3;\n"
        "\tmov.b64 {yf_mx8,yf_mx9}, yf_me4;\n"
        "\tmov.b64 {yf_mx10,yf_mx11}, yf_me5;\n"
        "\tmov.b64 {yf_mx12,yf_mx13}, yf_me6;\n"
        "\tmov.b64 {yf_my1,yf_my2}, yf_mo0;\n"
        "\tmov.b64 {yf_my3,yf_my4}, yf_mo1;\n"
        "\tmov.b64 {yf_my5,yf_my6}, yf_mo2;\n"
        "\tmov.b64 {yf_my7,yf_my8}, yf_mo3;\n"
        "\tmov.b64 {yf_my9,yf_my10}, yf_mo4;\n"
        "\tmov.b64 {yf_my11,yf_my12}, yf_mo5;\n"
        "\tmov.b64 {yf_my13,yf_my14}, yf_mo6;\n"
        "\tadd.cc.u32 yf_mx1, yf_mx1, yf_my1;\n"
        "\taddc.cc.u32 yf_mx2, yf_mx2, yf_my2;\n"
        "\taddc.cc.u32 yf_mx3, yf_mx3, yf_my3;\n"
        "\taddc.cc.u32 yf_mx4, yf_mx4, yf_my4;\n"
        "\taddc.cc.u32 yf_mx5, yf_mx5, yf_my5;\n"
        "\taddc.cc.u32 yf_mx6, yf_mx6, yf_my6;\n"
        "\taddc.cc.u32 yf_mx7, yf_mx7, yf_my7;\n"
        "\taddc.cc.u32 yf_mx8, yf_mx8, yf_my8;\n"
        "\taddc.cc.u32 yf_mx9, yf_mx9, yf_my9;\n"
        "\taddc.cc.u32 yf_mx10, yf_mx10, yf_my10;\n"
        "\taddc.cc.u32 yf_mx11, yf_mx11, yf_my11;\n"
        "\taddc.cc.u32 yf_mx12, yf_mx12, yf_my12;\n"
        "\taddc.cc.u32 yf_mx13, yf_mx13, yf_my13;\n"
        "\taddc.cc.u32 yf_mx14, yf_mx14, yf_my14;\n"
        "\taddc.cc.u32 yf_mx15, yf_mx15, 0;\n"
        "\taddc.u32 yf_mx16, yf_mx16, 0;\n"
        "\tadd.cc.u32 yf_mx8, yf_mx8, yf_u8;\n"
        "\taddc.cc.u32 yf_mx9, yf_mx9, yf_u9;\n"
        "\taddc.cc.u32 yf_mx10, yf_mx10, yf_u10;\n"
        "\taddc.cc.u32 yf_mx11, yf_mx11, yf_u11;\n"
        "\taddc.cc.u32 yf_mx12, yf_mx12, yf_u12;\n"
        "\taddc.cc.u32 yf_mx13, yf_mx13, yf_u13;\n"
        "\taddc.cc.u32 yf_mx14, yf_mx14, yf_u14;\n"
        "\taddc.cc.u32 yf_mx15, yf_mx15, yf_u15;\n"
        "\taddc.u32 yf_mx16, yf_mx16, 0;\n"
        "\t.reg .u64 yf_mr0,yf_mr1,yf_mr2,yf_mr3,yf_mh0,yf_mh1,yf_mh2,yf_mh3,yf_mf0,yf_mf1,yf_mf2,yf_mf3,yf_mg0,yf_mg1,yf_mg2,yf_mg3,yf_msfz,yf_msft;\n"
        "\t.reg .u32 yf_mz0,yf_mz1,yf_mz2,yf_mz3,yf_mz4,yf_mz5,yf_mz6,yf_mz7,yf_mz8,yf_mz9,yf_mw0,yf_mw1,yf_mw2,yf_mw3,yf_mw4,yf_mw5,yf_mw6,yf_mw7,yf_mk16,yf_mk9,yf_msfq,yf_msfh,yf_msfc,yf_msfhi;\n"
        "\tmul.lo.u32 yf_mk16, yf_mx16, 977;\n"
        "\tmov.b64 yf_mr0, {yf_mx0,yf_mx1};\n"
        "\tmov.b64 yf_mr1, {yf_mx2,yf_mx3};\n"
        "\tmov.b64 yf_mr2, {yf_mx4,yf_mx5};\n"
        "\tmov.b64 yf_mr3, {yf_mx6,yf_mx7};\n"
        "\tmov.b64 yf_mh0, {yf_mx8,yf_mx9};\n"
        "\tmov.b64 yf_mh1, {yf_mx10,yf_mx11};\n"
        "\tmov.b64 yf_mh2, {yf_mx12,yf_mx13};\n"
        "\tmov.b64 yf_mh3, {yf_mx14,yf_mx15};\n"
        "\tmul.wide.u32 yf_mt, yf_mx9, 977; add.cc.u64 yf_mg0, yf_mh0, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx11, 977; addc.cc.u64 yf_mg1, yf_mh1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx13, 977; addc.cc.u64 yf_mg2, yf_mh2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx15, 977; addc.u64 yf_mg3, yf_mh3, yf_mt;\n"
        "\tmov.b64 {yf_mw0,yf_mw1}, yf_mg0;\n"
        "\tmov.b64 {yf_mw2,yf_mw3}, yf_mg1;\n"
        "\tmov.b64 {yf_mw4,yf_mw5}, yf_mg2;\n"
        "\tmov.b64 {yf_mw6,yf_mw7}, yf_mg3;\n"
        "\tmul.wide.u32 yf_mt, yf_mx8, 977; add.cc.u64 yf_mf0, yf_mr0, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx10, 977; addc.cc.u64 yf_mf1, yf_mr1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx12, 977; addc.cc.u64 yf_mf2, yf_mr2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx14, 977; addc.u64 yf_mf3, yf_mr3, yf_mt;\n"
        "\tmov.b64 {yf_mz0,yf_mz1}, yf_mf0;\n"
        "\tmov.b64 {yf_mz2,yf_mz3}, yf_mf1;\n"
        "\tmov.b64 {yf_mz4,yf_mz5}, yf_mf2;\n"
        "\tmov.b64 {yf_mz6,yf_mz7}, yf_mf3;\n"
        "\tadd.cc.u32 yf_mz1, yf_mz1, yf_mw0;\n"
        "\taddc.cc.u32 yf_mz2, yf_mz2, yf_mw1;\n"
        "\taddc.cc.u32 yf_mz3, yf_mz3, yf_mw2;\n"
        "\taddc.cc.u32 yf_mz4, yf_mz4, yf_mw3;\n"
        "\taddc.cc.u32 yf_mz5, yf_mz5, yf_mw4;\n"
        "\taddc.cc.u32 yf_mz6, yf_mz6, yf_mw5;\n"
        "\taddc.cc.u32 yf_mz7, yf_mz7, yf_mw6;\n"
        "\taddc.cc.u32 yf_mz8, yf_mk16, yf_mw7;\n"
        "\taddc.u32 yf_mz9, yf_mx16, 0;\n"
        "\tmul.lo.u32 yf_mk9, yf_mz9, 977;\n"
        "\tadd.cc.u32 yf_msfq, yf_mz8, yf_mk9;\n"
        "\taddc.u32 yf_msfh, yf_mz9, 0;\n"
        "\tmov.b64 yf_msfz, {yf_mz0, yf_msfq};\n"
        "\tmul.wide.u32 yf_msft, yf_mz8, 977; add.cc.u64 yf_msft, yf_msft, yf_msfz;\n"
        "\taddc.u32 yf_msfc, yf_msfh, 0;\n"
        "\tmov.b64 {yf_mz0, yf_msfhi}, yf_msft;\n"
        "\tadd.cc.u32 yf_mz1, yf_mz1, yf_msfhi;\n"
        "\taddc.u32 yf_mz2, yf_mz2, yf_msfc;\n"
        "\tmov.b64 %0, {yf_mz0,yf_mz1};\n"
        "\tmov.b64 %1, {yf_mz2,yf_mz3};\n"
        "\tmov.b64 %2, {yf_mz4,yf_mz5};\n"
        "\tmov.b64 %3, {yf_mz6,yf_mz7};\n"
#else
        "\t.reg .u32 yf_ca0,yf_ca1,yf_ca2,yf_ca3,yf_ca4,yf_ca5,yf_ca6,yf_ca7,yf_cb0,yf_cb1,yf_cb2,yf_cb3,yf_cb4,yf_cb5,yf_cb6,yf_cb7;\n"
        "\t.reg .u64 yf_ce0,yf_ce1,yf_ce2,yf_ce3,yf_ce4,yf_ce5,yf_ce6,yf_ce7,yf_co0,yf_co1,yf_co2,yf_co3,yf_co4,yf_co5,yf_co6,yf_ct,yf_clc;\n"
        "\t.reg .u32 yf_ccy,yf_cec10,yf_cec12,yf_cec14,yf_co15;\n"
        "\t.reg .u32 yf_ma0,yf_ma1,yf_ma2,yf_ma3,yf_ma4,yf_ma5,yf_ma6,yf_ma7,yf_mb0,yf_mb1,yf_mb2,yf_mb3,yf_mb4,yf_mb5,yf_mb6,yf_mb7;\n"
        "\t.reg .u64 yf_me0,yf_me1,yf_me2,yf_me3,yf_me4,yf_me5,yf_me6,yf_me7,yf_mo0,yf_mo1,yf_mo2,yf_mo3,yf_mo4,yf_mo5,yf_mo6,yf_mt,yf_mlc;\n"
        "\t.reg .u32 yf_mcy,yf_mec10,yf_mec12,yf_mec14,yf_mx0,yf_mx1,yf_mx2,yf_mx3,yf_mx4,yf_mx5,yf_mx6,yf_mx7,yf_mx8,yf_mx9,yf_mx10,yf_mx11,yf_mx12,yf_mx13,yf_mx14,yf_mx15,yf_mx16,yf_my1,yf_my2,yf_my3,yf_my4,yf_my5,yf_my6,yf_my7,yf_my8,yf_my9,yf_my10,yf_my11,yf_my12,yf_my13,yf_my14,yf_mobc,yf_u8,yf_u9,yf_u10,yf_u11,yf_u12,yf_u13,yf_u14,yf_u15,yf_u16,yf_v9,yf_v10,yf_v11,yf_v12,yf_v13,yf_v14;\n"
        "\tmov.b64 {yf_ca0,yf_ca1}, %12;\n"
        "\tmov.b64 {yf_ca2,yf_ca3}, %13;\n"
        "\tmov.b64 {yf_ca4,yf_ca5}, %14;\n"
        "\tmov.b64 {yf_ca6,yf_ca7}, %15;\n"
        "\tmov.b64 {yf_cb0,yf_cb1}, %16;\n"
        "\tmov.b64 {yf_cb2,yf_cb3}, %17;\n"
        "\tmov.b64 {yf_cb4,yf_cb5}, %18;\n"
        "\tmov.b64 {yf_cb6,yf_cb7}, %19;\n"
        "\tmul.wide.u32 yf_ce0, yf_ca0, yf_cb0; mul.wide.u32 yf_ce1, yf_ca0, yf_cb2; mul.wide.u32 yf_ce2, yf_ca0, yf_cb4; mul.wide.u32 yf_ce3, yf_ca0, yf_cb6;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb1; add.cc.u64 yf_ce1, yf_ce1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb3; addc.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb5; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb7; addc.u64 yf_ce4, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb0; add.cc.u64 yf_ce1, yf_ce1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb2; addc.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb4; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb6; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\taddc.u32 yf_cec10, 0, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb1; add.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb3; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb5; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb7; addc.u64 yf_ce5, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb0; add.cc.u64 yf_ce2, yf_ce2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb2; addc.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb4; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb6; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\taddc.u32 yf_cec12, 0, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb1; add.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb3; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb5; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb7; addc.u64 yf_ce6, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb0; add.cc.u64 yf_ce3, yf_ce3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb2; addc.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb4; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb6; addc.cc.u64 yf_ce6, yf_ce6, yf_ct;\n"
        "\taddc.u32 yf_cec14, 0, 0;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb1; add.cc.u64 yf_ce4, yf_ce4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb3; addc.cc.u64 yf_ce5, yf_ce5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb5; addc.cc.u64 yf_ce6, yf_ce6, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb7; addc.u64 yf_ce7, yf_ct, 0;\n"
        "\tmul.wide.u32 yf_co0, yf_ca0, yf_cb1; mul.wide.u32 yf_co1, yf_ca0, yf_cb3; mul.wide.u32 yf_co2, yf_ca0, yf_cb5; mul.wide.u32 yf_co3, yf_ca0, yf_cb7;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb0; add.cc.u64 yf_co0, yf_co0, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb2; addc.cc.u64 yf_co1, yf_co1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb4; addc.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca1, yf_cb6; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\taddc.u32 yf_ccy, 0, 0;\n"
        "\tmov.b64 yf_clc, {yf_ccy, yf_cec10};\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb1; add.cc.u64 yf_co1, yf_co1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb3; addc.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb5; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca2, yf_cb7; addc.u64 yf_co4, yf_ct, yf_clc;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb0; add.cc.u64 yf_co1, yf_co1, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb2; addc.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb4; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca3, yf_cb6; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\taddc.u32 yf_ccy, 0, 0;\n"
        "\tmov.b64 yf_clc, {yf_ccy, yf_cec12};\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb1; add.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb3; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb5; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca4, yf_cb7; addc.u64 yf_co5, yf_ct, yf_clc;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb0; add.cc.u64 yf_co2, yf_co2, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb2; addc.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb4; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca5, yf_cb6; addc.cc.u64 yf_co5, yf_co5, yf_ct;\n"
        "\taddc.u32 yf_ccy, 0, 0;\n"
        "\tmov.b64 yf_clc, {yf_ccy, yf_cec14};\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb1; add.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb3; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb5; addc.cc.u64 yf_co5, yf_co5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca6, yf_cb7; addc.u64 yf_co6, yf_ct, yf_clc;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb0; add.cc.u64 yf_co3, yf_co3, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb2; addc.cc.u64 yf_co4, yf_co4, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb4; addc.cc.u64 yf_co5, yf_co5, yf_ct;\n"
        "\tmul.wide.u32 yf_ct, yf_ca7, yf_cb6; addc.cc.u64 yf_co6, yf_co6, yf_ct;\n"
        "\taddc.u32 yf_co15, 0, 0;\n"
        "\tmov.b64 {yf_u8,yf_u9}, yf_ce4;\n"
        "\tmov.b64 {yf_u10,yf_u11}, yf_ce5;\n"
        "\tmov.b64 {yf_u12,yf_u13}, yf_ce6;\n"
        "\tmov.b64 {yf_u14,yf_u15}, yf_ce7;\n"
        "\tmov.b64 {yf_v9,yf_v10}, yf_co4;\n"
        "\tmov.b64 {yf_v11,yf_v12}, yf_co5;\n"
        "\tmov.b64 {yf_v13,yf_v14}, yf_co6;\n"
        "\tmov.b64 {yf_ma0,yf_ma1}, %4;\n"
        "\tmov.b64 {yf_ma2,yf_ma3}, %5;\n"
        "\tmov.b64 {yf_ma4,yf_ma5}, %6;\n"
        "\tmov.b64 {yf_ma6,yf_ma7}, %7;\n"
        "\tmov.b64 {yf_mb0,yf_mb1}, %8;\n"
        "\tmov.b64 {yf_mb2,yf_mb3}, %9;\n"
        "\tmov.b64 {yf_mb4,yf_mb5}, %10;\n"
        "\tmov.b64 {yf_mb6,yf_mb7}, %11;\n"
        "\tmul.wide.u32 yf_me0, yf_ma0, yf_mb0; mul.wide.u32 yf_me1, yf_ma0, yf_mb2; mul.wide.u32 yf_me2, yf_ma0, yf_mb4; mul.wide.u32 yf_me3, yf_ma0, yf_mb6;\n"
        "\tadd.cc.u64 yf_me0, yf_me0, yf_ce0;\n"
        "\taddc.cc.u64 yf_me1, yf_me1, yf_ce1;\n"
        "\taddc.cc.u64 yf_me2, yf_me2, yf_ce2;\n"
        "\taddc.cc.u64 yf_me3, yf_me3, yf_ce3;\n"
        "\taddc.cc.u32 yf_u8, yf_u8, 0;\n"
        "\taddc.cc.u32 yf_u9, yf_u9, yf_v9;\n"
        "\taddc.cc.u32 yf_u10, yf_u10, yf_v10;\n"
        "\taddc.cc.u32 yf_u11, yf_u11, yf_v11;\n"
        "\taddc.cc.u32 yf_u12, yf_u12, yf_v12;\n"
        "\taddc.cc.u32 yf_u13, yf_u13, yf_v13;\n"
        "\taddc.cc.u32 yf_u14, yf_u14, yf_v14;\n"
        "\taddc.cc.u32 yf_u15, yf_u15, yf_co15;\n"
        "\taddc.u32 yf_u16, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb1; add.cc.u64 yf_me1, yf_me1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb3; addc.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb5; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb7; addc.u64 yf_me4, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb0; add.cc.u64 yf_me1, yf_me1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb2; addc.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb4; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb6; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\taddc.u32 yf_mec10, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb1; add.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb3; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb5; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb7; addc.u64 yf_me5, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb0; add.cc.u64 yf_me2, yf_me2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb2; addc.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb4; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb6; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\taddc.u32 yf_mec12, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb1; add.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb3; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb5; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb7; addc.u64 yf_me6, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb0; add.cc.u64 yf_me3, yf_me3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb2; addc.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb4; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb6; addc.cc.u64 yf_me6, yf_me6, yf_mt;\n"
        "\taddc.u32 yf_mec14, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb1; add.cc.u64 yf_me4, yf_me4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb3; addc.cc.u64 yf_me5, yf_me5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb5; addc.cc.u64 yf_me6, yf_me6, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb7; addc.u64 yf_me7, yf_mt, 0;\n"
        "\tmul.wide.u32 yf_mo0, yf_ma0, yf_mb1; mul.wide.u32 yf_mo1, yf_ma0, yf_mb3; mul.wide.u32 yf_mo2, yf_ma0, yf_mb5; mul.wide.u32 yf_mo3, yf_ma0, yf_mb7;\n"
        "\tadd.cc.u64 yf_mo0, yf_mo0, yf_co0;\n"
        "\taddc.cc.u64 yf_mo1, yf_mo1, yf_co1;\n"
        "\taddc.cc.u64 yf_mo2, yf_mo2, yf_co2;\n"
        "\taddc.cc.u64 yf_mo3, yf_mo3, yf_co3;\n"
        "\taddc.u32 yf_mobc, 0, 0;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb0; add.cc.u64 yf_mo0, yf_mo0, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb2; addc.cc.u64 yf_mo1, yf_mo1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb4; addc.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma1, yf_mb6; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\taddc.u32 yf_mcy, 0, 0;\n"
        "\tadd.u32 yf_mcy, yf_mcy, yf_mobc;\n"
        "\tmov.b64 yf_mlc, {yf_mcy, yf_mec10};\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb1; add.cc.u64 yf_mo1, yf_mo1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb3; addc.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb5; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma2, yf_mb7; addc.u64 yf_mo4, yf_mt, yf_mlc;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb0; add.cc.u64 yf_mo1, yf_mo1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb2; addc.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb4; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma3, yf_mb6; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\taddc.u32 yf_mcy, 0, 0;\n"
        "\tmov.b64 yf_mlc, {yf_mcy, yf_mec12};\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb1; add.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb3; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb5; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma4, yf_mb7; addc.u64 yf_mo5, yf_mt, yf_mlc;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb0; add.cc.u64 yf_mo2, yf_mo2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb2; addc.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb4; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma5, yf_mb6; addc.cc.u64 yf_mo5, yf_mo5, yf_mt;\n"
        "\taddc.u32 yf_mcy, 0, 0;\n"
        "\tmov.b64 yf_mlc, {yf_mcy, yf_mec14};\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb1; add.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb3; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb5; addc.cc.u64 yf_mo5, yf_mo5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma6, yf_mb7; addc.u64 yf_mo6, yf_mt, yf_mlc;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb0; add.cc.u64 yf_mo3, yf_mo3, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb2; addc.cc.u64 yf_mo4, yf_mo4, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb4; addc.cc.u64 yf_mo5, yf_mo5, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_ma7, yf_mb6; addc.cc.u64 yf_mo6, yf_mo6, yf_mt;\n"
        "\tmov.b64 {yf_mx14,yf_mx15}, yf_me7;\n"
        "\taddc.cc.u32 yf_mx15, yf_mx15, 0;\n"
        "\taddc.u32 yf_mx16, yf_u16, 0;\n"
        "\tmov.b64 {yf_mx0,yf_mx1}, yf_me0;\n"
        "\tmov.b64 {yf_mx2,yf_mx3}, yf_me1;\n"
        "\tmov.b64 {yf_mx4,yf_mx5}, yf_me2;\n"
        "\tmov.b64 {yf_mx6,yf_mx7}, yf_me3;\n"
        "\tmov.b64 {yf_mx8,yf_mx9}, yf_me4;\n"
        "\tmov.b64 {yf_mx10,yf_mx11}, yf_me5;\n"
        "\tmov.b64 {yf_mx12,yf_mx13}, yf_me6;\n"
        "\tmov.b64 {yf_my1,yf_my2}, yf_mo0;\n"
        "\tmov.b64 {yf_my3,yf_my4}, yf_mo1;\n"
        "\tmov.b64 {yf_my5,yf_my6}, yf_mo2;\n"
        "\tmov.b64 {yf_my7,yf_my8}, yf_mo3;\n"
        "\tmov.b64 {yf_my9,yf_my10}, yf_mo4;\n"
        "\tmov.b64 {yf_my11,yf_my12}, yf_mo5;\n"
        "\tmov.b64 {yf_my13,yf_my14}, yf_mo6;\n"
        "\tadd.cc.u32 yf_mx1, yf_mx1, yf_my1;\n"
        "\taddc.cc.u32 yf_mx2, yf_mx2, yf_my2;\n"
        "\taddc.cc.u32 yf_mx3, yf_mx3, yf_my3;\n"
        "\taddc.cc.u32 yf_mx4, yf_mx4, yf_my4;\n"
        "\taddc.cc.u32 yf_mx5, yf_mx5, yf_my5;\n"
        "\taddc.cc.u32 yf_mx6, yf_mx6, yf_my6;\n"
        "\taddc.cc.u32 yf_mx7, yf_mx7, yf_my7;\n"
        "\taddc.cc.u32 yf_mx8, yf_mx8, yf_my8;\n"
        "\taddc.cc.u32 yf_mx9, yf_mx9, yf_my9;\n"
        "\taddc.cc.u32 yf_mx10, yf_mx10, yf_my10;\n"
        "\taddc.cc.u32 yf_mx11, yf_mx11, yf_my11;\n"
        "\taddc.cc.u32 yf_mx12, yf_mx12, yf_my12;\n"
        "\taddc.cc.u32 yf_mx13, yf_mx13, yf_my13;\n"
        "\taddc.cc.u32 yf_mx14, yf_mx14, yf_my14;\n"
        "\taddc.cc.u32 yf_mx15, yf_mx15, 0;\n"
        "\taddc.u32 yf_mx16, yf_mx16, 0;\n"
        "\tadd.cc.u32 yf_mx8, yf_mx8, yf_u8;\n"
        "\taddc.cc.u32 yf_mx9, yf_mx9, yf_u9;\n"
        "\taddc.cc.u32 yf_mx10, yf_mx10, yf_u10;\n"
        "\taddc.cc.u32 yf_mx11, yf_mx11, yf_u11;\n"
        "\taddc.cc.u32 yf_mx12, yf_mx12, yf_u12;\n"
        "\taddc.cc.u32 yf_mx13, yf_mx13, yf_u13;\n"
        "\taddc.cc.u32 yf_mx14, yf_mx14, yf_u14;\n"
        "\taddc.cc.u32 yf_mx15, yf_mx15, yf_u15;\n"
        "\taddc.u32 yf_mx16, yf_mx16, 0;\n"
        "\t.reg .u64 yf_mr0,yf_mr1,yf_mr2,yf_mr3,yf_mh0,yf_mh1,yf_mh2,yf_mh3,yf_mf0,yf_mf1,yf_mf2,yf_mf3,yf_mg0,yf_mg1,yf_mg2,yf_mg3,yf_msfz,yf_msft;\n"
        "\t.reg .u32 yf_mf8,yf_mg8,yf_mz0,yf_mz1,yf_mz2,yf_mz3,yf_mz4,yf_mz5,yf_mz6,yf_mz7,yf_mz8,yf_mz9,yf_mw0,yf_mw1,yf_mw2,yf_mw3,yf_mw4,yf_mw5,yf_mw6,yf_mw7,yf_mk16,yf_mk9,yf_msfq,yf_msfh,yf_msfc,yf_msfhi;\n"
        "\tmul.lo.u32 yf_mk16, yf_mx16, 977;\n"
        "\tmov.b64 yf_mr0, {yf_mx0,yf_mx1};\n"
        "\tmov.b64 yf_mr1, {yf_mx2,yf_mx3};\n"
        "\tmov.b64 yf_mr2, {yf_mx4,yf_mx5};\n"
        "\tmov.b64 yf_mr3, {yf_mx6,yf_mx7};\n"
        "\tmov.b64 yf_mh0, {yf_mx8,yf_mx9};\n"
        "\tmov.b64 yf_mh1, {yf_mx10,yf_mx11};\n"
        "\tmov.b64 yf_mh2, {yf_mx12,yf_mx13};\n"
        "\tmov.b64 yf_mh3, {yf_mx14,yf_mx15};\n"
        "\tmul.wide.u32 yf_mt, yf_mx9, 977; add.cc.u64 yf_mg0, yf_mh0, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx11, 977; addc.cc.u64 yf_mg1, yf_mh1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx13, 977; addc.cc.u64 yf_mg2, yf_mh2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx15, 977; addc.cc.u64 yf_mg3, yf_mh3, yf_mt;\n"
        "\taddc.u32 yf_mg8, yf_mx16, 0;\n"
        "\tmov.b64 {yf_mw0,yf_mw1}, yf_mg0;\n"
        "\tmov.b64 {yf_mw2,yf_mw3}, yf_mg1;\n"
        "\tmov.b64 {yf_mw4,yf_mw5}, yf_mg2;\n"
        "\tmov.b64 {yf_mw6,yf_mw7}, yf_mg3;\n"
        "\tmul.wide.u32 yf_mt, yf_mx8, 977; add.cc.u64 yf_mf0, yf_mr0, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx10, 977; addc.cc.u64 yf_mf1, yf_mr1, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx12, 977; addc.cc.u64 yf_mf2, yf_mr2, yf_mt;\n"
        "\tmul.wide.u32 yf_mt, yf_mx14, 977; addc.cc.u64 yf_mf3, yf_mr3, yf_mt;\n"
        "\taddc.u32 yf_mf8, yf_mk16, 0;\n"
        "\tmov.b64 {yf_mz0,yf_mz1}, yf_mf0;\n"
        "\tmov.b64 {yf_mz2,yf_mz3}, yf_mf1;\n"
        "\tmov.b64 {yf_mz4,yf_mz5}, yf_mf2;\n"
        "\tmov.b64 {yf_mz6,yf_mz7}, yf_mf3;\n"
        "\tadd.cc.u32 yf_mz1, yf_mz1, yf_mw0;\n"
        "\taddc.cc.u32 yf_mz2, yf_mz2, yf_mw1;\n"
        "\taddc.cc.u32 yf_mz3, yf_mz3, yf_mw2;\n"
        "\taddc.cc.u32 yf_mz4, yf_mz4, yf_mw3;\n"
        "\taddc.cc.u32 yf_mz5, yf_mz5, yf_mw4;\n"
        "\taddc.cc.u32 yf_mz6, yf_mz6, yf_mw5;\n"
        "\taddc.cc.u32 yf_mz7, yf_mz7, yf_mw6;\n"
        "\taddc.cc.u32 yf_mz8, yf_mf8, yf_mw7;\n"
        "\taddc.u32 yf_mz9, yf_mg8, 0;\n"
        "\tmul.lo.u32 yf_mk9, yf_mz9, 977;\n"
        "\tadd.cc.u32 yf_msfq, yf_mz8, yf_mk9;\n"
        "\taddc.u32 yf_msfh, yf_mz9, 0;\n"
        "\tmov.b64 yf_msfz, {yf_mz0, yf_msfq};\n"
        "\tmul.wide.u32 yf_msft, yf_mz8, 977; add.cc.u64 yf_msft, yf_msft, yf_msfz;\n"
        "\taddc.u32 yf_msfc, yf_msfh, 0;\n"
        "\tmov.b64 {yf_mz0, yf_msfhi}, yf_msft;\n"
        "\tadd.cc.u32 yf_mz1, yf_mz1, yf_msfhi;\n"
        "\taddc.u32 yf_mz2, yf_mz2, yf_msfc;\n"
        "\tmov.b64 %0, {yf_mz0,yf_mz1};\n"
        "\tmov.b64 %1, {yf_mz2,yf_mz3};\n"
        "\tmov.b64 %2, {yf_mz4,yf_mz5};\n"
        "\tmov.b64 %3, {yf_mz6,yf_mz7};\n"
#endif
        "}\n"
        : "=l"(r0), "=l"(r1), "=l"(r2), "=l"(r3)
        : "l"(a[0]), "l"(a[1]), "l"(a[2]), "l"(a[3]), "l"(b[0]), "l"(b[1]), "l"(b[2]), "l"(b[3]),
          "l"(c[0]), "l"(c[1]), "l"(c[2]), "l"(c[3]), "l"(d[0]), "l"(d[1]), "l"(d[2]), "l"(d[3]));
    r[0] = r0; r[1] = r1; r[2] = r2; r[3] = r3;
#else
    (void)r; (void)a; (void)b; (void)c; (void)d;
#endif
}

/* Seed: the pair itself (rlo = a = X3 - Q, rhi = b = R); no product. */
__device__ __forceinline__ void qsb_filter_mul16(uint64_t *rlo, uint64_t *rhi, const uint64_t *a, const uint64_t *b) {
    rlo[0] = a[0]; rlo[1] = a[1]; rlo[2] = a[2]; rlo[3] = a[3]; rhi[0] = b[0]; rhi[1] = b[1]; rhi[2] = b[2]; rhi[3] = b[3];
}
