#!/usr/bin/env bash
# Regenerate subset_sm89_cubin.h: the ranked module compiled ahead of time for
# sm_89 (RTX 4090) from THIS source tree, loaded by tests/gpu_epochs/native_module.cuh
# so the driver does not JIT the PTX inside the timed window.
#
# Mirrors the ranked build (nvcc -O3 -DQSB_ZEROS_N=24, default compute_52 PTX)
# and lowers that same PTX to sm_89 -- the code the driver JIT would produce.
# MUST be rerun after any change to device code; the header and the source are
# one unit. Usage: tools/build_sm89_cubin.sh   (from candidates/subset)
set -euo pipefail
cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
nvcc -O3 -DQSB_ZEROS_N=24 -DQSB_NATIVE_MODULE_BUILD \
     -gencode arch=compute_52,code=sm_89 -cubin -o "$tmp/m.cubin" subset.cu
cuobjdump -lelf "$tmp/m.cubin" | grep -q "sm_89" || { echo "cubin is not sm_89" >&2; exit 1; }
python3 - "$tmp/m.cubin" subset_sm89_cubin.h <<'PY'
import hashlib, sys
data = open(sys.argv[1], "rb").read()
lines = ["/* Generated by tools/build_sm89_cubin.sh from this source tree (nvcc -O3",
         " * -DQSB_ZEROS_N=24, compute_52 PTX lowered to sm_89). Do not edit.",
         " * bytes=%d sha256=%s */" % (len(data), hashlib.sha256(data).hexdigest()),
         "static const unsigned char qsb_sm89_cubin[] __attribute__((aligned(16))) = {"]
for i in range(0, len(data), 24):
    lines.append("".join("%d," % b for b in data[i:i + 24]))
lines.append("};")
open(sys.argv[2], "w").write("\n".join(lines) + "\n")
print("subset_sm89_cubin.h: %d bytes of sm_89 cubin, sha256 %s" % (len(data), hashlib.sha256(data).hexdigest()))
PY
