#!/usr/bin/env python3
"""Build the source-bound sm_89 module before submission; no runtime compiler."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile

FLAGS = ['-O3', '-DQSB_ZEROS_N=24', '-arch=sm_89']
EXCLUDED = {'NativeManifest.h'}


def closure(root):
    found = {}
    def visit(name):
        if name in found or name in EXCLUDED:
            return
        path = root / name
        data = path.read_bytes()
        found[name] = data
        for include in re.findall(rb'^\s*#\s*include\s*"([^"\n]+)"', data, re.M):
            child = (Path(name).parent / include.decode()).as_posix()
            if (root / child).exists():
                visit(child)
    visit('pinning.cu')
    return dict(sorted(found.items()))


def write_manifest(path, files, build_hash, cubin_hash, macros):
    rows = ['// Generated by research/build_native_module.py; do not edit.', '#pragma once',
            '// This generated file is excluded from the source hash to avoid a cycle.',
            '#define QSB_NATIVE_BUILD_BYTES {' + ','.join('0x'+build_hash[i:i+2] for i in range(0,64,2)) + '}',
            '#define QSB_NATIVE_CUBIN_SHA256 "'+cubin_hash+'"',
            'struct NativeManifestSource { const char *name; const char *sha256; };',
            'static const NativeManifestSource native_manifest_sources[] = {']
    rows.extend('    {"'+name+'","'+hashlib.sha256(data).hexdigest()+'"},' for name,data in files.items())
    rows.extend(['};', 'static bool qsb_native_generated_config_match() {'])
    for name, value in sorted(macros.items()):
        if value is None:
            rows.extend(['#ifdef '+name, '    return false;', '#endif'])
        else:
            rows.extend(['#ifndef '+name, '    return false;', '#else',
                         '    if(('+name+') != ('+value+')) return false;', '#endif'])
    rows.extend(['    return sizeof(void*)==8 && sizeof(int)==4;', '}',
                 '#define QSB_NATIVE_CONFIG_MATCH qsb_native_generated_config_match()', ''])
    path.write_text('\n'.join(rows))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--nvcc', default='nvcc')
    parser.add_argument('--readelf', default='readelf')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    source = root / 'pinning.cu'
    manifest = root / 'NativeManifest.h'
    cubin = root / 'pinning_sm89.cubin'
    files = closure(root)
    version = subprocess.check_output([args.nvcc, '--version'], text=True).strip()
    hashes = {name:hashlib.sha256(data).hexdigest() for name,data in files.items()}
    identity = {'source_sha256':hashes, 'flags':FLAGS+['--cubin'], 'compiler':version}
    build_hash = hashlib.sha256(json.dumps(identity, sort_keys=True, separators=(',',':')).encode()).hexdigest()
    # A temporary manifest permits preprocessing; the emitted device stamp is
    # already final. Host-only cubin checksum/configuration fields follow below.
    write_manifest(manifest, files, build_hash, '0'*64, {})
    names = sorted(set(re.findall(r'\b(?:QSB|GT)_[A-Z0-9_]+\b', '\n'.join(data.decode() for data in files.values()))))
    names = [name for name in names if not name.startswith('QSB_NATIVE_')]
    with tempfile.TemporaryDirectory(prefix='qsb-native-build-') as directory:
        probe = Path(directory)/'capture.cu'
        lines = ['#include "'+source.as_posix()+'"']
        for name in names:
            lines += ['#ifdef '+name, 'QSB_CAPTURE_'+name+' ('+name+')', '#else', 'QSB_CAPTURE_'+name+' UNDEFINED', '#endif']
        probe.write_text('\n'.join(lines)+'\n')
        process = subprocess.run([args.nvcc]+FLAGS+['-E', str(probe)], capture_output=True, text=True)
        if process.returncode:
            raise SystemExit(process.stderr)
        captures = dict(re.findall(r'^QSB_CAPTURE_([A-Z0-9_]+)\s+(.+)$', process.stdout, re.M))
        macros = {}
        skipped = []
        for name in names:
            value = captures[name].strip()
            if value=='UNDEFINED':
                macros[name] = None
            elif re.search(r'[0-9]', value) and re.fullmatch(r'[0-9a-fA-FxXuUlL\s()~!&|^<>?:*/%+\-]+', value):
                macros[name] = value
            else:
                skipped.append({'name':name,'expansion':value})
        write_manifest(manifest, files, build_hash, '0'*64, macros)
        command = [args.nvcc]+FLAGS+['--cubin', str(source), '-o', str(cubin)]
        process = subprocess.run(command, capture_output=True, text=True)
        if process.returncode:
            raise SystemExit(process.stderr)
    elf = cubin.read_bytes()
    if not (elf[:6]==b'\x7fELF\x02\x01' and elf[18:20]==b'\xbe\x00' and elf[48]==89):
        raise SystemExit('Generated artifact is not an ELF64 sm_89 cubin')
    symbols = subprocess.check_output([args.readelf,'-sW',str(cubin)],text=True)
    # Header is the single source of truth for runtime-required symbol names.
    helper = (root/'NativeModule.h').read_text()
    required = re.findall(r'"(_Z[A-Za-z0-9_]+)"', helper)
    required += re.findall(r'\{"(pin_[A-Za-z0-9_]+)",\d+,0\}', helper)
    required += ['qsb_native_source_stamp']
    missing = [name for name in required if not re.search(r'\s'+re.escape(name)+r'$',symbols,re.M)]
    if missing:
        raise SystemExit('Missing native symbols: '+', '.join(missing))
    cubin_hash = hashlib.sha256(elf).hexdigest()
    write_manifest(manifest, files, build_hash, cubin_hash, macros)
    report = dict(identity, build_sha256=build_hash, cubin_sha256=cubin_hash,
                  cubin_bytes=len(elf), required_symbols=required,
                  configuration=macros, nonnumeric_macros=skipped,
                  generated_manifest_excluded_from_source_closure=True)
    (root/'research/native_module_build.json').write_text(json.dumps(report,indent=2)+'\n')
    print('Native module: '+str(len(elf))+' bytes; '+str(len(required))+' symbols; '+str(len(macros))+' configuration guards; '+str(len(files))+' source files')
    print('Source/configuration stamp: '+build_hash)


if __name__=='__main__':
    main()
